### ISSUE TITLE
Parsing opengis schemas

### ISSUE THREAD

**Issue by beren5000** [sissaschool/xmlschema#123]
greetings

i'm trying to get an schema from an url, i make the request and encode to utf-8, then i'm trying to create the schema i get the next error
`__main__:1: XMLSchemaImportWarning: Namespace import failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>.
Traceback (most recent call last):
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 138, in lookup
    obj = global_map[qname]
KeyError: '{http://www.opengis.net/gml}AbstractFeatureType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/complex_types.py", line 251, in _parse_base_type
    base_type = self.maps.lookup_type(base_qname)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 256, in lookup_type
    return lookup_type(self.types, qname, self.validator.BUILDERS_MAP)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 141, in lookup
    raise XMLSchemaKeyError("missing a %s component for %r!" % (types_desc, qname))
xmlschema.exceptions.XMLSchemaKeyError: "missing a XsdSimpleType or XsdComplexType component for '{http://www.opengis.net/gml}AbstractFeatureType'!"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 364, in __init__
    self.maps.build()
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 454, in build
    self.lookup_type(qname)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 256, in lookup_type
    return lookup_type(self.types, qname, self.validator.BUILDERS_MAP)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/globals_.py", line 161, in lookup
    global_map[qname] = factory_or_class(elem, schema, parent=None)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/complex_types.py", line 73, in __init__
    super(XsdComplexType, self).__init__(elem, schema, parent, name)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 214, in __init__
    self.elem = elem
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/complex_types.py", line 93, in __setattr__
    super(XsdComplexType, self).__setattr__(name, value)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 228, in __setattr__
    self._parse()
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/complex_types.py", line 175, in _parse
    base_type = self._parse_base_type(derivation_elem, complex_content=True)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/complex_types.py", line 253, in _parse_base_type
    self.parse_error("missing base type %r" % base_qname, elem)
  File "/Applications/MAMP/htdocs/env/exactAIS/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 156, in parse_error
    raise error
xmlschema.validators.exceptions.XMLSchemaParseError: missing base type '{http://www.opengis.net/gml}AbstractFeatureType':

Schema:

  <xsd:extension xmlns:xsd="http://www.w3.org/2001/XMLSchema" base="gml:AbstractFeatureType">
    <xsd:sequence>
      <xsd:element maxOccurs="1" minOccurs="0" name="mmsi" nillable="true" type="xsd:long" />
      <xsd:element maxOccurs="1" minOccurs="0" name="imo" nillable="true" type="xsd:int" />
      <xsd:element maxOccurs="1" minOccurs="0" name="vessel_name" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="callsign" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_code" nillable="true" type="xsd:int" />
      <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_cargo" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="vessel_class" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="length" nillable="true" type="xsd:int" />
      <xsd:element maxOccurs="1" minOccurs="0" name="width" nillable="true" type="xsd:int" />
      <xsd:element maxOccurs="1" minOccurs="0" name="flag_country" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="flag_code" nillable="true" type="xsd:int" />
      <xsd:element maxOccurs="1" minOccurs="0" name="destination" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="eta" nillable="true" type="xsd:string" />
      <xsd:element maxOccurs="1" minOccurs="0" name="draught" nillable="true" type="xsd:double" />
      <xsd:element maxOccurs="1" minOccurs="0" name="position" nillable="true" type="gml:PointPropertyType" />
      <xsd:element maxOccurs="1" minOccurs="0" name="longitude" nillable="true" type="xsd:double" />
      <xsd:element maxOccurs="1" minOccurs="0" name="latitude" nillable="true" type="xsd:double" />
    ...
    ...
  </xsd:extension>

Path: /xsd:schema/xsd:complexType/xsd:complexContent/xsd:extension
`

the string of the schema that i get is this
'<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:exactAIS="/gws" xmlns:gml="http://www.opengis.net/gml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="/gws">\n  <xsd:import namespace="http://www.opengis.net/gml" schemaLocation="https://services.exactearth.com/gws/schemas/gml/3.1.1/base/gml.xsd"/>\n  <xsd:complexType name="LVIType">\n    <xsd:complexContent>\n      <xsd:extension base="gml:AbstractFeatureType">\n        <xsd:sequence>\n          <xsd:element maxOccurs="1" minOccurs="0" name="mmsi" nillable="true" type="xsd:long"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="imo" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_name" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="callsign" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_code" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_cargo" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_class" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="length" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="width" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="flag_country" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="flag_code" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="destination" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="eta" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="draught" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="position" nillable="true" type="gml:PointPropertyType"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="longitude" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="latitude" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="sog" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="cog" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="rot" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="heading" nillable="true" type="xsd:double"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="nav_status" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="nav_status_code" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="source" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="ts_pos_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="ts_static_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="ts_insert_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="dt_pos_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="dt_static_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="dt_insert_utc" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_main" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="vessel_type_sub" nillable="true" type="xsd:string"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="message_type" nillable="true" type="xsd:int"/>\n          <xsd:element maxOccurs="1" minOccurs="0" name="eeid" nillable="true" type="xsd:long"/>\n        </xsd:sequence>\n      </xsd:extension>\n    </xsd:complexContent>\n  </xsd:complexType>\n  <xsd:element name="LVI" substitutionGroup="gml:_Feature" type="exactAIS:LVIType"/>\n</xsd:schema>'

what could the error means?

thanks a lot for your answer and your great library

**Comment by brunato** [comment]
Hi,
it should be an SSL certificate verification error that causes an import fail:
```
main:1: XMLSchemaImportWarning: Namespace import failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED
```
then the missing components cause the fail of schema building. It's probably a wrong SSL configuration in your host because the remote site referenced by *schemaLocation* has a valid SSL certificate.

To workaround you can disable ssl certificate verification of urllib for the session or (safer) download schemas and then update *schemaLocation* to a local ref.

**Comment by beren5000** [comment]
thanks a lot for your fast answer. right now i'm testing and learning about both, xmlschema and the provider, then im working in my local environment. Could you guide me to disable the ssl certificate verification in the urllib?, i just want to know if i could parse the objects that im receiving to json for my research.

**Comment by brunato** [comment]
A simple solution to disable SSL verification for your session can be to import the *ssl* library before *xmlschema*, changing the default ssl context, as in the following example:

```python
>>> import ssl
>>> ssl._create_default_https_context = ssl._create_unverified_context
>>> from urllib.request import urlopen
>>> urlopen("https://self-signed.badssl.com/")
<http.client.HTTPResponse object at 0x7fd03ee88e48>
```
Bye

**Comment by beren5000** [comment]
thanks a lot Davide, i had tried this, but still had the same response, i know this is not an issue or a bug, but if you could lend me a hand could be great.

i tried using the workaround in the import as you suggest in the top of my file
`
import requests as rq
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import xmlschema
`

but still does not work, i tried to put it 
`    
def _get_schema(self, service_type):
        params = {
            'authKey': self.token,
            'request': self.requests.get('describe'),
            'typeName': service_type,
            'service': 'wfs',
            'version': self.version
        }
        schema = self.make_request(params).content
        schema = schema.decode("utf-8")
        schema = schema.rstrip()
        import ssl
        ssl._create_default_https_context = ssl._create_unverified_context
        import xmlschema
        schema = xmlschema.XMLSchema(schema)
        return schema
`
this is my function, the make request is using "requests" a library from python, it stills gives me the error:
XMLSchemaImportWarning: Namespace import failed: <urlopen error Unauthorized>.
  schema = xmlschema.XMLSchema(schema)
could i know which url is calling or in what other way i can workaround this?

**Comment by brunato** [comment]
Put ssl import before `import requests`:

```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import requests as rq
import xmlschema
```
Bye

**Comment by beren5000** [comment]
sorry, yhea i tried that one too, but still, gets me the same error

`
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import requests as rq
import xmlschema

from settings import GLOBAL_SETTINGS, SETTINGS


class ExactAIS:
    """
    library for use exact AIS in useitweb
    """
    params = {}

    def __init__(self, *args, **kwargs):
        self.user = SETTINGS.get("user")
        self.password = SETTINGS.get("pass")
        self.token = SETTINGS.get("token")

        self.base_url = GLOBAL_SETTINGS.get("base_url")
        self.version = GLOBAL_SETTINGS.get("version")

        self.requests = {
            'describe': 'DescribeFeatureType',
            'get': 'GetFeature'
        }

        self.layer_types = {
            'LVI': 'exactAIS:LVI'
        }

    def _get_schema(self, service_type):
        params = {
            'authKey': self.token,
            'request': self.requests.get('describe'),
            'typeName': service_type,
            'service': 'wfs',
            'version': self.version
        }
        schema = self.make_request(params).content
        schema = schema.decode("utf-8")
        schema = schema.rstrip()
        schema = xmlschema.XMLSchema(schema)
        return schema

    def make_request(self, params=None):

        url = self.base_url
        if not params:
            if not self.params:
                self.make_params()
            params = self.params

        try:
            # print('parametros: ', params)
            r = rq.get(url=url, params=params)
            print(r.url)
            return r
        except ConnectionError:
            raise Exception('Connection Error')

    def make_params(self):

        params = {
            'authKey': self.token,
            'request': self.requests.get('get'),
            'version': self.version,
            'service': 'wfs',
            'typeName': 'exactAIS:LVI',
            'outputFormat': 'gml3'
        }
        self.params.update(**params)

    def search_by_mmsi(self, mmsi):
        self.make_params()
        print(self.params)
        self.params.update({
            'cql_filter': "mmsi='{}'".format(str(mmsi))
        })
        print(self.params)
        return self.make_request()
`
