### ISSUE TITLE
how to export to xml once you edited the nested dictionnary

### ISSUE THREAD

**Issue by Gustutu** [sissaschool/xmlschema#125]
Hello,

how to export to xml a modified nested dictionnary imported  from an xml.

Thanks

**Comment by brunato** [comment]
Hi,

I'm not sure to interpret in the right way your request, but schema class and XSD components include encode methods to convert back the decoded dictionary to XML data. If you mean instead to convert and save to an XML file, after the encode use the *tostring()* method of ElementTree / lxml libraries or the *xmlschema.etree.etree_tostring()* internal method to serialize and a file object to save the XML data.
