### ISSUE TITLE
TypeError in xmlschema.validators.identities.XsdIdentity.validator

### ISSUE THREAD

**Issue by paragguruji** [sissaschool/xmlschema#127]
The method **xmlschema.validators.identities.XsdIdentity.validator** maintains a Counter to capture "duplicated values" error.

However, **if any of the values discovered by iter_values is not Hashable, the parsing fails with a TypeError**. The tricky part here is, although the method _iter_values_ is returning tuple which is a Hashable, there can be non-hashable elements (e.g. dict) within such tuple. 

A real-world example from my work where I was trying to parse a large XML file containing financial data, complying with the XSD schema from the data-providing vendor, I get value from iter_values similar in structure to:
`('FOO BAR', {'BAZ': 123, '$': 'ABC'})`
This throws a TypeError as the inner dict within this value doesn't let the Counter use the value as a key. 

I have implemented a basic workaround that solves this issue at the cost of time complexity O(n) for checking duplicates among non-hashable values (while maintaining O(1) complexity for hashable values by continuing to use the Counter for them).

I am creating a PR with my solution. Hoping for comments and suggestions on any loopholes or any more efficient ways to resolve this issue.

**Comment by brunato** [comment]
Hi,
the error is caused by erroneous decoding of values in method *get_fields()*, that doesn't return a value when the field refers to a complex type element with attributes.
I've put a resolution for this in my develop, that will be published soon.

**Comment by brunato** [comment]
Fix available with release v1.0.14
