### ISSUE TITLE
Getting additional global type information?

### ISSUE THREAD

**Issue by matkuki** [sissaschool/xmlschema#131]
Hi,

Is there a way to get additional information about a `type`.
For example, if I have this `complexType` in a `.xsd` file:
```xml
<xs:complexType name="CompType">
  <xs:all>
   <xs:element name="FirstElement" type="FirstElementType"/>
   <xs:element name="SecondElement" minOccurs="0" type="SecondElementType"/>
  </xs:all>
 </xs:complexType>
```
is it possible to get information about the `CompType` (I used the format of Python dictionaries just as an example):
```
comp_type = {
    "name": "CompType",
    "attributes": None,
    "elements" : {
        "FirstElement": { "type": "FirstElementType" },
        "SecondElement": { "type": "SecondElementType", "minOccurs": "0"}
    }
}
```
The format is unimportant, I just want to know how to get this information from a `type`.
Any ideas?

Thanks

**Comment by brunato** [comment]
Hi,
if you have a schema `xs` the types are mapped into the dictionary `xs.types`. In this case `xs.types['CompType']` is the object that represents your complex type.
So if you set `comp_type = xs.types['CompType']` the information of the type can be accessed with:

```python
comp_type.name  # a string 
comp_type.attributes  # an empty attribute group
comp_type.content_type  # a model group with two elements
comp_type.content_type[0]  # the "FirstElement"
comp_type.content_type[1]  # the "SecondElement"
comp_type.content_type[0].type  # the "FirstElement" type
comp_type.content_type[0].min_occurs  
```

**Comment by matkuki** [comment]
Excellent, works like a charm. Thanks!
