### ISSUE TITLE
Issue with parsing XBRL

### ISSUE THREAD

**Issue by gunjanbadhey** [sissaschool/xmlschema#132]
Hi,
I tried parsing XBRL document but getting error. Below is the code snippets. Sample files attached with this message.
**Code:**
import xmlschema
file = 'D:/Python Code/finrep/Taxonomy/XBRL/IllustrativeInstanceFiles.2.8.1.1-Errata/WithRandomValues/DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.xbrl'
schema_file = "D:/Python Code/finrep/Taxonomy/XBRL/Taxonomy Packages.2.8.1.1/EBA_CRD_IV_XBRL_2.8_Reporting_Frameworks_2.8.1.1/www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd"

#try1
my_schema = xmlschema.XMLSchema("http://www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd")
#try 2
my_schema = xmlschema.XMLSchema(schema_file,validation='lax')

my_schema.is_valid(file)
#If validation is fail then check where it is failing
**my_schema.validate(file)**

Above line gives me below error. Could you please help?

**Output Error:**
my_schema.validate(file)
Traceback (most recent call last):

  File "<ipython-input-39-8fe7c9e91a7d>", line 1, in <module>
    my_schema.validate(file)

  File "C:\ProgramData\Anaconda3\lib\site-packages\xmlschema\validators\schema.py", line 1089, in validate
    raise error

XMLSchemaValidationError: failed validating <Element '{http://www.xbrl.org/2003/instance}xbrl' at 0x000001B9E5838818> with XMLSchema10(basename='finrep9_ind_ifrs.xsd', namespace='http://www.eba.europa.eu/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/FINREP9_Ind_IFRS'):

Reason: <Element '{http://www.xbrl.org/2003/instance}xbrl' at 0x000001B9E5838818> is not an element of the schema

Instance:

  <xbrli:xbrl xmlns:eba_met="http://www.eba.europa.eu/xbrl/crr/dict/met" xmlns:eba_typ="http://www.eba.europa.eu/xbrl/crr/dict/typ" xmlns:find="http://www.eurofiling.info/xbrl/ext/filing-indicators" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink">
    <link:schemaRef xlink:href="http://www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd" xlink:type="simple" />
    <xbrli:unit id="uPURE">
      <xbrli:measure>xbrli:pure</xbrli:measure>
    </xbrli:unit>
    <xbrli:context id="c1">
      <xbrli:entity>
        <xbrli:identifier scheme="http://standards.iso.org/iso/17442">DUMMYLEI123456789012</xbrli:identifier>
      </xbrli:entity>
      <xbrli:period>
        <xbrli:instant>2018-12-31</xbrli:instant>
      </xbrli:period>
    </xbrli:context>
    <find:fIndicators>
      <find:filingIndicator contextRef="c1">F_00.01</find:filingIndicator>
      <find:filingIndicator contextRef="c1">F_01.01</find:filingIndicator>
      <find:filingIndicator contextRef="c1">F_01.02</find:filingIndicator>
      <find:filingIndicator contextRef="c1">F_01.03</find:filingIndicator>
      <find:filingIndicator contextRef="c1">F_02.00</find:filingIndicator>
      <find:filingIndicator contextRef="c1">F_03.00</find:filingIndicator>
    ...
    ...
  </xbrli:xbrl>

[xsd.zip](https://github.com/sissaschool/xmlschema/files/3613761/xsd.zip)
[DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.zip](https://github.com/sissaschool/xmlschema/files/3613762/DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.zip)

**Comment by gunjanbadhey** [comment]
any solution to this?

**Comment by brunato** [comment]
Hi,
sorry but not yet. It's a pretty complex case of usage of substitution groups with elements in different namespaces. 
I'will try to solve before the new release that will come out in a couple of days.

**Comment by gunjanbadhey** [comment]
Thanks Brunato.

**Comment by brunato** [comment]
A new release is available but this issue is still not fixed. I've to fix before some similar W3C tests, that still fail, to made something that can resolve this without break other parts. It's complicated because it involves the some changes to substitution groups usage. 

A note about the schema building. With the just published release you can try to build the schema passing the new optional argument *loglevel*:

  my_schema = xmlschema.XMLSchema("http://www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd", loglevel=20)

this should show you the loading of each namespace and its source. This also show that your uploaded schema file (xsd.zip) does not contain all necessary schemas. Maybe this can be fixed with the dowload of all schema files from the reference site, that can be made the building of the schema faster.

Bye

**Comment by brunato** [comment]
Hi,

this issue should be fixed in release v1.0.16, but with a consideration. The XML instance needs additional namespaces (the first is "http://www.eba.europa.eu/xbrl/crr/dict/met", reported by the validation error) so you need to import the missing namespaces. For example:

```python
>>> import xmlschema
>>> schema_url = "http://www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd"
>>> my_schema = xmlschema.XMLSchema(schema_url)
>>> my_schema.is_valid("DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.xbrl")
False
>>> my_schema.import_schema("http://www.eba.europa.eu/xbrl/crr/dict/met", "https://eba.europa.eu/eu/fr/xbrl/crr/dict/met/met.xsd")
XMLSchema10(basename='met.xsd', namespace='http://www.eba.europa.eu/xbrl/crr/dict/met')
>>> my_schema.build()
>>> my_schema.is_valid("DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.xbrl")
True
```

or passing custom location at schema class init:

```python
>>> import xmlschema
>>> schema_url = "http://www.eba.europa.eu/eu/fr/xbrl/crr/fws/finrep/cir-680-2014-ind/2018-03-31/mod/finrep9_ind_ifrs.xsd"
>>> locations = [("http://www.eba.europa.eu/xbrl/crr/dict/met", "https://eba.europa.eu/eu/fr/xbrl/crr/dict/met/met.xsd")]
>>> my_schema = xmlschema.XMLSchema(schema_url, locations=locations)
>>> my_schema.is_valid("DUMMYLEI123456789012_GB_FINREP020202_FINREP9INDIFRS_2018-12-31_20180802120228000.xbrl")
True
```

**Comment by gunjanbadhey** [comment]
Thanks Brunato, I will try this.

**Comment by gunjanbadhey** [comment]
It is working and converting to Dict. thanks. I will further check this week.
