### ISSUE TITLE
Validation against schema v1.1

### ISSUE THREAD

**Issue by msenra** [sissaschool/xmlschema#133]
I've been testing your project, but unfortunately for me, I was unsuccessful with validation with schema version 1.1.
I send the files I used to test.

[Saft Demo AT.zip](https://github.com/sissaschool/xmlschema/files/3616908/Saft.Demo.AT.zip)

**Comment by brunato** [comment]
Hi,
I've tested your case in my develop branch that has several fixes for XSD 1.1. 
It seems to be a problem with an _xs:assert_ expression that is not validated. This has to be fixed in _elementpath_ package.

**Comment by msenra** [comment]
Thanks for the feedback. 
Any idea when this could be fixed?

**Comment by brunato** [comment]
I think that can be a pair of weeks if the fix doesn't involve a big changes in _elementpath_. Also a new release of xmlschema is needed to patch errors on assertions validation.

**Comment by brunato** [comment]
Hi,
I've fixed this, the new release will be available in a couple of days. It has required many improvements to _elementpath_ for completing the XSD type matching.

**Comment by msenra** [comment]
thank you!

**Comment by brunato** [comment]
The new release v1.0.15 is available. It fixes the bug through the improvements introduced in *elementpath-1.3.0*.
Bye
