### ISSUE TITLE
Create random xml

### ISSUE THREAD

**Issue by morell5** [sissaschool/xmlschema#134]
Hello, everyone!

Does **class XsdComplexType** has a method generating XML document correspoding such ComplexType? Are any other ways generating XML?

**Comment by brunato** [comment]
Hi,
no this feature is not available. Currently each component is linked to the schema element that defines it (the best match) but there isn't a method to compose these elements (the component and other bases) into a document. This task may be feasible for simple situations (eg. one namespace, one XSD document) but can be pretty complicated in composed situations.

**Comment by morell5** [comment]
Can this library generate Python classes represents each type with setters , getters and export to XML like generate.DS or PyXB?

**Comment by brunato** [comment]
No it doesn't, generating code is not the goal of this library. Code generation maybe a topic of another package, that use this library as schemas parser. For example we are going to use Jinja2 and xmlschema for generating Fortran types for an input interface.
