### ISSUE TITLE
Issue parsing XSD with attributeGroup ref to XLINK

### ISSUE THREAD

**Issue by arifshaon** [sissaschool/xmlschema#137]
Hello,

I am trying to parse a local copy of METS.xsd (http://www.loc.gov/standards/mets/mets.xsd) file with local reference to XLINK.xsd but getting the following parsing error:

xmlschema.validators.exceptions.XMLSchemaParseError: unknown attribute group 'xl
ink:simpleLink':

Schema:

  <xsd:complexType xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="objectType
">
      <xsd:annotation>
          <xsd:documentation xml:lang="en">objectType: complexType for interface
Def and mechanism elements
              The mechanism and behavior elements point to external objects--an
interface definition object or an executable code object respectively--which tog
ether constitute a behavior that can be applied to one or more &lt;div&gt; eleme
nts in a &lt;structMap&gt;.
          </xsd:documentation>
      </xsd:annotation>
      <xsd:attribute name="ID" type="xsd:ID" use="optional">
          <xsd:annotation>
              <xsd:documentation xml:lang="en">ID (ID/O): This attribute uniquel
y identifies the element within the METS document, and would allow the element t
o be referenced unambiguously from another element or document via an IDREF or a
n XPTR. For more information on using ID attributes for internal and external li
nking see Chapter 4 of the METS Primer.
              </xsd:documentation>
          </xsd:annotation>
      </xsd:attribute>
      <xsd:attribute name="LABEL" type="xsd:string" use="optional">
          <xsd:annotation>
              <xsd:documentation xml:lang="en">LABEL (string/O): A text descript
ion of the entity represented.
              </xsd:documentation>
          </xsd:annotation>
      </xsd:attribute>
      <xsd:attributeGroup ref="LOCATION" />
      <xsd:attributeGroup ref="xlink:simpleLink" />
  </xsd:complexType>

Path: /xsd:schema/xsd:complexType[12]

I have tried using both Python 2.7 and Python 3.8.
Please note that XMLSpy parses the file without any issue.

Please advise.

Best regards
Arif

**Comment by brunato** [comment]
Hi,
found a fix for this. The problem happens because XLink is loaded in meta-schema. So I have removed XLink from meta-schema and add it to a set of fallback locations hints, like is now for XHTML (some schemas use them without an explicit location hint). Will be available in a couple of days with the new release.

**Comment by brunato** [comment]
The new release v1.0.15 that fix this issue is available.
Best regards
