### ISSUE TITLE
Validation against multiple XSDs

### ISSUE THREAD

**Issue by arifshaon** [sissaschool/xmlschema#140]
I am not sure if this is intended to be within the scope of xmlschema. But I have been trying to validate an XML document against multiple schemas using the following the method. While the schemas load OK, validation always fails.  Please note that this works with tools like XMLSpy or using Java (javax.xml.validation.Validator).

Combined schema:

<xs:schema xmlns="http://dummy.libxml2.validator" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://dummy.libxml2.validator" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:import namespace="http://www.loc.gov/METS/" schemaLocation="http://www.loc.gov/standards/mets/mets.xsd"/>
	<xs:import namespace="http://www.loc.gov/mods/v3" schemaLocation="http://www.loc.gov/standards/mods/v3/mods-3-4.xsd"/>
	<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.loc.gov/standards/xlink/xlink.xsd"/>
	<xs:import namespace="http://cosimo.stanford.edu/sdr/metsrights/" schemaLocation="http://www.loc.gov/standards/rights/METSRights.xsd"/>
</xs:schema>

XML snippet:

<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:premis="info:lc/xmlns/premis-v2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rts="http://cosimo.stanford.edu/sdr/metsrights/" xmlns:bl="http://bl.uk/namespaces/bldigitized" xmlns:blprocess="http://bl.uk/namespaces/blprocess" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd http://bl.uk/namespaces/blprocess http://www.bl.uk/schemas/blprocess/blprocess.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-4.xsd info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/premis.xsd http://www.w3.org/1999.xlink http://www.loc.gov/standards/xlink/xlink.xsd http://cosimo.stanford.edu/sdr/metsrights/ http://www.loc.gov/standards/rights/METSRights.xsd" TYPE="DCW">
................

Error:

xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{http://www.loc.gov/METS/}mets' at 0xa1f5830> with XMLSchema10(namespace='http://dummy.libxml2.validator"):

Reason: <Element '{http://www.loc.gov/METS/}mets' at 0xa1f5830> is not an element of the schema

Please advise what I might be doing wrong or if this type of validation is not supported.

Thanks very much
Arif

**Comment by brunato** [comment]
Hi,
This is almost sure related to issue #132 and I try to fix that for next release. Leave this open, I will inform you next.

**Comment by brunato** [comment]
Hi, new release v1.0.16 is available. Check if it works now and in this case close the issue.

**Comment by arifshaon** [comment]
Works like a charm now!
Many thanks!!
