### ISSUE TITLE
Use of encode to XML

### ISSUE THREAD

**Issue by gtluu** [sissaschool/xmlschema#141]
Hi, I have loaded in XML data using the following:

`xsd = xmlschema.XMLSchema(xsd_file)
xml = xsd.to_dict('xml_file')`

I was wondering how to convert data from the nested dictionary back to an XML file. I've seen the encode() and iter_encode() functions but I'm not sure of exactly how to use them. Thank you.

**Comment by brunato** [comment]
Hi,
nested dictionary data (or an equivalent JSON file) can be re-encoded back to XML if you use the same [converter](https://xmlschema.readthedocs.io/en/latest/converters.html) convention (the default converter maybe sufficient for your needs). The method to use is **_encode_**, passing the object and the validation mode ('strict' or 'lax', use the second one if you are not sure about the full correctness of data). The method _iter_encode_ is a generator at the base of encoding, to use if you need to build a custom encode procedure, so probably you don't to use at first.
Bye
