### ISSUE TITLE
Catalog support

### ISSUE THREAD

**Issue by iamahuman** [sissaschool/xmlschema#142]
~The package seems to neither include the W3C standard schemes nor support any caching mechanisms, causing the validator to fetch from [the slow W3C servers](https://www.w3.org/Help/Webmaster#slowdtd) every time it loads a scheme.~ I was wrong, I was only considering http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd .

Since catalog management might not exactly be in the scope of the project, are there any plans to include a fixed built-in scheme catalog and/or let a user supply a custom resource resolver instead of a hard-coded Python `urllib` standard library dependency? Supplying a custom opener may be sufficient for some applications but might interfere with other modules depending on the same facility.

**Comment by brunato** [comment]
Hi,
there are some W3C standard schemas included in the package (see xmlschema/validators/schemas/ in the source):
  - XSD meta-schemas 
  - XSI schema
  - XML schema
 - XHTML 1.0
 - XLink
 - Schema versioning

XSD/XSI/XML and VC schemas are already loaded in meta-schema instance. XLink and XHTML 1 are loaded when required and no explicit remote location is provided. I have no plan to add or maintain a catalog, so I've provided a `locations` optional argument to schema class init to override or add specific namespace/resources (usually from local filesystem).
