### ISSUE TITLE
XsdElement.iter_encode does not use the default schema converter anymore

### ISSUE THREAD

**Issue by bdauvergne** [sissaschool/xmlschema#144]
I was initializing my schema with `XMLSchema(..., converter=xmlschema.UnorderedConverter)`, and later doing an `schema.elements['MyElement'].encode(some_data)` (`some_data` is unserialized JSON so unordered decoding is mandatory), with commit df6eb2351 iter_encode does not get self.schema.converter as its default encoder anymore breaking this usage. I was forced to change previous code to `.encode(some_data, converter=xmlschema.UnorderedConverter)`.

Was it an expected change or was I misusing the API ?

**Comment by brunato** [comment]
Hi,
you usage of the API is correct and this is an unexpected change. From the commit that you report some changes are made to simplify parameters propagation on the nested generators calls. I'll produce a test for finding the problem and write a fix.

Thank you
Davide

**Comment by bdauvergne** [comment]
Would you like me to contribute some test case ?

**Comment by brunato** [comment]
> Would you like me to contribute some test case ?

Sure! Create a PR with ore or more cases that reproduce the encoding issue.
Thanks

**Comment by bdauvergne** [comment]
I mistakenly added `fixes` to my commit message, this issue should be reopened until the underlying problem is really fixed.
