### ISSUE TITLE
"Wrong content type <class 'str'>" when encoding text from dictionary to xml

### ISSUE THREAD

**Issue by theducvu** [sissaschool/xmlschema#153]
Hi, I saw you mention that informative error reporting has been implemented, but I am still struggling with encoding text fields from dict to xml.

My problem is related to the ONIX for books 3.0 XSD schema. Currently I'm receiving "Wrong content type <class 'str'>" (or 'bytes' if i encode the string into utf-8) when I try to encode text into the text fields. The thing is, I'm not sure what type is expected. Is there a way to figure out which type is expected?

I am using python 3.7.1, and xmlschema 1.0.16.

**Expected result:** The text is encoded into the xml file. 

**Actual result:** This error is returned if validation is 'strict':

```
<Element '{http://www.w3.org/2001/XMLSchema}complexType' at 0x0000020B53949C78>
<Element '{http://ns.editeur.org/onix/3.0/reference}BiographicalNote' at 0x0000020B5558A908>
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{http://ns.editeur.org/onix/3.0/reference}BiographicalNote' at 0x0000020B5558A908> with XsdGroup(model='sequence', occurs=[1, 1]):

Reason: wrong content type <class 'str'>

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" mixed="true">
      <xs:complexContent>
          <xs:extension base="Flow">
              <xs:attribute name="refname">
                  <xs:simpleType>
                      <xs:restriction base="xs:token">
                          <xs:enumeration value="BiographicalNote" />
                      </xs:restriction>
                  </xs:simpleType>
              </xs:attribute>
              <xs:attribute name="shortname">
                  <xs:simpleType>
                      <xs:restriction base="xs:token">
                          <xs:enumeration value="b044" />
                      </xs:restriction>
                  </xs:simpleType>
              </xs:attribute>
              <xs:attributeGroup ref="generalAttributes" />
              <xs:attributeGroup ref="languageAttribute" />
              <xs:attributeGroup ref="textformatAttribute" />
      ...
      ...
  </xs:complexType>

Instance:

  <BiographicalNote xmlns="http://ns.editeur.org/onix/3.0/reference" />
```

If the validation is 'lax', the Text fields are encoded without any text, same errors are returned.

This is the full BiographicalNote portion in the ONIX 3 XSD file:
```
<xs:element name="BiographicalNote">
	<xs:complexType mixed="true">
		<xs:complexContent>
			<xs:extension base="Flow">
				<xs:attribute name="refname">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="BiographicalNote" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="shortname">
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="b044" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attributeGroup ref="generalAttributes" />
				<xs:attributeGroup ref="languageAttribute" />
				<xs:attributeGroup ref="textformatAttribute" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:element>
```

Hoping someone who is more familiar with xml and xsd can take a look and tell me what I'm missing.

**EDIT**: I manage to get the text field through by passing in a list of dictionaries: {'@textformat': 05, '$': text} but the text still does not show up in the final xml output.
```
<Text textformat="05"/>
```

**Comment by theducvu** [comment]
Update: I looked into it further and it seems xmlschema is not able to see the text in any such text field.

I tried decoding a sample ONIX 3 file with this field:

```
<Text textformat="05"><p><strong>Perennial relaunches the first novel in the classic Martin Beck detective series from the 1960s</strong> – the novels that have inspired all crime fiction written ever since.</p></Text>
```

Here's the same field in the result dictionary:

```
 'Text': [{'@textformat': '05',
    'p': {'strong': None}}],
```

So essentially the text was just not visible to the schema somehow.

The function I used:

```
schema = xmlschema.XMLSchema('ONIX_BookProduct_3.0_reference.xml')
schema.decode(open('sample.xml', 'r'), validation='lax')
```

**Comment by brunato** [comment]
Hi,
the schema requires those schemas to be built without errors:

  ONIX_BookProduct_3.0_reference.xsd
  ONIX_BookProduct_CodeLists.xsd
  ONIX_XHTML_Subset.xsd

have you a link to *sample.xml* or could you upload a full XML sample document in order to reproduce the error?
Thanks

**Comment by theducvu** [comment]
Thanks for your reply. I am using those files for the schema.

This is the sample file I used, a rather standard ONIX sample file.

[Onix3sample_refnames.zip](https://github.com/sissaschool/xmlschema/files/3987196/Onix3sample_refnames.zip)

To reproduce my issue:
```
schema = xmlschema.XMLSchema11('ONIX_BookProduct_3.0_reference.xsd')
with open('Onix3sample_refnames.xml') as f:
    d = schema.decode(f)
print([x['Text'] for x in d['Product'][0]['CollateralDetail']['TextContent']])

#  Result
# [[{'@textformat': '05'}], [{'@textformat': '05', 'p': [None, {'em': None}, {'em': None}, {'em': None}]}], [{'@textformat': '05', 'p': None}], [{'@textformat': '05', 'p': None}], [None]]
```

**Comment by brunato** [comment]
Hi,
in your sample there is the usage of XSD 1.1 but my schema is also for XSD 1.0. And the sample is invalid with the schemas that i use. Could you please give me a link to you schema sources (maybe it's a more recent version, eg. 3.0.4?).
Thanks

**Comment by brunato** [comment]
Finally I found schemas at https://www.editeur.org/93/Release-3.0-Downloads/ ...

```python
>>> import xmlschema
>>> import xml.etree.ElementTree as et
>>> from xmlschema.etree import etree_elements_assert_equal
>>> xs = xmlschema.XMLSchema("ONIX_BookProduct_3.0_reference.xsd")
>>> d = xs.decode('Onix3sample_refnames.xml', cdata_prefix='#')
>>> elem = xs.maps.elements['{http://ns.editeur.org/onix/3.0/reference}ONIXMessage'].encode(d, cdata_prefix='#')
>>> root = et.parse('Onix3sample_refnames.xml').getroot()
>>> etree_elements_assert_equal(root, elem, strict=False)
```

The schema has an its own XHTML implementation and some contents are endoded in character data fragments. So you need to provide cdata_prefix='#' to decode/encode these fragments (for default character data parts are not decoded.
 Bye
