### ISSUE TITLE
iter_errors question.

### ISSUE THREAD

**Issue by msenra** [sissaschool/xmlschema#156]
Hi

Can you please give an example of how to access the error list and prevent it from stopping on the first error?

Best regards.

**Comment by brunato** [comment]
Hi,
with v1.0.17 you can use the API at document level, for example:

```python
import xmlschema
errors = [e for e in xmlschema.iter_errors(xml_filename, schema=xsd_schema_filename, lazy=True)]
```
The argument *lazy* is not required, but it's useful if you want to consume less memory during validation. The argument *schema* is required if your XML file doesn't contain schema location hints.
Bye
