### ISSUE TITLE
decode's `schema_path` argument now fails to find non-global types

### ISSUE THREAD

**Issue by danifus** [sissaschool/xmlschema#157]
Hi,

I've created a branch (https://github.com/danifus/xmlschema/tree/schema_path) with a failing test when specifying the `schema_path` arg for a non-global element in `decode()`.

This worked for me in v1.0.15 but has stopped working since.

I've been able to get it to work again with the following changes but I'm not sure if it is the correct approach:

from:
```
def iter_decode(self, obj, path=None, validation='lax', namespaces=None, converter=None,
                    unordered=False, **kwargs):
    ...
        if namespace:
            try:
                schema = self.maps.namespaces[namespace][0]
            except (KeyError, IndexError):
                reason = 'the namespace {!r} is not loaded'.format(namespace)
                raise XMLSchemaEncodeError(self, obj, self, reason, namespaces=namespaces)
            else:
                xsd_element = schema.find(path, namespaces=namespaces)
```

to:
```
def iter_decode(self, obj, path=None, validation='lax', namespaces=None, converter=None,
                    unordered=False, **kwargs):
    ...
        if namespace:
            try:
                schema = self.maps.namespaces[namespace][0]
            except (KeyError, IndexError):
                schema = self
            else:
                xsd_element = schema.find(path, namespaces=namespaces)
```
in a couple of locations.

Let me know if you need anything else to resolve this.

Cheers,
Dan

**Comment by brunato** [comment]
Hi @danifus ,

the current code is different now (tests will be moved out the codebase) so i will reuse your test in v1.1.0 for confirming the fix.
In your sample there is a typo with encode's code. Anyway if have to put a fix for the decode part this is my code snippet for patching v1.0.18:

https://github.com/sissaschool/xmlschema/blob/7d1ff4f6172715b24f92ce1da4fa3baa8d97e1e1/xmlschema/validators/schema.py#L1378-L1383

```python
        try:
            schema = self.maps.namespaces[namespace][0]
        except (KeyError, IndexError):
            if namespace or not schema_path:
                reason = 'the namespace {!r} is not loaded'.format(namespace)
                yield self.validation_error('lax', reason, source.root, source, namespaces)
                return
            schema = self
``` 
The patch for previous releases can be similar considering, if a schema for the namespace is not found, the only admitted case is if the schema path is not None (maybe a schema path or a path is provided) and the source has no namespace.
Thanks
Davide

**Comment by danifus** [comment]
Thanks for your help! I'll put this code into my project while I await 1.1.0 :)

**Comment by brunato** [comment]
Hi,
published a new release. The code snippet of this issue has been included in the helper method *XMLSchema.get_schema()*.
Significative updates on decoding in v1.1.0, eg. a raw_decoder() for implementing lazy decoders (JSON lazy encoding as first tentative).

Bye

**Comment by danifus** [comment]
Thanks! That is working for me now :)
