### ISSUE TITLE
Assertion for mutually exclusive attributes is failing

### ISSUE THREAD

**Issue by jmeile** [sissaschool/xmlschema#171]
Hi

I want to have an assertion on my xsd file to intruduce mutually exclusive attributes (only one can be present). So, I defined the following files:

**test.xsd:**
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
		   vc:minVersion="1.1"
>
  <xs:element name="tag">
    <xs:complexType>
      <xs:sequence/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="abc" use="optional" type="xs:integer"/>      
      <xs:attribute name="def" use="optional" type="xs:integer"/>
      <xs:assert test="(@abc and not(@def)) or (not(@abc) and @def)"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

**test.xml:**
```
<?xml version="1.0" encoding="utf-8"?>
<tag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 name="test" abc="10" def="0"/>
```

Then running the following code:
```
import xmlschema
from pprint import pprint

schema_name = 'test.xsd'
xml_file_name = 'test.xml'
my_schema = xmlschema.XMLSchema11(schema_name)
pprint(my_schema.is_valid(xml_file_name))
pprint(my_schema.validate(xml_file_name))
pprint(my_schema.to_dict(xml_file_name))
```

will successfully validate the schema; however, if you see, "abc" and "def" are both present. I think the main error here is that python evaluates '0' (zero) as False and so the logic error comes. I think for this case would be much more practical to evaluate if "def" is "None", which is indeed what I'm looking for.

I think this is a bug on the implementation of xmlschema, which is using the boolean evaluation of python. Or perhaps there is a way of changing this on an "xs:assert", perhaps a "is None" function?

Best regards
Josef

**Comment by jmeile** [comment]
Ok, this seems to be a problem with the implementation of xpath, see:
https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/boolean

So, is the same as with python. NaN (None in python) will be evaluated to False. I tried the following assert:
`<xs:assert test="(@abc and @def != NaN) or (@abc != NaN and @def)"/>`

but it keeps failing. So, I found this explanation:
https://stackoverflow.com/questions/3854345/xpath-test-if-node-value-is-number

See the answer from "Dimitre Novatchev". In short he said:
> NaN is not equal to any other value, even to itself.

So that assert will failed. Dimitre added that NaN can't be used as a number, so, a way of copying this would be to check this on the assert. So, I replaced my assert with this:
```
<xs:assert test="(@abc and not(@def) and (number(@def) != number(@def))) or 
			   (not(@abc) and (number(@abc) != number(@abc)) and @def)"/>
```

To be honest, I don't like it, but it works.

Does somebody have a better solution?

**Comment by jmeile** [comment]
I found these workarounds:
- Use the two above assertions (they are ugly and unclear, but they seem to work)

- If you can, then use numbers that do not include the zero, then the simplest assertion:
`      <xs:assert test="(@abc and not(@def)) or (not(@abc) and @def)"/>`
will work. On my use case, I can use this since my integers are meant to be array indexes, but humans start them usually with '1', so, inside python I will just substract 1 to the obtained value.

- You can also use strings instead of numbers. However, if you need to validate that your number is inside a range with minInclusive and maxInclusive, I don't think this will work for strings, so here the options:
  - Try minInclusive and maxInclusive and see if this works
  - Or create an assertion that casts your string values to integer, then check that it is inside the range

Additionally if working with strings, you will also have to use a regex to check that your value is a number.

I would appreciate if somebody else has a better workaround, ie: include somehow a user defined function, ie: isNaN

**Comment by jmeile** [comment]
I know that this is a little bit off topic with this issue, but I also want to congratulate you for this library. It seems to be one of the few supporting XML 1.1. There are other alternatives, but they don't work with this new XML version and some of them are outdated.

**Comment by brunato** [comment]
Hi,
thank you for the thread on this. I try to summarize with short comment on each your ones.

**About the first assert expression:**
  
`<xs:assert test="(@abc and not(@def)) or (not(@abc) and @def)"/>`

consider that in also in XPath not('0') is false and not(0) is true as a not-empty string is considered equivalent to true and 0 is equivalent to false. With schema `@def` is evaluated as an integer, and its value is 0, so not(0) is true. Without schema the evaluation is different.

**About the 2nd assert expression:**

`<xs:assert test="(@abc and @def != NaN) or (@abc != NaN and @def)"/>`

As I know NaN cannot be expressed in an XPath expression as a symbol, but has to be written using a type constructor like `xs:float('NaN')` or with a type casting.

**Workarounds**

I prefer this workaround:

`<xs:assert test="(@abc and not(@def castable as xs:double)) or 
		   (not(@abc castable as xs:double) and @def)"/>`

I think it's better than working with strings or put limitations on indexes. Also defining custom function maybe a less simple solution.

 
For issues related to XPath and builtin XSD datatypes maybe better opening an issue for *elementpath* library including little schema/instance samples like you do in this case.

Thank you

**Comment by brunato** [comment]
Nothing to improve on this at the moment.

**Comment by brunato** [comment]
Hi,

for this issue I will change in next version restoring the _effective boolean value_ of schema-typed attributes (elements) to be always `True`. The XPath standard is clear on this and the EBV of an integer attribute has to be `True` also if the value is "0".

For a confirmation I've tried a simpler assertion with another robust XSD 1.1 validator (xerces):
  
  `<xs:assert test="@abc and @def"/>`

With this assertion the following XMLs are reported as valid:

`<tag name="test" abc="10" def="1"/>`
`<tag name="test" abc="10" def="0"/>`
`<tag name="test" abc="0" def="0"/>`

and these are invalid:

`<tag name="test" def="1"/>`
`<tag name="test" abc="1"/>`

Best regards
