### ISSUE TITLE
slow loading of xmlschema.XMLSchema object

### ISSUE THREAD

**Issue by underchemist** [sissaschool/xmlschema#172]
Hi,

First of all thanks for such a great package! I'm struggling (mostly with my lack of familiarity with xml schemas) to understand if there's a fundamental limitation due to the structure of my schema files or if there's a faster way to instatiate the `xmlschema.XMLSchema` object.

I have essentially a .xsd with many includes referencing many other xsd files. It takes about 1 second to load the `XMLSchema` object which is undesirable for my application. I've attached an example of my schema files if that helps. 

Do you see an easy way to load the schema files faster?
[schemas.zip](https://github.com/sissaschool/xmlschema/files/4246164/schemas.zip)
 
EDIT: Just to note, in the examples `rs2prod_product.xsd` is the "root" schema file from which all the others are referenced

**Comment by brunato** [comment]
Hi, have you already tried the pickle library to dump the schema object to a file and load then faster?
```pycon
>>> import datetime as dt
>>> import pickle
>>> import datetime as dt
>>> import xmlschema
>>> start = dt.datetime.now(); xs = xmlschema.XMLSchema("rs2prod_product.xsd"); dt.datetime.now() - start
datetime.timedelta(microseconds=692759)
>>> with open("schema.pickle", 'wb') as f:
...     pickle.dump(xs, f)
... 
>>> with open("schema.pickle", 'rb') as f:
...     start = dt.datetime.now(); xs1 = pickle.load(f); dt.datetime.now() - start
... 
datetime.timedelta(microseconds=103580)
```

**Comment by underchemist** [comment]
that's an interesting workaround, I will probably use something like this. 

Just so I understand properly, do you have a sense of what is the bottleneck in creating the `xmlschema.XMLSchema` object in this case? is it just file IO? the parsing of all the data types within the schema? the nested structure? 

These schema files should basically be the same forever so I don't need to depend on parsing them from my data on the fly so I should be able to vendor these pickled schema instances within my application. Is there anything stateful in the xmlschema object? such as the filename passed to the object?

**Comment by underchemist** [comment]
Additionally, if I load the `rs2prod_product.xsd` using `lxml.etree.parse` and use the ElementTree as the input to the `xmlschema.XMLSchema` object I get syntax/path error I think due to the presence of the include statements. 

```
XMLSchemaParseError: unknown type 'rs2prod:sourceAttributesDataStore':

Schema (line 56):

  <xsd:element xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rs2prod="http://www.rsi.ca/rs2/prod/xml/schemas" name="sourceAttributes" type="rs2prod:sourceAttributesDataStore">
          <xsd:annotation>
              <xsd:documentation>
    Source (instrument) attributes. Information describing the sensor
    characteristics, raw data and satellite orbit and attitude
  </xsd:documentation>
          </xsd:annotation>
      </xsd:element>

Path: /xsd:schema/xsd:element/xsd:complexType/xsd:sequence/xsd:element
```

**Comment by brunato** [comment]
> Just so I understand properly, do you have a sense of what is the bottleneck in creating the `xmlschema.XMLSchema` object in this case? is it just file IO? the parsing of all the data types within the schema? the nested structure?
> 
In this case is the parsing of data types that requires many data structures to be created to represent the schema infoset:

```python
>>> import xmlschema
>>> xs = xmlschema.XMLSchema("rs2prod_product.xsd")
>>> len([e for e in xs.maps.iter_components()])
1607
```
About half of them are of the meta schema and half are of your schema.

> These schema files should basically be the same forever so I don't need to depend on parsing them from my data on the fly so I should be able to vendor these pickled schema instances within my application. Is there anything stateful in the xmlschema object? such as the filename passed to the object?

The entire state is dumped to file and restored on load.

**Comment by brunato** [comment]
> I don't think it would help with loading times, just curious if having an already parsed ElementTree would be faster?
Not so much, so I had decided to keep it simple using only *xml.etree.ElementTree* for schemas.

**Comment by underchemist** [comment]
> The entire state is dumped to file and restored on load.
Right, but I guess I'm saying would you expect anything to fail if a schema is pickled on one device and loaded on another?

Anyway, feel free to close the issue. You provided a detailed explanation and viable workaround! thanks so much.

**Comment by brunato** [comment]
> Right, but I guess I'm saying would you expect anything to fail if a schema is pickled on one device and loaded on another?

Python's pickle protocols are standardized, so you can reload a pickled object in another device. The only issue is the security of your transport layer from one device to another to assure the integrity of the serialized object.

Cheers
