### ISSUE TITLE
validators method issue

### ISSUE THREAD

**Issue by Thomasb81** [sissaschool/xmlschema#173]
According to
https://github.com/sissaschool/xmlschema/issues/74#issuecomment-408588037

I can retrieve the possible value of an enumerated type. But I found a case where it does not work.

```
>>>import xmlschema
>>>my_schema = xmlschema.XMLSchema('ip-xact/1685-2009/index.xsd',validation='lax')
>>>my_schema.find('//spirit:addressBlock/spirit:usage').type.validators
[XsdEnumerationFacets(['memory', 'register', 'reserved'])]
>>>my_schema.find("//spirit:addressBlock/spirit:access").type.validators
()
```
The last command return an empty tuple. While I would have expected this kind of object:
`[XsdEnumerationFacets(['read-only','write-only','read-write','writeOnce','read-writeOnce'])] `

I understand that the working and not working example have different complexity description in the schema.

Test done on v1.0.14 since the compatibility with this schema seems broken after  (reference to https://github.com/sissaschool/xmlschema/issues/170)

Thomas

**Comment by Thomasb81** [comment]
I can get the expected result with:
`my_schema.find("//spirit:addressBlock/spirit:access").type.base_type.validators`

**Comment by Thomasb81** [comment]
Is there method I can use to validate text of a specific element ?

like
>>>my_schema.find("//spirit:addressBlock/spirit:access").check("read-0nly")

That could be use to validate an user text entry prior element node is append at the right place in an xml document. 

Thanks

**Comment by brunato** [comment]
If the element has a simple type you can try:

```pycon
>>>my_schema.find("//spirit:addressBlock/spirit:access").type.validate("read-0nly")
```
For XSD elements the validate API accepts only an Element instance.

**Comment by Thomasb81** [comment]
Tanks
