### ISSUE TITLE
Getting XMLSchemaDecodeError when validating ISO 8601 date time string

### ISSUE THREAD

**Issue by belgrade-dev** [sissaschool/xmlschema#174]
(v. 1.1.1)

I am gettting the following error when trying to validate a document that contain dates in (supposedly) valid ISO 8601 format:
```
XMLSchemaDecodeError(reason="Invalid datetime string '2020-03-09 00:00:00.000' for <class 'elementpath.datatypes.Date10'>")
```
Obviously, the date '2020-03-09 00:00:00.000' is for some reason not considered to be valid. My guess is that xmlschema code expects 'T' as a separator between the date and the time part, but I'm not sure if this is a correct expectation. I'm saying this because the isoparse() method from the standard dateutil package considers the same datetime string as a valid ISO 8601 string:
```python
dateutil.parser.isoparse('2020-03-09 00:00:00.000') 
datetime.datetime(2020, 3, 9, 0, 0)
```
Is there some settting or workaround that I can use, to avoid having to force the current datetime strings to comply with xmlschema's expectations?

Thanks in advance.

**Comment by brunato** [comment]
Hi,

the xs:dateTime format is inspired by ISO 8601, but is not the same. The 'T' separator is required so  '2020-03-09 00:00:00.000' is not valid.

For details:  https://www.w3.org/TR/xmlschema-2/#dateTime

There is no workaround for let the library accepting wrong datetime formats. The only option is to set validation='lax' and process the documents, filtering out these datetime errors, and then check if there are other errors not related with this case.

**Comment by belgrade-dev** [comment]
Hi Davide,

 

First of all – thanks for finding the time to reply, in these difficult times. And good luck.

 

Even the format with ‘T’, e.g. ‘2020-03-05T23:04:10.047' gives the same error message.

 

What would be an example of a correct format that contains both date and time part?

 

Thanks in advance!

 

Regards,

Vladimir

**Comment by brunato** [comment]
Hi Vladimir,

Thank you for your words. Fortunately I can work from my home and stay pretty safe for the moment.

About your reply the format '2020-03-05T23:04:10.047' is correct for xs:dateTime, but I noticed now that your initial error:
```
XMLSchemaDecodeError(reason="Invalid datetime string '2020-03-09 00:00:00.000' for <class 'elementpath.datatypes.Date10'>")
```
is regarding an xs:date data type so time part cannot appear at all.

Cheers
Davide

**Comment by belgrade-dev** [comment]
Hi,

 

That was indeed the issue. Thanks once again for your help!

 

Regards,

Vladimir
