### ISSUE TITLE
xmlschema with multiple namespace import 

### ISSUE THREAD

**Issue by bengadisoufiane** [sissaschool/xmlschema#175]
I have an XSD file defined with multiple XSD file import namespace, and i want to validate some xml fine then convert it to json.

but I have remarque that the xmlschema.xmlschema() doesn't import all the XSD file correctly.

I can share with my xsd folder if you need

**Comment by brunato** [comment]
Hi,
this library supports multiple XSD namespace imports, so it's maybe a bug for your case. Share a link if your schemas are taken from public available schemas, otherwise load them in an archive file (eg. .zip).

**Comment by bengadisoufiane** [comment]
hello,
Here you find the google drive foulder of XSD:
[https://drive.google.com/open?id=1bkacChg3XIrUy7o_FPvIHeB7WFVs_1JG](url)

**Comment by brunato** [comment]
Hi,
the previous link is not of a public access location. Please attach a .zip file with XSD files instead.

**Comment by bengadisoufiane** [comment]
Here you go.
[Uploading Transaction.zip…](XSD)

**Comment by bengadisoufiane** [comment]
Here you find the XSD zip file:
[Transaction.zip](https://github.com/sissaschool/xmlschema/files/4334054/Transaction.zip)

**Comment by brunato** [comment]
Hi,
I tried your archive, that contains 29 xsd files, and all the schemas seem to be loaded:

```pycon
>>> import xmlschema
>>> import os.path
>>> xs = xmlschema.XMLSchema("TransactionEngineService.xsd")
>>> for v in xs.maps.namespaces.values():
...    for schema in v:
...        if "TransactionEngineService" in schema.url:
...            print(os.path.basename(schema.url))
... 
TransactionEngineService.xsd
TransactionEngineService_transaction_enumtransaction.xsd
TransactionEngineService_transaction_enums.xsd
TransactionEngineService_giftvoucher_enums.xsd
TransactionEngineService_network_enums.xsd
TransactionEngineService_crm_enumcustomer.xsd
TransactionEngineService_common_enumcodification.xsd
TransactionEngineService_common_enumpersonsextype.xsd
TransactionEngineService_crm_enumloyaltyprogram.xsd
TransactionEngineService_customercare_enumcustomercare.xsd
TransactionEngineService_product_enums.xsd
TransactionEngineService_sales_enumpos.xsd
TransactionEngineService_sales_enumdevice.xsd
TransactionEngineService_common_documents_enumdocument.xsd
TransactionEngineService_crm_enumloyaltyoperation.xsd
TransactionEngineService_crm_marketingaction_enums.xsd
TransactionEngineService_crm_enumcustomerprofile.xsd
TransactionEngineService_transaction_enumpaidinoutreason.xsd
TransactionEngineService_transaction_enumtender.xsd
TransactionEngineService_sales_enumeft.xsd
TransactionEngineService_transaction_enumdiscountreason.xsd
TransactionEngineService_couponing_enumcoupon.xsd
TransactionEngineService_inventory_enums.xsd
TransactionEngineService_guidedsale_enums.xsd
TransactionEngineService_transaction_enumcustomermvt.xsd
TransactionEngineService_transaction_enumpossession.xsd
TransactionEngineService_tracking_enums.xsd
TransactionEngineService_purchaseorder_enums.xsd
TransactionEngineService_common_enumperiod.xsd
```

**Comment by bengadisoufiane** [comment]
Hello, 

yes, I don't know why when i try to validate an XMLs files against this schema i get some error.
Can you please, check if i made a mistake ?
here is some XMLs files.
[Uploading xmls simples.zip…](xmls simples)

**Comment by brunato** [comment]
These XML files missing of namespace declarations. For example the file 4.xml is valid inserting the namespace declaration in the root tag, eg.:

```xml
<<?xml version="1.0" encoding="UTF-8"?>
<tlt:transactionListType xmlns:tlt="http://com/cylande/unitedretail/transaction/service/common/TransactionEngineService/">
...
...
</tlt:transactionListType>
```

Without namespace declarations the loaded ElementTree data lacks on mapping elements to the right namespaces. For other files the problem maybe similar but probably they lack also other namespace declarations because fixing the root element is not enough.
