### ISSUE TITLE
xs:alternative issue: local variable 'constraint' referenced before assignment

### ISSUE THREAD

**Issue by cniethammer** [sissaschool/xmlschema#18]
I am using python 3.6.2 and xmlschema 0.9.12

Creating an new validator for a XSD 1.1 Schema file incluing xs:alternative elements with
`xmlschema.XMLSchema('test.xsd')`

I get the following error message
.local/lib/python3.6/site-packages/xmlschema/components/elements.py in _parse(self)
...
--> 173             if constraint.name in self.maps.constraints:
...
UnboundLocalError: local variable 'constraint' referenced before assignment

Here the content of test.xsd:
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="root" type="rootType"/>
<xs:element name="node" type="nodeType">
  <xs:alternative test="@mode='A'" type="nodeA"/>  
  <xs:alternative test="@mode='B'" type="nodeB"/>
</xs:element>

<xs:complexType name="rootType">
  <xs:sequence>
    <xs:element ref="node" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="nodeType">
  <xs:attribute name="mode" type="allowed-node-types"/>
</xs:complexType>

<xs:simpleType name="allowed-node-types">
  <xs:restriction base="xs:string">
    <xs:enumeration value="A"/>
    <xs:enumeration value="B"/>
  </xs:restriction>
</xs:simpleType>      

<xs:complexType name="nodeA">
  <xs:complexContent>
    <xs:extension base="nodeType">
          <xs:attribute name="value" type="xs:string" use="required"/>
          <xs:anyAttribute />
    </xs:extension>  
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="nodeB">
  <xs:complexContent>
    <xs:extension base="nodeType">
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:anyAttribute processContents="skip"/>
    </xs:extension>  
  </xs:complexContent>
</xs:complexType>  

</xs:schema>

**Comment by brunato** [comment]
The current XMLSchema class doesn't cover XSD 1.1, only version 1.0. XSD 1.1 is in the roadmap. 

I fixed the unexpected exception with a more clear message that describe <xs:alternative> as a unexpected element declaration.

**Comment by brunato** [comment]
XSD 1.1 is now supported by release v1.0.14
