### ISSUE TITLE
Anchored regular expressions

### ISSUE THREAD

**Issue by ErikRtvl** [sissaschool/xmlschema#180]
When validating a xs:pattern element that includes anchors in the schema, the validation runs into an exception. Using a monkey-patch of the `get_python_regex` function that strips `^` and `$` from the start and end before calling the actual function solves the issue (for me).

I know that in xml-schema's, the starting and ending position anchors are implicitly added, but users tend to add them anyway meaning it gets added twice in the actual expression to be evaluated by python, converting the anchorrs to literal `^`  and `$`.

My monkey-patch:

```
  old_f = copy.copy(xmlschema.regex.get_python_regex)
  def get_python_regex_wrapper(xml_regex, xsd_version: str = '10'):
    return old_f(xml_regex.lstrip('^').rstrip('$'), xsd_version=xsd_version)
  xmlschema.validators.facets.get_python_regex = get_python_regex_wrapper
```

Maybe an idea to add this? Although I assume there are already reasons not to.

**Comment by brunato** [comment]
Hi,

the schema has to be accepted also with an additional `^` and/or `$` (so I've to fix the exception that you notify me in the next release ...) but the regex matching cannot be changed (the additional characters cannot be stripped ...), because it would not be compliant with the XSD standard.
Thank you

**Comment by ErikRtvl** [comment]
Sorry for not replying earlier. Remaining compliant with XSD standard (thus implicitly anchoring regular expressions from schemas) sounds logical.

I'll check the next release. Thanks for developing this useful module!
