### ISSUE TITLE
xmlschema usage request

### ISSUE THREAD

**Issue by NicoPy** [sissaschool/xmlschema#184]
Hi,

I'm in the process of creating a GUI application to visualize and edit xml files for a specific application.
Thanks to xmlschema validating xml files works.
Extracting the xml data using to_dict() works also. The dict allows me to display the xml data in my application. Great.
Now, I'd like to edit the xml data using information extracted from the xml schema.
For this I need an enhanced dict where values contain not only the text but also the xml node and the associated schema information. 
I also need a way to get information from the schema to know which edition is possible. For example, an enumerated type has a predefined set of possible values.
Is this possible ?

**Comment by brunato** [comment]
Hi,
extracting information from schema components is already possible. Schema instances have *types*, *elements* and other global components directly connected to the instance.
You can access non-global components through hierachy or with XPath (find/findall as the ElementTree API).

Enhanced dictionaries are not currently implemented in decoders. This can be a nice feature but it needs an analysis of implications in terms of feasibility and performance impact.

**Comment by NicoPy** [comment]
Hi,
I've made progress with xmlschema use.
I'm able to validate and extract the content of xml file using an xml schema.
One problem I have is the following : I want the user to be able to edit the xml content using my application. To construct the user interface of my application, I need to know if a xml element is a boolean, an int, an enumeration...  This is because, enumeration elements will be presented as a choice lists, string elements as text edit controls... 
What is the best way to achieve this ?

**Comment by brunato** [comment]
Currently the best choice is to use XPath to retrieve the paired XSD component. In decoded data maybe you can use JSONPath (but I've never used this yet) traslating also the paths.

**Comment by NicoPy** [comment]
I already have the pairing between the XML node and the associated XSD component.
My problem is with the XSD components themselves.
The schema I use is [this one](https://arm-software.github.io/CMSIS_5/SVD/html/schema_1_2_gr.html).
How can I detect that, for example, *"cpuNameType"* is an enumeration or *"mpuPresent"* is a boolean ?

**Comment by brunato** [comment]
With the current version to check if a type is derived from a specific builtin type you can do:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema("schema_1_2_gr.xsd")
>>> boolean_type = schema.builtin_types()['boolean']
>>> schema.find('//mpuPresent').type.is_derived(boolean_type)
True
```

For enumeration you can check the type's facets:

```pycon
>>> schema.types['cpuNameType'].facets
{'{http://www.w3.org/2001/XMLSchema}enumeration': XsdEnumerationFacets("['CM0', 'CM0PLUS', 'CM0+', 'CM1', 'SC000', ...]")}
```

or validators (the facets that are applied on decoded data):

```pycon
>>> schema.types['cpuNameType'].validators
[XsdEnumerationFacets("['CM0', 'CM0PLUS', 'CM0+', 'CM1', 'SC000', ...]")]
>>> schema.types['cpuNameType'].validators[0].enumeration
['CM0', 'CM0PLUS', 'CM0+', 'CM1', 'SC000', 'CM23', 'CM3', 'CM33', 'CM35P', 'SC300', 'CM4', 'CM7', 'ARMV8MML', 'ARMV8MBL', 'ARMV81MML', 'CA5', 'CA7', 'CA8', 'CA9', 'CA15', 'CA17', 'CA53', 'CA57', 'CA72', 'other']
```
In version v1.2 a property will added to access this list of values. Also the documentation will be extended with a section that explains how to access the principal XSD components (types, elements and attributes).

**Comment by NicoPy** [comment]
That's very interesting.
Thanks for your support.

**Comment by brunato** [comment]
I leave this opened until the publishing of v1.2.0.
Cheers

**Comment by NicoPy** [comment]
Any schedule for V1.2.0 ?

**Comment by brunato** [comment]
Not yet, maybe for the end of May, but I've other things to complete.

**Comment by NicoPy** [comment]
No problem. Just for my knowledge.
Thanks.

**Comment by brunato** [comment]
In release v1.2.0 simple types have an enumeration property that can return a list containing the enumeration values (`None` if there is no enumeration facets associated to type).
Cheers

**Comment by NicoPy** [comment]
@brunato Thanks a lot Davide 👍
