### ISSUE TITLE
Configuration to only allow local file access

### ISSUE THREAD

**Issue by danifus** [sissaschool/xmlschema#185]
Hi,

For security, I would like to ensure that I only attempt to access schemas from my local filesystem ie. no connecting to external documents. How would I go about doing that?

Thanks,
Dan

**Comment by brunato** [comment]
Hi,
currently it's not possible to block, but default remote XML resources, so also schemas, are parsed with a *SafeXMLParser* to defuse XML attacks. In this scenario can still a remote blocking option useful in your opinion?

Thanks,
Davide

**Comment by danifus** [comment]
That does go a long way but I think restricting it can still be useful. Mitigation can be effective but avoiding the risk in the first place is always more robust.

There are a few issues that can come about from requesting a legitimate external schema that may still not be wanted. The resources may be large schemas (maliciously or not) or experiencing latency issues which could affect the performance of the  system. The servers hosting the external resources can also be used to log requests and that may result in leaking information about the schemas being handled by a service.

A less important use case is to check that I'm not accidentally including schemas which have external dependencies. If it errors out immediately, I know to fix them straight away.

**Comment by brunato** [comment]
If I interpret in the right way your idea it's maybe like a _sandbox mode_ on building the schema ... accepting only file's scheme urls or local filesystem paths. Or in an more safe way only paths in the same directory or in a subdirectory. Or both, regulated by a new argument of the XMLSchema class.

The new argument is not related to XML resource as the _defuse_ argument, but it'is managed directly by import/include methods of the schema class. When activated any blocked loading is warned by a log message.

This could satisfy the protections needs that you explained?

**Comment by danifus** [comment]
Yes I think that sounds good. Loading from the same directory or sub directories sounds like a good way to avoid directory traversal attacks. Good idea!

Would that also restrict attempting to collect remote resources when using a schema to parse a local xml document? Does xmlschema ever attempt to fetch external resources when parsing a document? It's been a while since I looked at the xmlschema internals!

**Comment by brunato** [comment]
I think it would restricts also the loading of wildcard related elements. I don't remember the details about that now but It should be related to a namespace import, so it can be managed in the same way.

**Comment by danifus** [comment]
Sounds perfect! That will help me sleep at night :p

**Comment by brunato** [comment]
The schema's init argument for handling the new feature will be called _allow_, described as security mode for accessing resource locations.
Possible values:

- 'all': all types of URLs are allowed (default)
- 'remote': only remote resource URLs are allowed
- 'local': only file paths and URLs are allowed
- 'sandbox': only file paths and URLs that are under the directory path identified by source or by the *base_url* argument are allowed.

The new argument will be passed and handled by the `XMLResource` instance of the schema, similarly to what already happens with *defuse* argument.

**Comment by danifus** [comment]
That sounds great! Thanks heaps for your work with this and the rest of the project! :D

**Comment by brunato** [comment]
Hi @danifus,
the enhancement is available with release v1.2.0.

**Comment by danifus** [comment]
This is great! Thanks for your help.

I've created #191 to make it a little easier to use "sandbox" mode correctly. Happy to make alterations to it if you need.

Thanks again!
