### ISSUE TITLE
Accessing <xs:complexType><xs:sequence><xs:element> blocks in a loaded XML Schema?

### ISSUE THREAD

**Issue by nickpelling** [sissaschool/xmlschema#186]
I'm trying to use xmlschema as a tool to help convert XML schemas into C-like code structures (i.e. XML Data Binding). With the help of the xmlschema manual, I can now access most XML Schema structures OK:

```
import xmlschema
xs = xmlschema.XMLSchema("test.xsd")

for key in xs.types:
    print(key)
    ty = xs.types[key]
    
    # If simple type
    if ty.is_simple():
        print("  is derived from", ty.base_type.name)
        facets = ty.facets
        for facet in facets:
            print(" -> ", facet)
            
    # If complex type
    if ty.is_complex():
        print("  [struct]")
        attrs = ty.attributes
        for attr in attrs:
            att2 = attrs[attr]
            print(" ->", attr, att2.type.name)
        
            
    # If enumeration type
    if ty.is_atomic() and not ty.is_emptiable():
        print("  [enum]")
        facets = ty.facets
        for facet in facets:
            enums = ty.facets[facet];
            for enum in enums:
                print(" ->", enum.attrib['value'])
```
However, I can't see how to reach xs:sequence blocks in this way, i.e. blocks that look like:

```
  <xs:complexType name="tFoo">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="16" name="BarArray" type="tBar"/>
      <xs:element minOccurs="0" maxOccurs="8" name="ZodArray" type="tZod"/>
    </xs:sequence>
  </xs:complexType>
```

Is there a way of accessing these blocks?

Incidentally, I couldn't find any examples on the Web of people using xmlschema for XML Data Binding, even though it seems like the very first tool I would choose. :-)

**Comment by brunato** [comment]
Hi,
a complexType has also a *content_type* attribute:

```
import xmlschema
xs = xmlschema.XMLSchema("test.xsd")
tfoo = xs.types['tFoo']
tfoo.content_type
```
for a complex content this is a sequence group, in this case a sequence of 2 elements.
I hope this can be enough for the moment.

Soon I will publish a new release of the package with additional APIs for XSD types and other components and maybe a code generator based on Jinja templates (initially for Fortran code but I wish it will be easily extendable also for other programming languages).

Cheers

**Comment by brunato** [comment]
> Soon I will publish a new release of the package with additional APIs for XSD types and other components and maybe a code generator based on Jinja templates (initially for Fortran code but I wish it will be easily extendable also for other programming languages).

In the documentation of the new release I will add a section to explain how to use XSD components internals. 

The code generator based on Jinja templates will be strictly related to a research project that needs to generate Fortran code, but there will be almost empty frames for extending templates and filters for other programming languages, for future developments (hoping also for other contributions). I count to publish that in a pair of weeks.

**Comment by nickpelling** [comment]
Thanks, Davide, that's perfect! Hopefully that's the last major piece of the programming puzzle here. :-)

The only other query I have for you is a general one about using xmlschema for XML Data Binding. Does xmlschema expose any XML mechanism for specifying that structures should exist but not persist? For example, a live 'state' variable defined by the XML Schema that exists during runtime but which should not appear in an XML file. Thanks very much for your help!

**Comment by brunato** [comment]
xmlschema only rely on XSD specification not on additional specs for doing XML Data Bindings. My idea is of making xmlschema's components API usable for code generation. This will be in a new package soon, but only with the intention to show a manner of doing this (the new package will be related to a suite of codes written in Fortran ...).

If you need XML Data Binding now, if you haven't already done, take a look to [xsData](https://github.com/tefra/xsdata/) a recently published package.

**Comment by nickpelling** [comment]
Yes, xsData is a very cool new library that I was indeed unaware of, thanks very much for the link! :-)

**Comment by brunato** [comment]
The scientific project that I collaborate with has published a [tool for code generation for XSD](https://github.com/QEF/xsdtools) schemas based on _xmlschema_ and _jinja2_ , but as I announced it's a concept tool and it's currently limited to generic Fortran code for a specific scientific suite.

The basic idea of the tool is to provide classes for different languages using a set of basic _jinja_ filters/tests for building schema (xmlschema's PSVI) based templates.
