### ISSUE TITLE
How to save successfull fetched schema

### ISSUE THREAD

**Issue by JonasKiefer** [sissaschool/xmlschema#187]
Hello,

in my case fetching of remote schema takes very long time. Is there a way to save the successful fetched schema as a string or file object?

kind regards

**Comment by brunato** [comment]
Hi,
use the _pickle_ library, eg. for serialization into a string object:

```pycon
>>> import xmlschema
>>> import pickle
>>> schema = xmlschema.XMLSchema("tests/test_cases/examples/vehicles/vehicles.xsd")
>>> serialized_schema = pickle.dumps(schema)
>>> type(serialized_schema)
<class 'bytes'>
>>> schema1 = pickle.loads(serialized_schema)
>>> schema1.is_valid("tests/test_cases/examples/vehicles/vehicles.xml")
True
>>> schema1.is_valid("tests/test_cases/examples/vehicles/vehicles-2_errors.xml")
False
```
use _pickle.dump_ and _pickle.load_ for file serialization.

**Comment by JonasKiefer** [comment]
thx, that works to save the object as a file. But what if i need to convert the full xmlschema with all includes to a single string so i can use it with [pyxbgen](http://pyxb.sourceforge.net/userref_pyxbgen.html) for example.

**Comment by brunato** [comment]
Schema editing is not a feature of this library. For my experience composed schemas use often multiple namespaces, so supporting this for generic schemas can require reference rewriting, namespace prefix conflicts resolution. Too complex for me.

Maybe better to think about an export procedure that checks and optionally remaps schema location hints (if they are absolute url), saving schema XSD files to a local path.

**Comment by brunato** [comment]
Added an *export()* method to schema class, that save loaded schemas to a target directory.
All the schemas imported/included starting from the main schema instance are saved. For default absolute imports/includes are not saved, provide `only_relative=False` for saving all.

An example of usage:

```pycon
>>> import xmlschema
>>> import tempfile
>>> import os
>>> 
>>> vh_schema = xmlschema.XMLSchema('tests/test_cases/examples/vehicles/vehicles.xsd')
>>> with tempfile.TemporaryDirectory() as dirname:
...     vh_schema.export(target=dirname)
...     os.system("ls -l {}/*".format(dirname))
... 
-rw-r--r--. 1 brunato staff 471 Sep 26 10:54 /tmp/tmpev3z95zk/bikes.xsd
-rw-r--r--. 1 brunato staff 469 Sep 26 10:54 /tmp/tmpev3z95zk/cars.xsd
-rw-r--r--. 1 brunato staff 361 Sep 26 10:54 /tmp/tmpev3z95zk/types.xsd
-rw-r--r--. 1 brunato staff 543 Sep 26 10:54 /tmp/tmpev3z95zk/vehicles.xsd
0
>>> 
```

It works also with schemas loaded from remote URLs, that can be loaded, built and than saved to a local path.
The export remaps absolute locations when needed. Available with release v1.2.5.

**Comment by wbkdef** [comment]
I'm trying to save a schema for later use (it takes a long time to download all the ".xsd" files from scratch).

I tried `schema.export(target='./cached_schemas', save_remote=True)` but get the following error:
```
Traceback (most recent call last):
  File "C:\Users\wbruc\.virtualenvs\scratch_python-lMg12cM6\Lib\site-packages\xmlschema\validators\schemas.py", line 1528, in export
    fp.write(text)
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>
```

I also tried to pickle the Schema `with open(f"{fn_pickle}", "wb") as f: pickle.dump(schema, f)` , but get this error:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<string>", line 3, in <module>
TypeError: cannot pickle '_io.TextIOWrapper' object
```

How to be able to save and reload a schema, so it doesn't have to fetch files from the web each time?  Thanks.

**Comment by brunato** [comment]
Hi,
it's related to encoding of the origin XSD source. Could you give me the source URL of this schema?

P.S.: Please, next time open a new issue, this is related to a new feature, not for following problems with the same feature.

Thank you

**Comment by wbkdef** [comment]
Hi,

Absolutely, I'll open a new issue next time.

Here's the source URL:
https://mip-interop.org/data/v4.3/BattlespaceConcept.xsd

Thank you
