### ISSUE TITLE
OSX pip install crashes the app

### ISSUE THREAD

**Issue by Ashot-ton** [sissaschool/xmlschema#188]
When pip3 install xmlschema on osx i get the following error: zsh: abort      pip install xmlschema or zsh: abort      pip3 install xmlschema depending on which version of pip I run

**Comment by brunato** [comment]
Hi,
please could you tell me with which pip versions the installation works and with which pip versions it doesn't work?

**Comment by Ashot-ton** [comment]
Neither of the pips manage to install it, and i get the same error as mentioned in the post, i am running the latest version of osx:10.15

**Comment by brunato** [comment]
Ok, my tests run successful on Travis CI with Python 3.7.4 on macOS 10.14.4. I will try to add also tests for macOS 10.5 to reproduce the issue.

**Comment by brunato** [comment]
Added a test for macOS 10.15.4 on Travis CI. The first job of this test has ran successfully. If your problem persists try to look at [job details](https://travis-ci.org/github/sissaschool/xmlschema/jobs/690311726) to see if there are differences with your environment.

**Comment by Ashot-ton** [comment]
The issue has been solved, thank you very much for the effort!
