### ISSUE TITLE
Single element in <xs:choice maxOccurs="unbounded"> don't wrapped to list

### ISSUE THREAD

**Issue by Johnsik** [sissaschool/xmlschema#190]
xmlschema don't wrapper to list single element inside <xs:choice maxOccurs="unbounded"> if xs:choice isn't single element in <xs:sequence>

I'm included example where inside "type_a" tag "c" processed as list but in "type_b" are not.

[test_xmlschema.zip](https://github.com/sissaschool/xmlschema/files/4663014/test_xmlschema.zip)

**Comment by brunato** [comment]
The decision on putting the decoded value into a list is taken only on matched element basis. I will examine if this decision can be taken also looking the container group.

**Comment by brunato** [comment]
Hi,
adjusted _is_single()_ methods for particles. For model groups _is_single()_ result is determined by group and child groups (not considering child elements). For elements _is_single()_ result depends on _max_occurs_, _max_occurs_ of parent group, model (choice) or lenght (1) of the parent group.

With modifications your test the result will change from:
``` {'a': {'c': [{'$': '1'}]}, 'b': {'c': {'$': '1'}, 'e': [{'$': '1'}]}}```
to:
```{'a': {'c': [{'$': '1'}]}, 'b': {'c': [{'$': '1'}], 'e': [{'$': '1'}]}}```

**Comment by Johnsik** [comment]
Thank you very much!

**Comment by brunato** [comment]
Fix available with release v1.2.0.

Cheers
