### ISSUE TITLE
XsdComplexType is_element_only has changed

### ISSUE THREAD

**Issue by bdauvergne** [sissaschool/xmlschema#195]
I don't know if our use of is_element_only() but we used it to exclude ComplexType with SimpleType content; but the new test for it broke our code.

Here the type :

        <xsd:complexType name="PDFType">
                <xsd:attribute ref="FILE"/>
        </xsd:complexType>

for me it's an element only type (even if the content_type is empty).

**Comment by bdauvergne** [comment]
Link to the using code http://git.entrouvert.org/passerelle.git/tree/passerelle/utils/xml.py#n317

**Comment by brunato** [comment]
Hi,
referring to the [XSD standard](https://www.w3.org/TR/xmlschema11-1/#Complex_Type_Definition_details) a complexType can have four different varieties of content type: 

- **empty**: deny child elements, allow text content
- **simple**: deny child elements, allow text content
- **element-only**: allow child elements, deny intermingled text content
- **mixed**: allow child elements and intermingled text content

So your case the content type is considered _'empty'_ (the same if you use an empty simple type as base). I worked to conform package API to the standard, fixing errors on content type classification.

The reference methods for checking the content type are _is_empty()_, _has_simple_content()_, _is_element_only()_ and _has_mixed_content()_. For your scope you can use `not has_simple_content()`.

Note: checking this I discovered a issue on _has_simple_content()_ for a simpleType that has to return `True` only if the type is not empty.

**Comment by bdauvergne** [comment]
Thanks for the advice, I adapted the code.
