### ISSUE TITLE
Lost `add_position` in recursive call at `etree_iterpath`

### ISSUE THREAD

**Issue by mishatrinex** [sissaschool/xmlschema#196]
Hi!
https://github.com/sissaschool/xmlschema/blob/e7c0c43d41be6617bbeed2698154f8a8a0f2d396/xmlschema/etree.py#L237
I can assume it should be like that:
```python
        yield from etree_iterpath(child, tag, child_path, namespaces, add_position)
```
to correctly build xpath with position for all children elements.

**Comment by brunato** [comment]
Yes, I'll fix that.
Thank you
