### ISSUE TITLE
JSON to XML schema (ONVIF)

### ISSUE THREAD

**Issue by mrkieumy** [sissaschool/xmlschema#199]
Hi @brunato , thank you for your great work. In my work, I need to convert the object detection result (JSON) to the ONVIF format (XML schema) for readable on the camera on board of railway.
I have a JSON file like this:
```json
[
{
 "frame_id":1151, 
 "objects": [ 
  {"class_id":0, "name":"person", "relative_coordinates":{"center_x":0.783664, "center_y":0.478734, "width":0.031240, "height":0.091902}, "confidence":0.833649}, 
  {"class_id":0, "name":"person", "relative_coordinates":{"center_x":0.769856, "center_y":0.477192, "width":0.028218, "height":0.088091}, "confidence":0.753653}
 ] 
}, 
{
 "frame_id":1152, 
 "objects": [ 
  {"class_id":0, "name":"person", "relative_coordinates":{"center_x":0.785543, "center_y":0.478569, "width":0.032181, "height":0.094132}, "confidence":0.850375}
 ] 
}, 
...
]
```
and I want to convert it to XML schema format of ONVIF like this:
https://doc.developer.milestonesys.com/html/gettingstarted/intro_metadata.html

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tt:MetadataStream xmlns:tt="http://www.onvif.org/ver10/schema">
  <tt:VideoAnalytics>
    <tt:Frame UtcTime="2013-10-08T08:40:42.042+02:00">
      <tt:Object ObjectId="1">
        <tt:Appearance>
          <tt:Transformation>
            <tt:Translate x="-1.0" y="-1.0"/>
            <tt:Scale x="0.003125" y="0.00416667"/>
          </tt:Transformation>
          <tt:Shape>
            <tt:BoundingBox left="20.0" top="30.0" right="100.0" bottom="80.0"/>
            <tt:CenterOfGravity x="60.0" y="50.0"/>
          </tt:Shape>
          <tt:Class>
              <tt:ClassCandidate>
              <tt:Type>Animal</tt:Type>
              <tt:Likelihood>0.9</tt:Likelihood>
            </tt:ClassCandidate>
          </tt:Class>
        </tt:Appearance>
        <tt:Behaviour>
          <tt:Idle/>
        </tt:Behaviour>
      </tt:Object>
    </tt:Frame>
  </tt:VideoAnalytics>
  <tt:Extension>
    <OriginalData>U29tZU9yaWdpbmFsRGF0YSBlbmNvZGVkIGluIEJBU0U2NA==</OriginalData>
  </tt:Extension>
</tt:MetadataStream>
```

Could you please give a detail instruction or any function to solve this task.
Thank you very much.
I appreciate any help.

**Comment by brunato** [comment]
Hi,
I found ONVIF's XSD schemas at address https://www.onvif.org/profiles/specifications/.

The schema for your XML data is _metadatastream.xsd_. It needs XSD 1.1 validator to build and requires some imported and included schemas:

```pycon
>>> xs = xmlschema.XMLSchema11('https://www.onvif.org/ver10/schema/metadatastream.xsd', loglevel=20)
[INFO] Include schema from 'common.xsd'
[INFO] Namespace 'http://www.w3.org/2005/08/addressing' imported from 'http://www.w3.org/2005/08/addressing/ws-addr.xsd'
[INFO] Namespace 'http://docs.oasis-open.org/wsrf/bf-2' imported from 'http://docs.oasis-open.org/wsrf/bf-2.xsd'
[INFO] Namespace 'http://docs.oasis-open.org/wsn/t-1' imported from 'http://docs.oasis-open.org/wsn/t-1.xsd'
[INFO] Namespace 'http://docs.oasis-open.org/wsn/b-2' imported from 'http://docs.oasis-open.org/wsn/b-2.xsd'
[INFO] Namespace 'http://www.onvif.org/ver20/analytics/humanface' imported from '../../ver20/analytics/humanface.xsd'
[INFO] Namespace 'http://www.onvif.org/ver20/analytics/humanbody' imported from '../../ver20/analytics/humanbody.xsd'
```
The JSON data is not tightly related to XSD schemas so cannot converted using the xmlschema library. I suggest to create a script to build an XML MetadataStream file (or in memory building a tree) from JSON data and then validate the produced XML with _metadatastream.xsd_ schema.

**Comment by mrkieumy** [comment]
Hi @brunato  , thank you so much for your suggestion,
For the JSON file, I can handle it, the big problem is that I don't know where to start to write a script to build an XML MetadataStream file. I search for it but I didn't find any information. Could you please give more detail about how to write a very simple XML MetadataStream file.
I really appreciate your help.
Best regards.

**Comment by brunato** [comment]
You can take a look at ElementTree in Python's standard library, that is also the library that I've used to load schemas and XML data. There are many tutorial on how to create XML using ElementTree (eg. https://pymotw.com/2/xml/etree/ElementTree/create.html).

For writing XML data the preferred choice maybe the [lxml library](https://lxml.de/), that uses the same ElementTree interface plus [additional API](https://lxml.de/tutorial.html) for make elements (useful especially when you have to manage more namespaces in XML tree).

**Comment by mrkieumy** [comment]
Thank you so much, I'll take a look at lxml library.
Best regards.

**Comment by mrkieumy** [comment]
HI @brunato , sorry to bother you again, I used lxml and created an XML Metadate file, it looks exactly the same with the template. The only thing is the dateTime, it has space between character.
My dateTime: <tt:Frame UtcTime="2 0 2 0 - 0 6 - 2 7 T 2 3 : 0 6 : 3 3 . 6 3 2 4 3 4 + 0 2 : 0 0">
While the Template: <tt:Frame UtcTime="2013-10-08T08:40:42.042+02:00">
That the reason when I validated my file by:
 xs = xmlschema.XMLSchema11('https://www.onvif.org/ver10/schema/metadatastream.xsd', loglevel=20)
    xs.validate(ONVIFfile)
It raise an error: 
xmlschema.validators.exceptions.XMLSchemaDecodeError: failed validating '2 0 2 0 - 0 6 - 2 7 T 2 0 : 4 6 : 3 7 . 8 9 3 0 2 3 + 0 0 : 0 0' with XsdAtomicBuiltin(name='xs:dateTime'):
Reason: Invalid datetime string '2 0 2 0 - 0 6 - 2 7 T 2 0 : 4 6 : 3 7 . 8 9 3 0 2 3 + 0 0 : 0 0' for <class 'elementpath.datatypes.DateTime'>

I used many commands like: datetime.utcnow(), datetime.now(), or adding .isoformat(),...
It doesn't work. 
Do you know how to delete the space between datetime on XML to output the correct UtcTime. I'm ready to give you my source code file if you need it.
Thank you so much in advance.
Best regards.
