### ISSUE TITLE
Encode objects to lxml etree.

### ISSUE THREAD

**Issue by proofit404** [sissaschool/xmlschema#201]
Thanks for the awesome library!

I tried to do following:
* create xml schema from `user.xsd`
* generate element tree by encoding a dictionary with user data
* I want to apply XSLT to the element tree I got
* I've got error because lxml XSLT transformation expects element tree of lxml (not from the standard xml module)

At the moment I workaround this problem by serialization xml to string and parsing it back before XSLT transformation applied.

Is is any possibility to generate lxml element tree from the beginning?

Best regards,
Artem.

**Comment by brunato** [comment]
Hi,
try to provide _etree_element_class_ option to encode. For example, using one of the package sample schemas:

```pycon
>>> import lxml.etree as et
>>> import xmlschema
>>> vh_schema = xmlschema.XMLSchema('vehicles.xsd')
>>> vh_data = vh_schema.decode('vehicles.xml')
>>> vh_data
{'@xmlns:vh': 'http://example.com/vehicles', '@xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance', '@xsi:schemaLocation': 'http://example.com/vehicles vehicles.xsd', 'vh:cars': {'vh:car': [{'@make': 'Porsche', '@model': '911'}, {'@make': 'Porsche', '@model': '911'}]}, 'vh:bikes': {'vh:bike': [{'@make': 'Harley-Davidson', '@model': 'WL'}, {'@make': 'Yamaha', '@model': 'XS650'}]}}
>>> vh_tree = vh_schema.encode(vh_data)
>>> isinstance(vh_tree, et._Element)
False
>>> vh_tree = vh_schema.encode(vh_data, etree_element_class=et.Element)
>>> isinstance(vh_tree, et._Element)
True
```

**Comment by proofit404** [comment]
I would try to do so. Thanks!
