### ISSUE TITLE
API generation from schema

### ISSUE THREAD

**Issue by stefanseefeld** [sissaschool/xmlschema#207]
I'm looking for a way to map an XML schema directly to a Python API to programmatically construct (valid) content. The schema may be used in a metaclass to constrain what objects may be instantiated, what children & properties defined, etc.

Does something like this already exist ? If not, would there be interest in PRs adding support for such functionality ?

**Comment by brunato** [comment]
Hi,

i left generators part out of this package for avoid of insert other dependencies. But I've worked also on another package that uses xmlschema for generating code. The package is https://github.com/QEF/xsdtools and currently is still in alpha, intending to collect ideas for generating code from XSD schemas.

It's based on jinja templates and it was developed from a previous tool written for generating Fortran code for processing XML data, but with a look on using the same generators for other languages (C, Python).

Another tool that uses jinja is https://github.com/tefra/xsdata, that parse XML and XSD with custom classes and is dedicated for generating Python 3.7+ dataclasses from XSD schemas. It uses xmlschema only for testing purposes, not for generating code.

I don't know if these project can be useful for what you have to do. Do you want to use jinja for building Python code, or your proposal would use another approach?

**Comment by stefanseefeld** [comment]
Hello,
thanks for the detailed reply with all the references. I'll review the projects you mention, but I suspect that they work quite differently from what I want to do: what I have in mind isn't a code-generating tool, but a meta-programming technique that would generate the API on-the-fly.
I'll try to put together a quick prototype to illustrate the idea, then we can compare.

**Comment by brunato** [comment]
Hi,
are you still trying to prepare a prototype for API generation or other projects (eg. xsdata) have got your attention?

Thank you
Davide

**Comment by stefanseefeld** [comment]
Yes, I would very much like to pursue the idea, but have been overwhelmed by other tasks for the last couple of months. Sorry !

**Comment by brunato** [comment]
Don't worry, I'm already developing an improvement on this. In next release v1.5 I'm going to add data objects with schema bindings and in v1.6 maybe I ought to add also a meta-class to create custom data objects with schema bindings.
Maybe after the publication of v1.5 you could contribute on developing the meta-class or give me comments/suggestions.

**Comment by brunato** [comment]
I've just published v1.5.1. Added also a first release of XML data bindings generation. I'm still considering this as an experimental feature so if you (or others ...) have the opportunity to use I would appreciate any comments or advice about.
