### ISSUE TITLE
Issues with encoding/decoding of xml data 

### ISSUE THREAD

**Issue by IamTheLime** [sissaschool/xmlschema#214]
As part of an integration I am currently doing I have a main XSD file that imports a second XSD, one of the types includes an element from the second XSD as follows:
```  <xs:complexType name="ComplexType">
    <xs:sequence>
       ....
      <xs:element ref="p:SecondaryXSDType" />
    </xs:sequence>
  </xs:complexType>
```
The library is able to decode an XML into a dict just fine, however I am facing issues with the encoding, the secondary XMD
includes a complex type that declares an attribute:
```
<xs:complexType name="NameofType">
		<xs:complexContent>
			<xs:extension base="p:p:SecondaryXSDType">
				<xs:sequence>
					<xs:element name="Name" ></xs:element>
				</xs:sequence>
				<xs:attribute name="thisattributecauseserror" type="xs:boolean" use="required">
				</xs:attribute>
			</xs:extension>
</xs:complexContent>
```
executing 
```
schema = xmlschema.XMLSchema(
    "../assets/MainXSD.xsd",
converter=xmlschema.XMLSchemaConverter(preserve_root=False, strip_namespaces=False),
    namespace="namespace"
)
response_schema.encode(response_schema.decode("xml_document.xml"))
```
Will claim that it is missing required attribute "Thisattributecauseserror"  during validation process, upon looking at the error it also seems that the namespace for this attribute is expanded potentially failing the matching with the XsdAttributeGroup `'{namespace}Thisattributecauseserror': True` 

Thank you in advance for any help you can provide.

**Comment by brunato** [comment]
Hi,
the attribute could have a qualified form il the XSD file where is defined has `attributeFormDefault="qualified"`. 
Check better your schemas because `<xs:element ref="p:SecondaryXSDType"` has no sense.

To try reproducing the error I need those information:
 - If the main XSD file has a _targetNamespace_
 - The values of _attributeFormDefault_ and _elementFormDefault_ attributes of both schemas, if they are specified.

If you can provide full schemas and the XML case it might be simpler finding the problem.

**Comment by IamTheLime** [comment]
Hi, thanks for the prompt reply, the attribute for the imported schemas are open and can be found here:
https://github.com/PriceComparisonStandardsGroup/AddOns/blob/master/Schema/AddOns.xsd (The attribute in question is the Financeable attribute for the ComplexType "Incremental")

This is included in the main XSD as follows
``` mainschema.xsd
<xs:schema	xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:p="urn:PriceComparisonStandardsGroup/20160505/AddOns"
    		    xmlns="[xlmnsURI]"
  			    targetNamespace="[targetNamespaceURI]"
  			    elementFormDefault="qualified"
  			    attributeFormDefault="unqualified"
  			    version="2.1">

<xs:import namespace="urn:PriceComparisonStandardsGroup/20160505/AddOns" schemaLocation="https://raw.githubusercontent.com/PriceComparisonStandardsGroup/AddOns/master/Schema/AddOns.xsd" />
...
  <xs:complexType name="ComplexTypeX">
    <xs:sequence>
      <xs:element ref="p:AddOns" />
    </xs:sequence>
  </xs:complexType>
```

**Comment by brunato** [comment]
```
{'{http://www.w3.org/2001/XMLSchema-instance}type': 'p:Incremental', 'Category': 'HomeEmergency', 'SubType': 'HomeEmergency', '{<<MainXSDNamespace>>}Financeable': True}
```
`<<MainXSDNamespace>>` is "[targetNamespaceURI]" or "urn:PriceComparisonStandardsGroup/20160505/AddOns"?
Thanks

**Comment by IamTheLime** [comment]
> ```
> {'{http://www.w3.org/2001/XMLSchema-instance}type': 'p:Incremental', 'Category': 'HomeEmergency', 'SubType': 'HomeEmergency', '{<<MainXSDNamespace>>}Financeable': True}
> ```
> 
> `<<MainXSDNamespace>>` is "[targetNamespaceURI]" or "urn:PriceComparisonStandardsGroup/20160505/AddOns"?
> Thanks

Apologies that was indeed a poor way of phrasing it, that would be the "[targetNamespaceURI]" specified on the XSD that imports the Addons.xsd **not** "urn:PriceComparisonStandardsGroup/20160505/AddOns"

**Comment by brunato** [comment]
Found a resolution for this problem. It's generated both by xsi:type and a not empty default namespace.  The fix will be provided with next release. 

Here is a patch for source installation if you need sooner: [patch-for-issue-214.txt](https://github.com/sissaschool/xmlschema/files/5589623/patch-for-issue-214.txt)

**Comment by IamTheLime** [comment]
Amazing, can confirm the patch works
