### ISSUE TITLE
effective_min_occurs and effective_max_occurs always return "1" for an element

### ISSUE THREAD

**Issue by hcw70** [sissaschool/xmlschema#216]
When looking at a XSD like
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="protocol">
        <xs:complexType>
            <xs:sequence minOccurs='0' maxOccurs='unbounded'>
                <xs:element name="doc" type="TDocumentable"/>                            
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TBase" abstract="true">
        <xs:annotation><xs:documentation>
            Base type definition for all other types in the document.
            Used to have a base type in the generated PyXB bindings.
        </xs:documentation></xs:annotation>
    </xs:complexType>

    <xs:complexType name="TDocumentable">
        <xs:complexContent>
            <xs:extension base="TBase">
                <xs:choice minOccurs="0" maxOccurs="1">
                    <xs:element name="doc_val" type="xs:string"/>
                </xs:choice>
                <xs:attribute name="eval" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

```

and asking for effective_min_occurs for doc_val

```
        doc_val = xsd.all_elements["doc_val"][0]
        doc_va_p = doc_val.parent
        min_val = doc_val.effective_min_occurs
        self.assertEqual(doc_val.effective_min_occurs, 0)
        self.assertEqual(doc_val.effective_max_occurs, 1)
``` 
i always get 1 / 1 for effective min / max.

Stepping into
`        min_val = doc_val.effective_min_occurs
`
reveals a call to 
```
class ParticleMixin(object):
    min_occurs = 1
    max_occurs = 1

    @property
    def effective_min_occurs(self):
        return self.min_occurs
```
which seems to be wrong since min_occurs / max_occurs is fixed to one....

**Comment by brunato** [comment]
Hi,

_effective_min_occurs_ and _effective_max_occurs_ are internals used for checking valid restrictions of XSD 1.1 choice groups.
I will add a pair of docstrings to explain this. Anyway these are defined as properties and their values are identical to min_occurs and max_occurs for xs:element or xs:any. Values can vary for model groups and may change depending on model type and inner structure. So both properties are redefined for model group class (see _models.py_).

> 
> ```
> class ParticleMixin(object):
>     min_occurs = 1
>     max_occurs = 1
> 
>     @property
>     def effective_min_occurs(self):
>         return self.min_occurs
> ```
> 
> which seems to be wrong since min_occurs / max_occurs is fixed to one....

Those are class properties and are default values, reassigned at instance level when provided as attributes.

Anyway I checked _effective_min_occurs_ and _effective_max_occurs_, in order to refine the sense of both. In the _model.py_ code they will be changed to:

```python
    @property
    def effective_min_occurs(self):
        if not self.min_occurs or not self:
            return 0
        elif self.model == 'choice':
            if any(not e.min_occurs for e in self.iter_model()):
                return 0
        else:
            if all(not e.min_occurs for e in self.iter_model()):
                return 0
        return self.min_occurs

    @property
    def effective_max_occurs(self):
        if self.max_occurs == 0 or not self:
            return 0

        effective_items = list(e for e in self.iter_model() if e.max_occurs != 0)
        if not effective_items:
            return 0
        elif self.max_occurs is None:
            return
        elif self.model == 'choice':
            if any(e.max_occurs is None for e in effective_items):
                return
            return self.max_occurs * max(e.max_occurs for e in effective_items)

        not_emptiable_items = [e for e in effective_items if e.min_occurs]
        if not not_emptiable_items:
            if any(e.max_occurs is None for e in effective_items):
                return
            return self.max_occurs * max(e.max_occurs for e in effective_items)
        elif len(not_emptiable_items) > 1:
            return self.max_occurs

        try:
            return self.max_occurs * not_emptiable_items[0].max_occurs
        except TypeError:
            return
```

**Comment by hcw70** [comment]
So the real origin of my issue is to extract doc how often a element is allowed in an xml document
based on the schema.

So the "original" issue is with a type like
```
    <xs:element name="protocol">
        <xs:complexType>
            <xs:sequence minOccurs='0' maxOccurs='unbounded'>
                <xs:element name="doc" type="TDocumentable"/>                            
            </xs:sequence>
        </xs:complexType>
    </xs:element>
```
that element["doc"].min_occurs would reveal me "0" since it can be omitted. 
However, in xmlschema i always get "1", maybe because the element "doc" itself has minOccurs="1" per default.
So i was looking for something matching my requirement and stumbled with a bit of hope over effective_min_occurs.....

So maybe to rephrase my problem, how do i get to `"doc can appear 0 .. inf times in element "protocol"` with help of xmlschema?

**Comment by brunato** [comment]
With the new version of _effective_min_occurs_ and _effective_max_occurs_ the result on xs:sequence will be 0 and None.

But as i said these properties depends on group model. Giving a general rule is not simple because model groups can be nested without a defined limit. Moreover group references break the parent relationship between the origin model group and its leaf elements.

Better to put the maxOccurs and minOccurs on leaf elements whenever possible:

```
    <xs:element name="protocol">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="doc" type="TDocumentable" minOccurs='0' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
```

Anyway I will examine if it's possible to define new method(s) for model groups to attempt the calculation of total min/max occurrences of a subitem.

**Comment by hcw70** [comment]
Thank you for your analysis.... 
I did not expect it to be that hard... 
but thinking about the nesting of sequences / choices indeed makes that hard....

**Comment by brunato** [comment]
Hi,
within the release v1.4.0 I've added two internal methods _overall_min_occurs_/_overall_max_occurs_ to model groups. These methods can be used to have an _estimation_ of the min and max occurs of a sub-particle (usually an element) in the selected group. I hope this can be helpful for your needs.

**Comment by hcw70** [comment]
Great! I will have a look soon....

**Comment by hcw70** [comment]
@brunato Now i had time to look at this. But i dunno how i can use this.
I have an instance of an XsdElement in my var. How to call  overall_min_occurs/overall_max_occurs ? How to navigate to the associated "particle" (whatever that is and wherever it may be... 8-> ) ?

Regards

**Comment by hcw70** [comment]
@brunato Can you give me a hint on this?

Regards
Hauke

**Comment by brunato** [comment]
Hi, 
_overall_min_occurs_/_overall_max_occurs_  are methods of model groups that can be applied on other particles (element or subgroups).

With your sample schema:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema('issue_216.xsd')
>>> protocol = schema.find('protocol')
>>> protocol.type
XsdComplexType(content='element-only', attributes=[])
>>> protocol.type.content
XsdGroup(model='sequence', occurs=[0, None])
>>>
>>> doc_element = schema.find('protocol/doc')
>>> doc_element
XsdElement(name='doc', occurs=[1, 1])
>>>
>>> protocol.type.content.overall_max_occurs(doc_element)   # is None that means unbounded
>>> protocol.type.content.overall_min_occurs(doc_element)
0
>>>
>>> doc_val_element = schema.find('protocol/doc/doc_val')
>>> doc_val_element
XsdElement(name='doc_val', occurs=[1, 1])
>>> doc_element.type.content.overall_min_occurs(doc_val_element)
0
>>> doc_element.type.content.overall_max_occurs(doc_val_element)
1
```
