### ISSUE TITLE
xs:boolean error with defaults

### ISSUE THREAD

**Issue by allisonChilton** [sissaschool/xmlschema#218]
https://github.com/sissaschool/xmlschema/blob/9a57e760b6adc49604e7b4472598755603030fca/xmlschema/validators/attributes.py#L83

Above line reads the xs:boolean type (correctly) from xsd spec as "false" and "true". If you use this to encode the default arguments later, iter encode will yield str 'false' or 'true' at: 
https://github.com/sissaschool/xmlschema/blob/9a57e760b6adc49604e7b4472598755603030fca/xmlschema/validators/attributes.py#L622

which causes it to fail encoding at: https://github.com/sissaschool/xmlschema/blob/9a57e760b6adc49604e7b4472598755603030fca/xmlschema/validators/simple_types.py#L682

**Comment by brunato** [comment]
Hi,
as I checked this is not only affecting atttributes, but also elements. The resolution will be adding another _attribute_ to XSD elements/attributes (eg. default_value=None) and also for fixed (eg. fixed_value).

Thank you for reporting this issue

**Comment by brunato** [comment]
Resolved in v1.4.0 without adding additional attributes (eg. default_value). For XSD attributes the block that adds missing values has been moved after the iteration cycle. In all cases the encoded value is simply determined by default/fixed value associated.
