### ISSUE TITLE
Case sensitive hexBinary validation

### ISSUE THREAD

**Issue by tefra** [sissaschool/xmlschema#222]
Datatype `xs:hexBinary` validation is **case sensitive** in xmlschema for fixed/enumeration values, I think they should be **case insensitive**, [source](https://www.w3.org/TR/xmlschema-2/#hexBinary)

I checked lxml, a few online validators as well and I also see valid test cases in w3c suite where both uppercase and lowercase lexical representations appear.

```python
import xmlschema
from lxml import etree

schema_tree = etree.fromstring("""<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="first" type="xsd:hexBinary" fixed="abcedf" />
  <xsd:element name="second" type="enum" />
  <xsd:simpleType name="enum">
    <xsd:restriction base="xsd:hexBinary">
      <xsd:enumeration value="abcedf" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:element name="root">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="first" />
        <xsd:element ref="second" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>""")

xml_tree = etree.fromstring("""<root>
  <first>ABCEDF</first>
  <second>ABCEDF</second>
</root>""")

etree.XMLSchema(schema_tree).validate(xml_tree)  # Passes
xmlschema.XMLSchema11(schema_tree).validate(xml_tree)  # Fails
```

**Comment by brunato** [comment]
Yes, the equivalence between the fixed value or the enumeration value must be done with case insensitive. 
Probably it requires a comparison of data-typed value for a general solution and so maybe a fix also for datatype class in _elementpath_ package.

I'll add your example into test cases, 
thanks

**Comment by brunato** [comment]
I've fixed HexBinary class in _elementpath_ v2.1.2, adding the proper `__len__()` and fixing `__eq__()` to compare uppercase strings. 

In xmlschema binary types (_xs:hexBinary_ and _xs:base64Binary_) will be managed like datetime types, with and additional option _binary_types_ to schema decode methods.

**Comment by tefra** [comment]
Thanks for the update @brunato, so we also need an update in xmlschema right?

**Comment by brunato** [comment]
Yes, I've already fixed in my develop but I found a related issue on encoding binary, that probably affect also datetime datatypes.

**Comment by brunato** [comment]
You can now try v1.4.2 release of _xmlschema_, that has the fix for this issue.

**Comment by tefra** [comment]
Excellent @brunato I can confirm the fix is working
