### ISSUE TITLE
xmlschema should fail gracefully when given an obviously not valid file by mistake (like .DS_store)

### ISSUE THREAD

**Issue by juanlucasrey** [sissaschool/xmlschema#224]
currently the message is a cryptic

Traceback (most recent call last):
  File "user_file.py", line 14, in <module>
    if schema.is_valid(os.path.join(root, file)):
  File "/usr/local/lib/python3.9/site-packages/xmlschema/validators/schema.py", line 1420, in is_valid
    error = next(self.iter_errors(source, path, schema_path, use_defaults, namespaces), None)
  File "/usr/local/lib/python3.9/site-packages/xmlschema/validators/schema.py", line 1441, in iter_errors
    source = XMLResource(source, defuse=self.defuse, timeout=self.timeout)
  File "/usr/local/lib/python3.9/site-packages/xmlschema/resources.py", line 385, in __init__
    self.parse(source, lazy)
  File "/usr/local/lib/python3.9/site-packages/xmlschema/resources.py", line 576, in parse
    self._parse(resource)
  File "/usr/local/lib/python3.9/site-packages/xmlschema/resources.py", line 539, in _parse
    for event, node in ElementTree.iterparse(resource, events):
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1254, in iterator
    yield from pullparser.read_events()
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1329, in read_events
    raise event
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1301, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by brunato** [comment]
It's the message of **xml.etree.ElementTree.iterparse** API for a not-well formed XML file. 
I could intercept the error and re-raise as an `xmlschema.XMLResourceError` but formally this is not an error generated by the _xmlschema_ library and someone could prefer to distinguish between them.
Also if i encapsulate the error the message would not be more precise anyway.

**Comment by juanlucasrey** [comment]
I understand what the origin of the error is. but I insist this is still not failing gracefully. you suggest intercepting an error, but it would be better to do a basic check before sending obviously wrong data to the xml.etree library. An example would be checking that the first character is "<".

take this file for example:
------------------------------
from xmlschema import XMLSchema
from lxml import etree
from io import StringIO


def lxml_validation(xml_string, schema_string):
    xml_schema_io = StringIO(schema_string)
    xmlschema_doc = etree.parse(xml_schema_io)
    xmlschema_lxml = etree.XMLSchema(xmlschema_doc)

    xml_io = StringIO(xml_string)
    doc = etree.parse(xml_io)
    print(xmlschema_lxml.validate(doc))


def xmlschema_validation(xml_string, schema_string):
    xml_schema_io = StringIO(schema_string)
    xmlschema_xmlschema = XMLSchema(xml_schema_io)

    xml_io = StringIO(xml_string)
    print(xmlschema_xmlschema.is_valid(xml_io))


if __name__ == '__main__':
    schema_string = '''\
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <xsd:element name="a" type="AType"/>
        <xsd:complexType name="AType">
            <xsd:sequence>
                <xsd:element name="b" type="xsd:string" />
            </xsd:sequence>
        </xsd:complexType>
        </xsd:schema>
        '''

    valid_xml = '<a><b></b></a>'

    lxml_validation(valid_xml,
                    schema_string)

    xmlschema_validation(valid_xml,
                         schema_string)

    invalid_xml = 'abba'

    switch = False

    if(switch):
        lxml_validation(invalid_xml,
                        schema_string)
    else:
        xmlschema_validation(invalid_xml,
                             schema_string)
--------------------------------

is you change Switch  to True you will see that lxml's error checks for this first character and tells the user:
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found

lxml owns the error and gives a useful error message.

in xmlschema's case, changing With to False, you will get an unhelpful message not owned by xmlschema and not giving a clear indication to what is wrong.

**Comment by brunato** [comment]
Doing basic checks on file or remote resources is not a good option, because you have to rewind the file-like object, and this could not be always applicable. So this is done for a restricted set of cases and by explicit option (eg. defuse a lazy resource).

I agree that the **lxml**'s XML parser usually produces more clear error messages but I cannot substitute the _xml.etree.ElementTree_ parser (_expat_ parser) in its role for at least three reasons:

- It's the preferred package for processing XML data of the Python's standard library
- For performance, because it's a C-optimized module
- It's always available with a Python distribution

Using _lxml_ instead would not be better on processing very large files in lazy mode, because you need to delete nodes also on parent elements. So _lxml_ is certainly a more complete choice but it could requires more memory and more processing steps. So the choice in _xmlschema_ is to use _ElementTree_ for reading XML from resource. If you prefer to use lxml you can read you XML file with _lxml.etree_ and then pass it to schema validator.
