### ISSUE TITLE
Is setup_requires=[elementpath] still needed?

### ISSUE THREAD

**Issue by gokcennurlu** [sissaschool/xmlschema#225]
Hello,

I'd like to thank all for amazing work on this tool firstly.

While updating it from a very early version to the current one, I noticed that `elementpath` was pulled as a `setup.py` dependency and I found that confusing at the first glance.

Looks like it became a build time dependency with 9aaa9f12445f372052509e6788896fbd0577c476 and later added to `setup.py` with 4b7b16a750052e1bc23fc13744e784521229dfd. AFAIU, it's not needed anymore with some recent changes in ba3b73e56573690129fe9296f6a35053717679cd.

Is `setup_requires=["elementpath"]` still needed and would you consider removing it?

**Comment by brunato** [comment]
Hi,
your observation is correct, _setup_requires_ is not needed anymore because the Unicode categories codepoints are now in a generated python module,  included from _elementpath_. I'll remove this configuration entry from setup.py from the next release.

Thank you
