### ISSUE TITLE
Quoting around tag name missing in some error messages

### ISSUE THREAD

**Issue by pekkaklarck** [sissaschool/xmlschema#226]
I got an error like this when validating an XML file:

> Unexpected child with tag 'name' at position 2. Tag status expected.

It took me some time to understand that `status` is a tag name in the latter sentence. In the former sentence there's no such problem because there are quotes around `name`.

I actually needed to go to the source to make it sure how to interpreter the error and at the same time fixed the problem for me locally. In this case the only thing needed was changing `%s` to `%r` at https://github.com/sissaschool/xmlschema/blob/master/xmlschema/validators/exceptions.py#L330. There's a similar case few lines below and possibly also others.

**Comment by brunato** [comment]
Hi, 
ok, I'm patching error message as you suggested.
Thanks

**Comment by brunato** [comment]
Changes available with release v1.5.3.
