### ISSUE TITLE
Don't configure logging handlers in a library

### ISSUE THREAD

**Issue by tevansuk** [sissaschool/xmlschema#228]
https://github.com/sissaschool/xmlschema/blob/c81d429e2c322f2b679883798bc2a5c26ec9f42b/xmlschema/validators/schema.py#L62-L66

[You should not do this](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library). 

> Note It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

Which is how I spent my morning :/ In order to fix this, the code in my project that sets up logging now needs to have knowledge of where you are (currently) configuring handlers, and import them before setting up our own desired logging so that we can remove the loggers added by the library. Huge pain.

**Comment by brunato** [comment]
I'm sorry, I was not aware of this. Logging is optionally used only in schema initialization to track namespace imports or XSD schemas inclusion. 

I'm going to remove these lines for the next release:

https://github.com/sissaschool/xmlschema/blob/c81d429e2c322f2b679883798bc2a5c26ec9f42b/xmlschema/validators/schema.py#L63-L66

**Comment by brunato** [comment]
Fix available within release v1.5.3.
