### ISSUE TITLE
Python typing information

### ISSUE THREAD

**Issue by gaborbernat** [sissaschool/xmlschema#230]
Hello, I'd like to add type annotations for this package. Are you open to make it inline, or you'd prefer if we'd do it via a stubs-only package, per https://www.python.org/dev/peps/pep-0561? 

Thanks,

**Comment by brunato** [comment]
Hi,
I've already started using inline type annotation in some modules but I've stopped after realizing a problem on how to include annotations about lxml's Elements (optionally usable in validations/decoding), so probably a stubs-only package could be a more simple manner to manage this.

**Comment by gaborbernat** [comment]
> (optionally usable in validations/decoding),

Sounds to me like a protocol-based interface, not?

**Comment by brunato** [comment]
> Sounds to me like a protocol-based interface, not?

Yes, it could be but argument type varies on which XSD compontent you are considering. It's described mainly into `ValidationMixin` definition.

**Comment by brunato** [comment]
Hi @gaborbernat,

about this, have you already planned something for working on, or do you prefer that I start another repo for xmlschema's stubs?

Thanks

**Comment by gaborbernat** [comment]
Feel free to go ahead without me 😊

**Comment by brunato** [comment]
Ok, I'll leave this open until I'll start a stub package for this (soon, before that i want to end some new features for elementpath library)

**Comment by brunato** [comment]
Hi @gaborbernat,

for adding typing information to xmlschema, after experiments on **elementpath** package, I've changed the decision and choose the option of inline annotations, that are more maintainable for me.

In **elementpath** v2.3.0 I used Protocol based annotations, that are necessary because the processed nodes can be ElementTree's data or schema components. For xmlschema the current solution is to use the XSD classes for type annotations, using conditional imports (if TYPE_CHECKING):...) to avoid circular imports at runtime.

The type hints are activated from release v1.7.1 that I'm going to publish today. Glad if you have some feedback for this after.

**Comment by gaborbernat** [comment]
I'm on holiday now, so will have to get back to you in a weeks time, but thanks!

**Comment by gaborbernat** [comment]
So some issues we've ran into:

- `XsdAtomicRestriction.validators` seems to not have an annotations
- When instantiating a schema we get `Call to untyped function "XMLSchema10" in typed context`
- `XsdEnumerationFacets.__iter__` throws ` <nothing> has no attribute "__iter__" (not iterable)`

**Comment by brunato** [comment]
Hi,

have you tested with an external script (or whatever)?
There are other reported issues?

**Comment by gaborbernat** [comment]
I've tested with mypy on our project (which is private, so cannot share it sadly). These three were the only issues we've seen when replacing our stubs with the core typing.

**Comment by brunato** [comment]
Ok, i will try to fix them. The first and the last should be simple to resolve, the 2nd maybe more complicated.

**Comment by brunato** [comment]
A question: do you run check in your code with the option `--disallow-untyped-calls`?

**Comment by gaborbernat** [comment]
I run it with --strict, nothing else.

**Comment by brunato** [comment]
To really fix this I've to going strict also on xmlschema (covering all public API is nearly the same as going strict on the entire library).

**Comment by gaborbernat** [comment]
Sound great to me. On mypy `0.910` the typing generated by xmlschema causes an INTERNAL ERROR. Oddly enough works with mypy 0.810 (but throws those validation failures).

**Comment by brunato** [comment]
The INTERNAL ERROR seems to be related to Protocol checking. A class in xpath.py have to be redefined from ElementProtocol defined in `elementpath.protocols.py`, but a new version of this is also needed for Python < 3.8 ...

**Comment by brunato** [comment]
Found a workaround for fixing the INTERNAL ERROR of mypy for xmlschema. 

Anyway the mypy error seems to be related to a check of the protocol when it's enforced in an instance method, like in this example:

```python
from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class MyProtocol(Protocol):
    def is_valid(self) -> bool: ...
    text: Optional[str]


class MyClass:
    text = None

    def is_valid(self) -> bool:
        assert isinstance(self, MyProtocol)
```

**Comment by gaborbernat** [comment]
You likely want to post that to the mypy issue, could be useful to understand why it's happening in the first time; thanks!

**Comment by brunato** [comment]
New minor relese is available. Type annotations are currently extented to all the public API of the library.
Let me know if your `--strict` mypy checks report any error.

Thanks

**Comment by gaborbernat** [comment]
I think now looks good 👍

**Comment by brunato** [comment]
Very good!

A _little_ question about *tox* testing before closing this ... ;)
In new release I have added some mypy detailed tests with some little scripts and `test_typing.py` module, but running --strict  within tox checks the strictness not only in the test script but also on the xmlschema library.

There is a setting to avoiding this behavior?

Thank you

**Comment by gaborbernat** [comment]
I don't think that's tox related, more mypy related. I think though you want to call mypy twice, one on the test folder and once for where you don't want strict? 🤔

**Comment by brunato** [comment]
I launch --strict on a litte script (test_strict_simple_types). With plain unittest is going well, but when I run the same test in tox the strictness is applied also on xmlschema ... I dont' know why ... I will check this again ...

**Comment by gaborbernat** [comment]
Can you annotate https://github.com/sissaschool/xmlschema/blob/155c31aefe558399c4e6ce98aa8829ec67c18fe9/xmlschema/validators/builtins.py#L329, currently mypy interprets it as a fixed size tuple, rather than a varied sized one, you want something like: ``Tuple[TypedDict, ...]`` and replace the dict as the correct typeddict?

**Comment by gaborbernat** [comment]
This https://github.com/sissaschool/xmlschema/blob/155c31aefe/xmlschema/validators/particles.py#L316  is available via XsdGroup but is not typed.

**Comment by gaborbernat** [comment]
The type of an attribute should be of type XsdType no? Currently is Optional[Any] - https://github.com/sissaschool/xmlschema/blob/155c31aefe/xmlschema/validators/attributes.py#L53-L59?

**Comment by brunato** [comment]
> Can you annotate
> 
> https://github.com/sissaschool/xmlschema/blob/155c31aefe558399c4e6ce98aa8829ec67c18fe9/xmlschema/validators/builtins.py#L329
> , currently mypy interprets it as a fixed size tuple, rather than a varied sized one, you want something like: `Tuple[TypedDict, ...]` and replace the dict as the correct typeddict?

These tuples are internals used only to initially build XSD built-in types (by _xsd_builtin_types_factory_), so i will probably annotate them for a coarse analysis.

**Comment by brunato** [comment]
> This https://github.com/sissaschool/xmlschema/blob/155c31aefe/xmlschema/validators/particles.py#L316 is available via XsdGroup but is not typed.

There are a lot of calls on XSD components and many of them cannot be simply annotated without generating mypy errors, because often component tests are done with auxiliary functions (eg. has_simple_content()) that cannot be interpreted by mypy in the right way. So the convergence to an almost full type annotation could take long time and the final result could be non optimal.

**Comment by brunato** [comment]
> The type of an attribute should be of type XsdType no? Currently is Optional[Any] - https://github.com/sissaschool/xmlschema/blob/155c31aefe/xmlschema/validators/attributes.py#L53-L59?

The type of an attribute must be XsdSimpleType, i will replace Any and check with Optional[XsdSimpleType] (value before parsing is None).

**Comment by abrisan** [comment]
> > This https://github.com/sissaschool/xmlschema/blob/155c31aefe/xmlschema/validators/particles.py#L316 is available via XsdGroup but is not typed.
> 
> There are a lot of calls on XSD components and many of them cannot be simply annotated without generating mypy errors, because often component tests are done with auxiliary functions (eg. has_simple_content()) that cannot be interpreted by mypy in the right way. So the convergence to an almost full type annotation could take long time and the final result could be non optimal.

Have you considered just adding `Any` to all the types that fall into this category? Mypy would treat most of these things as implicit `Any`s anyways I suppose, and at least it would silence errors like this for your clients:

```error: Call to untyped function "iter_elements" in typed context``` 

It's not perfect by any means, but it's a start - and it also gives you nice way to see what is left to do by just searching for all `Any`s in your code 😃

**Comment by brunato** [comment]
> Have you considered just adding `Any` to all the types that fall into this category? Mypy would treat most of these things as implicit `Any`s anyways I suppose, and at least it would silence errors like this for your clients:
> 
> `error: Call to untyped function "iter_elements" in typed context`
> 
> It's not perfect by any means, but it's a start - and it also gives you nice way to see what is left to do by just searching for all `Any`s in your code

It's a choice but sometimes i use `Any` also for some local variables in methods and also the type for generic helper functions, for example: 

```python
def is_url(obj: Any) -> bool:
    """
    Checks if and object can be an URL, restricting to strings that cannot be XML data.
    """
    if not isinstance(obj, (str, bytes)):
        return False
    elif isinstance(obj, str):
        if '\n' in obj or obj.lstrip().startswith('<'):
            return False
    elif b'\n' in obj or obj.lstrip().startswith(b'<'):
        return False
```

Anyway nothing impedes to use a type alias for this purpose:

`AnyType = Any`

**Comment by gaborbernat** [comment]
I think there you want to use object and not Any, see https://stackoverflow.com/questions/39817081/typing-any-vs-object

**Comment by brunato** [comment]
> I think there you want to use object and not Any, see https://stackoverflow.com/questions/39817081/typing-any-vs-object

Replacing `Any` with `object` give me an error in `is_url()`:

    $ mypy xmlschema/resources.py 
    xmlschema/resources.py:222: error: "object" has no attribute "strip"  [attr-defined]
    Found 1 error in 1 file (checked 1 source file)

Analyzing obj's type with a sample case:

```python
def check_type(obj: object) -> bool:
    if not isinstance(obj, (str, bytes)):
        reveal_type(obj)
        return False

    reveal_type(obj)
    reveal_type(obj)
    return bool(obj.strip())
```
that produces as expected the output:
```bash
$ mypy mypy-sample-case.py
mypy-sample-case.py:3: note: Revealed type is "builtins.object"
mypy-sample-case.py:6: note: Revealed type is "Union[builtins.str, builtins.bytes]"
mypy-sample-case.py:7: note: Revealed type is "Union[builtins.str, builtins.bytes]"
```

but adding a related instance check (str or bytes):

```python
def check_type(obj: object) -> bool:
    if not isinstance(obj, (str, bytes)):
        reveal_type(obj)
        return False

    reveal_type(obj)
    if isinstance(obj, str):
        reveal_type(obj)
    else:
        reveal_type(obj)
    reveal_type(obj)
    return bool(obj.strip())
```

the obj's type is restored to the initial and an error is reported:

```bash
$ mypy mypy-sample-case.py
mypy-sample-case.py:3: note: Revealed type is "builtins.object"
mypy-sample-case.py:6: note: Revealed type is "Union[builtins.str, builtins.bytes]"
mypy-sample-case.py:8: note: Revealed type is "builtins.str"
mypy-sample-case.py:10: note: Revealed type is "builtins.bytes"
mypy-sample-case.py:11: note: Revealed type is "builtins.object"
mypy-sample-case.py:12: error: "object" has no attribute "strip"
Found 1 error in 1 file (checked 1 source file)
```

The same behaviour if i replace `object` with `Any`, excepting the final error obviously.

**Comment by brunato** [comment]
Hi, 
new release v1.8.2 should fix `IO[str]` compatibility.

**Comment by brunato** [comment]
I close the issue assuming that is resolved, reopen this if it's not.
Best

**Comment by gaborbernat** [comment]
Forgot to get back but all good now, thanks!
