### ISSUE TITLE
[Enhancement] Raising all the exceptions for one XML without breaking

### ISSUE THREAD

**Issue by jphoon** [sissaschool/xmlschema#234]
I have a very long XML that needs to be checked against a schema. However, the xmlschema libraries breaks after finding one error.
Is there any plans on showing all the errors/exceptions without breaking? This could be useful for documentation purposes.

**Comment by brunato** [comment]
Hi, 
for generating all the errors you can try `iter_errors()`. Usually one can also use schema.decode() providing validation='lax' that returns a tuple (obj, errors) but depends how big is your XML file.

**Comment by brunato** [comment]
Close the issue because the feature is already implemented.
