### ISSUE TITLE
Does not properly resolve relative import in imported file

### ISSUE THREAD

**Issue by danielk333** [sissaschool/xmlschema#237]
When loading a wsdl file which imports another wsdl which in turn contains a relative import (now with another relative root) it tries to resolve the import relative to the first original file rather then the file where the import is stated. This probably is also true for general xml documents as i assume the wsdl extras is just using the base xml logic.

I have no idea where in the code this might be fixed though :sweat_smile:

**Comment by brunato** [comment]
Hi,
I've tested with three sample schemas, but seems fine.
Could you please explain the loaded path sequence? (not important the real paths but the structure of relative paths in sequence)
Thanks

**Comment by brunato** [comment]
I tried with a modified version of _stockquote_ example, with this setting on a Linux OS:

```bash
$ tree
.
├── dir1
│   └── stockquoteservice.wsdl
└── dir2
    ├── stockquote.wsdl
    └── stockquote.xsd

2 directories, 3 files
```

**stockquoteservice.wsdl**: 
   `<import namespace="http://example.com/stockquote/definitions"
           location="../dir2/stockquote.wsdl"/>`
**stockquote.wsdl**:
  `<import namespace="http://example.com/stockquote/schemas" location="./stockquote.xsd" />`

using this setup it seems to work in all cases like this (I tried also from `dir1/`, `dir2/` or with an absolute path ...):

```pycon
>>> import xmlschema.extras.wsdl as wsdl
>>> wsdl_doc = wsdl.Wsdl11Document('dir1/stockquoteservice.wsdl')
>>> list(wsdl_doc.maps.imports.values())[0].url
'file:///tmp/issue_237/dir2/stockquote.xsd'
>>> list(wsdl_doc.maps.imports.values())[1].url
'file:///tmp/issue_237/dir2/stockquote.wsdl'
```
