### ISSUE TITLE
encode("utf-8") and attr_prefix='', cdata_key='text'

### ISSUE THREAD

**Issue by bjornjorgensen** [sissaschool/xmlschema#240]
Hi I have used xmltodict before to convert xml files to json.
Now that I have all the xsd files I will try the same with yours xmlschema.

The code that I use before that works are
```

with open(fullname, 'rb') as f:
        xmlString = f.read()

    jsonString = json.dumps(xmltodict.parse(xmlString, process_namespaces=True, attr_prefix='', cdata_key='text'))
with open(fullname[:-4] + ".json", 'w') as f:
        f.write(jsonString)
```

so the code that I try now with xmlschema

`
schema_file = open("C:/Users/ujorbjo00/Nextcloud2/falk/xsd/V3.0.2/DOFFIN_ESENDERS.xd")

schema = xmlschema.XMLSchema(schema_file, base_url="C:/Users/ujorbjo00/Nextcloud2/falk/xsd/V3.0.2/")

path = "C:/citrix overføring/doffin/flyttede_filer/V3_0_2/1/"
for filename in os.listdir(path):
    if not filename.endswith('.xml'):
        continue

    fullname = os.path.join(path, filename)

    jsonString = json.dumps(xmlschema.to_dict(fullname, schema=schema, decimal_type=str), indent=4).encode("utf-8")
    print(jsonString)
    
    with open(fullname[:-4] + ".json", 'w') as f:
        f.write(jsonString)
`

now I get b'{\n    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",\n    "@xsi:noNa

If I remove .encode("utf-8") 
Then I get 
"OFFICIALNAME": "Direktoratet for \u00f8konomistyring (DF\u00d8)", 

where all the norwegian øæå are missing.

And can I give xmlschema attr_prefix='', cdata_key='text' ?

**Comment by brunato** [comment]
Hi,
with xmlschema you can provide `attr_prefix=''`. About character data there are `text_prefix` for element's text (that is `'$' `for default) and `cdata_prefix` for cdata in mixed-content (eg. if you provide `cdata_prefix='#'` the sections are named '#1', '#2' and so on).

I will take a look to character encoding problem. Schemas with a sample XML can help me to detect the problem.

**Comment by brunato** [comment]
About character encoding seems to be an unnecessary `.encode("utf-8")` applied to json string after dumps. Remove that and it should be fine.

**Comment by bjornjorgensen** [comment]
[2018-300000.zip](https://github.com/sissaschool/xmlschema/files/6290777/2018-300000.zip)

No it dident work. 
I uploaded on of the files.

**Comment by brunato** [comment]
Consider this resolved and anyway is how _json.dumps_ works.

**Comment by bjornjorgensen** [comment]
Yes, Iam using `jsonString = json.dumps(xmlschema.to_dict(fullname, schema=schema, decimal_type=str, attr_prefix='', text_key='', cdata_prefix= ''),ensure_ascii=False, indent=4)` and it works on some files. Then I get 

> codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\uf0a7' in position 2771: character maps to <undefined>

So its probely some erros in the xml files.

**Comment by brunato** [comment]
U+F0A7 is not a valid unicode character.
