### ISSUE TITLE
Getting XML using .from_json

### ISSUE THREAD

**Issue by TonyTNguyen** [sissaschool/xmlschema#241]
I have this weird problem that I try to look around for help, but no available. Basically I have json data coming in. I want it to encode to XML with schema validation using your wonderful library. Here is my reduced code:

```
import xmlschema
import datetime
import xml.etree.ElementTree as ET
import json
CAPSchema=xmlschema.XMLSchema('https://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2.xsd')
jsonTxt = """{
  "alert": {
    "identifier": "str1234",
    "sender": "str1234",
    "sent": "2012-12-13T12:12:12",
    "status": "Actual",
    "msgType": "Alert",
    "source": "str1234",
    "scope": "Public",
    "restriction": "str1234",
    "addresses": "str1234",
    "code": "str1234",
    "note": "str1234",
    "references": "str1234",
    "incidents": "str1234",
    "info": {
      "language": "???",
      "category": "Geo",
      "event": "str1234",
      "responseType": "Shelter",
      "urgency": "Immediate",
      "severity": "Extreme",
      "certainty": "Observed",
      "audience": "str1234",
      "eventCode": {
        "valueName": "str1234",
        "value": "str1234"
      },
      "effective": "2012-12-13T12:12:12-05:00",
      "onset": "2012-12-13T12:12:12-05:00",
      "expires": "2012-12-13T12:12:12-05:00",
      "senderName": "str1234",
      "headline": "str1234",
      "description": "str1234",
      "instruction": "str1234",
      "web": "http://www.xsd2xml.com",
      "contact": "str1234",
      "parameter": {
        "valueName": "str1234",
        "value": "str1234"
      },
      "resource": {
        "resourceDesc": "str1234",
        "mimeType": "str1234",
        "size": "1234",
        "uri": "http://www.xsd2xml.com",
        "derefUri": "str1234",
        "digest": "str1234"
      },
      "area": {
        "areaDesc": "str1234",
        "polygon": "str1234",
        "circle": "str1234",
        "geocode": {
          "valueName": "str1234",
          "value": "str1234"
        },
        "altitude": "123.45",
        "ceiling": "123.45"
      }
    }
  }
}"""
try:
	xmlData = xmlschema.from_json(jsonTxt ,schema = CAPSchema)
except xmlschema.XMLSchemaValidationError as exp:
        print("Unable to validate: " + str(exp))
except xmlschema.XMLSchemaEncodeError as exp1:
        print("Cannot encode xml: " + str(exp1))
print("Program end")
```
It doesn't matter how I twist and turn this, I always come back with error:

_Reason: unable to select an element for decoding data, provide a valid 'path' argument._

I try to give it some path, but it will result to some other error. The json text I generated using http://xsd2xml.com/ and https://www.utilities-online.info/xmltojson. I track this down in your code, and it seems like it cannot parse the XSD file (in iter_encode, file schema.py), even it works fine in validation, decoding, and encode xml to dictionary, json,... I am only beginner on Python, so I cannot figure out exactly how the code behave like this.

Can you enlighten me on this?

**Comment by brunato** [comment]
Hi,
it's a matter of namespaces, despite there is no prefix the data are still bound to namespace of the schema:

```pycon
>>> CAPSchema.target_namespace
'urn:oasis:names:tc:emergency:cap:1.2'
```

so you have to provide a map for default namespace:

```pycon
>>> xmlData = xmlschema.from_json(jsonTxt ,schema = CAPSchema, namespaces={'': 'urn:oasis:names:tc:emergency:cap:1.2'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brunato/Development/projects/xmlschema/xmlschema/documents.py", line 309, in from_json
    return schema.encode(obj, path=path, converter=converter, **kwargs)
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/schema.py", line 1882, in encode
    for result in self.iter_encode(obj, path, validation, *args, **kwargs):
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/schema.py", line 1869, in iter_encode
    yield from xsd_element.iter_encode(obj, validation, use_defaults=use_defaults,
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/elements.py", line 910, in iter_encode
    for result in xsd_type.content.iter_encode(element_data, validation, **kwargs):
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/groups.py", line 917, in iter_encode
    yield self.children_validation_error(
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/groups.py", line 242, in children_validation_error
    raise error
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{urn:oasis:names:tc:emergency:cap:1.2}alert' at 0x7f8df8fd9db0> with XsdGroup(model='sequence', occurs=[1, 1]):

Reason: The content of element 'cap:alert' is not complete. Tag 'cap:identifier' expected.

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:sequence>
      <xs:element name="identifier" type="xs:string" />
      <xs:element name="sender" type="xs:string" />
      <xs:element name="sent">
        <xs:simpleType>
          <xs:restriction base="xs:dateTime">
            <xs:pattern value="\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d[-,+]\d\d:\d\d" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="status">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Actual" />
            <xs:enumeration value="Exercise" />
            <xs:enumeration value="System" />
            <xs:enumeration value="Test" />
            <xs:enumeration value="Draft" />
          </xs:restriction>
    ...
    ...
  </xs:complexType>

Instance:

  <cap:alert xmlns:cap="urn:oasis:names:tc:emergency:cap:1.2" />

```

but as you see something is still wrong ...
Could you please give me the original XML sample so I can decode it and check the differences with the JSON produced by on-line tools?

Thanks

**Comment by TonyTNguyen** [comment]
xml_document = """<?xml version="1.0" encoding="utf-8"?>
<alert>
  <identifier>str1234</identifier>
  <sender>str1234</sender>
  <sent>2012-12-13T12:12:12</sent>
  <status>Actual</status>
  <msgType>Alert</msgType>
  <source>str1234</source>
  <scope>Public</scope>
  <restriction>str1234</restriction>
  <addresses>str1234</addresses>
  <code>str1234</code>
  <note>str1234</note>
  <references>str1234</references>
  <incidents>str1234</incidents>
  <info>
    <language>???</language>
    <category>Geo</category>
    <event>str1234</event>
    <responseType>Shelter</responseType>
    <urgency>Immediate</urgency>
    <severity>Extreme</severity>
    <certainty>Observed</certainty>
    <audience>str1234</audience>
    <eventCode>
      <valueName>str1234</valueName>
      <value>str1234</value>
    </eventCode>
    <effective>2012-12-13T12:12:12-05:00</effective>
    <onset>2012-12-13T12:12:12-05:00</onset>
    <expires>2012-12-13T12:12:12-05:00</expires>
    <senderName>str1234</senderName>
    <headline>str1234</headline>
    <description>str1234</description>
    <instruction>str1234</instruction>
    <web>http://www.xsd2xml.com</web>
    <contact>str1234</contact>
    <parameter>
      <valueName>str1234</valueName>
      <value>str1234</value>
    </parameter>
    <resource>
      <resourceDesc>str1234</resourceDesc>
      <mimeType>str1234</mimeType>
      <size>1234</size>
      <uri>http://www.xsd2xml.com</uri>
      <derefUri>str1234</derefUri>
      <digest>str1234</digest>
    </resource>
    <area>
      <areaDesc>str1234</areaDesc>
      <polygon>str1234</polygon>
      <circle>str1234</circle>
      <geocode>
        <valueName>str1234</valueName>
        <value>str1234</value>
      </geocode>
      <altitude>123.45</altitude>
      <ceiling>123.45</ceiling>
    </area>
  </info>
</alert>

**Comment by TonyTNguyen** [comment]
Thank you very much. It's weird that xsd does not accept 1234 as integer. I will look into this after close this issue.
Thank you again

**Comment by brunato** [comment]
In _jsonTxt_  the value is a string: `"size": "1234"`. Then is correct if a validation error is reported. 

In general encode from data/json does not accepts strings in substitution of the right data type. It's permitted only for primitive types that are not decoded for default (eg. binary and datetime types). I don't want to change this default behaviour for datatypes that are available both in Python or in JSON. Maybe i will add an option for encode.

Best regards

**Comment by TonyTNguyen** [comment]
Oh, no. Don't change it. Stick with the spec. "1234" is different with 1234. I realize the issue as soon as I look into it. The online converter did not do a good job.
Another thing on the side that the document on https://xmlschema.readthedocs.io/en/latest/ seem does not seem to have up-to-date information. For example, it does not show the parameter _namespaces_ for .from_json(). Is it fall into kwargs ?

**Comment by brunato** [comment]
> Another thing on the side that the document on https://xmlschema.readthedocs.io/en/latest/ seem does not seem to have up-to-date information. For example, it does not show the parameter _namespaces_ for .from_json(). Is it fall into kwargs ?

Yes, I will change kwargs description to clarify this ...

**Comment by priyatamnano** [comment]
@TonyTNguyen @brunato 

Could you please provide a python script or example which will create the xml from xsd and populate the value from json,??
