### ISSUE TITLE
text_key='$' 

### ISSUE THREAD

**Issue by bjornjorgensen** [sissaschool/xmlschema#242]
Hi again. I am trying to convert tender xml files to json. 
Them I am using are for Norways Doffin.no. They are almost the same as EU TED xml tenders.
Some of this xml files have a lot of <P> 
```
<TITLE_CONTRACT>TITLE TEXT</TITLE_CONTRACT>
						<SHORT_DESCRIPTION_CONTRACT>
							<P>TEXT.</P>
							<P/>
							<P>More TEXT.</P>
						</SHORT_DESCRIPTION_CONTRACT>
```

When I used xmltodict I get only one `SHORT_DESCRIPTION_CONTRACT.P` and the text form all `<P>` come in one list. 

When I 
`jsonString = json.dumps(xmlschema.to_dict(fullname, schema=schema, decimal_type=str, attr_prefix='', text_key='', cdata_prefix= ''),ensure_ascii=False, indent=4)`

I get a list with many dicts and they all have the same key name. And this gives some problems to get the values in these keys. 
https://stackoverflow.com/questions/67097070/remove-list-with-dict-in-pandas

[2016-351047.zip](https://github.com/sissaschool/xmlschema/files/6317886/2016-351047.zip)

**Comment by brunato** [comment]
Hi,
i don't find schema DOFFIN_ESENDERS.xd, could you provide a link or load it into a zip?

About the issue: <P> should be a mixed content complexType so for default generates a dict, but it should be collapsible if there are no attributes.
 
Thanks

**Comment by bjornjorgensen** [comment]
[xsd(1).zip](https://github.com/sissaschool/xmlschema/files/6329013/xsd.1.zip)
Adding the xsd files that I got from doffin.no

**Comment by brunato** [comment]
The right schema for XML case seems to be the v1.0.0.

Anyway examining the case the P's type is a mixed content complex type as expected. Changing the default behavior for a mixed content that contains only text and has no attributes is coherent with similar cases (eg. a simple-content _complexType_ that has declared attributes but the instance has no attributes) so I've decided to accomplish the requested change.

If this change will cause issues to others, I will consider to add an option for this, restoring the old behavior as default.

**Comment by bjornjorgensen** [comment]
ok, thank you very much for your time. shown you release a new update on pip then I will test it.

**Comment by brunato** [comment]
Hi @bjornjorgensen, a new release is available (v1.6.2).

**Comment by bjornjorgensen** [comment]
Now it have been , separated for each P   



`"SHORT_DESCR": {
                            "P": [
                                "Sandefjord kommune skal anskaffe bassengkjemikalier, vannrenseustyr og service på anmodning på renseanlegg for alle basseng i kommunen. Rammeavtalen skal sikre at svømmebassengene til enhver tid har egnet kjemikalier og deler til eksisterende utstyr, for å sikre god vannkvalitet og et rent miljø i bassengene.  For å sikre dette er det også nødvendig med egnet utstyr til vannrensing.  Rammeavtalen skal også dekke service på eksisterende renseanlegg (nærmere beskrivelse følger nedenfor).",
                                "Beskrivelsen av Sandefjord Svømmehall:",
                                "- Antall basseng: 2 (svømmebasseng og terapibasseng)",
                                "- Vannmengde: 1,3 mill. liter.",
                                "Beskrivelse av Skolebasseng:",
                                "- Ranvik, vannmengde:    0,22 mill liter",
                                "- Varden, vannmengde:   0,22 mill liter",
                                "- Andebu, vannmengde:  0,2 mill liter",
                                "- Bokmoa, vannmengde: 0,24 mill liter",
                                "Beskrivelse av terapibasseng:",
                                "SMS (Sandefjord Medisinske Senter)",
                                "- Antall basseng:  1 basseng",
                                "- Vannmengde: 0,13 mill. liter",
                                "Soletunet sykehjem:",
                                "- Antall basseng: 1 basseng",
                                "- Vannmengde: 0,2 mill liter",
                                "Beskrivelse av ønsket årlig service på SMS svømmebasseng:",
                                "Det ønskes ikke tilbud på årlig service.",
                                "Beskrivelse av ønsket årlig service på bassengene i Ranvik skole og Varden ungdomsskole:",
                                "- Kontrollere anleggenes og de enkelte komponenters funksjon, herunder foreta forebyggende vedlikehold.",
                                "- Foreta mindre justeringer som ikke krever nytt materiell eller utskifting av deler og som servicepersonellet kan utføre på stedet.",
                                "- Påvise feil eller mangler og slitasje som krever reparasjon eller bytte av materiell og komme med forslag til forbedrende tiltak. Utbedringer skal utføres så snart som mulig, for å hindre driftsavbrudd.",
                                "Målsetting med anskaffelsen:",
                                "Formålet med anskaffelsen er å sørge for at det til enhver tid er et rent miljø og god vannkvalitet i bassengene.  Anskaffelsen skal fremme et helsevennlig miljø for brukere av bassenget.  Det er også viktig for Oppdragsgiver å ha en leverandør som er samarbeidsvillig og pålitelig."
                            ]
                        },`



I did hope the output can be 

"Sandefjord kommune skal anskaffe bassengkjemikalier, vannrenseustyr og service på anmodning på renseanlegg for alle basseng i kommunen. Rammeavtalen skal sikre at svømmebassengene til enhver tid har egnet kjemikalier og deler til eksisterende utstyr, for å sikre god vannkvalitet og et rent miljø i bassengene.  For å sikre dette er det også nødvendig med egnet utstyr til vannrensing.  Rammeavtalen skal også dekke service på eksisterende renseanlegg (nærmere beskrivelse følger nedenfor). Beskrivelsen av Sandefjord Svømmehall: - Antall basseng: 2 (svømmebasseng og terapibasseng) - Vannmengde: 1,3 mill. liter. Beskrivelse av Skolebasseng: - Ranvik, vannmengde:    0,22 mill liter - Varden, vannmengde:   0,22 mill liter - Andebu, vannmengde:  0,2 mill liter - Bokmoa, vannmengde: 0,24 mill liter Beskrivelse av terapibasseng: SMS (Sandefjord Medisinske Senter) - Antall basseng:  1 basseng - Vannmengde: 0,13 mill. liter Soletunet sykehjem: - Antall basseng: 1 basseng - Vannmengde: 0,2 mill liter Beskrivelse av ønsket årlig service på SMS svømmebasseng: Det ønskes ikke tilbud på årlig service. Beskrivelse av ønsket årlig service på bassengene i Ranvik skole og Varden ungdomsskole: - Kontrollere anleggenes og de enkelte komponenters funksjon, herunder foreta forebyggende vedlikehold. - Foreta mindre justeringer som ikke krever nytt materiell eller utskifting av deler og som servicepersonellet kan utføre på stedet. - Påvise feil eller mangler og slitasje som krever reparasjon eller bytte av materiell og komme med forslag til forbedrende tiltak. Utbedringer skal utføres så snart som mulig, for å hindre driftsavbrudd. Målsetting med anskaffelsen: Formålet med anskaffelsen er å sørge for at det til enhver tid er et rent miljø og god vannkvalitet i bassengene.  Anskaffelsen skal fremme et helsevennlig miljø for brukere av bassenget.  Det er også viktig for Oppdragsgiver å ha en leverandør som er samarbeidsvillig og pålitelig." 


[2_files.zip](https://github.com/sissaschool/xmlschema/files/6416039/2_files.zip)

**Comment by bjornjorgensen** [comment]
I can probably try a re on ", "

**Comment by brunato** [comment]
Hi,
this is not possible to do with the default converter because text is from distinct P tags. You can do this in post-decoding with a join on P list, for example:

```python
'\n'.join(result["SHORT_DESCR"]["P"])  
```

In general automatically merging data from different elements has a little sense because there is a loss of information about the different contents (eg. how to re-encode the merged text?).

**Comment by bjornjorgensen** [comment]
ok, I did run this code on the files and now it looks ok :) 
I well close this case now. 

`def recursive_iter(obj):
    if isinstance(obj, dict):
        for item in obj.values():
            if "P" in obj and isinstance(obj["P"], list):
                obj["P"] = " ".join([str(e) for e in obj["P"]])
            else:
                yield from recursive_iter(item)
    elif any(isinstance(obj, t) for t in (list, tuple)):
        for item in obj:
            yield from recursive_iter(item)
    else:
        yield obj

path = "data/json"

for filename in os.listdir(path):
    if not filename.endswith('.json'):
        continue


    fullname = os.path.join(path, filename)
    with open(fullname, 'r') as f:
        jsonstr = f.read()

    json_sting = json.loads(jsonstr)
    for item in recursive_iter(json_sting):
        json_str2 = json.dumps(json_sting)

    with open(fullname[:-4] + "_stript_list.json", 'w') as f:
        f.write(json_str2)`
