### ISSUE TITLE
Replace xs:sequence with xs:all

### ISSUE THREAD

**Issue by tom62291** [sissaschool/xmlschema#244]
Can I replace xs:sequence with xs:all and build the xml schema object with some pre-processing functions instead of change the raw xsd document?

**Comment by brunato** [comment]
Hi,
no, there is not pre-processing functions for XSD sources, and currently there is not the intention to develop them. 

In general this could be a theme for `XMLResource` class instead of the schema class and maybe it should be implemented through an XSLT.
