### ISSUE TITLE
Unable to retrieve schema structure

### ISSUE THREAD

**Issue by Thomasb81** [sissaschool/xmlschema#254]
Hello

I would expect to use xmlschema to retrieve a structure similar to what could represent xmlspy to depict the xsd schema.
![image](https://user-images.githubusercontent.com/1123617/125696890-6907d2fb-c6a5-465d-9189-84d451493351.png)

But this script is the closest of what I manage to achieve:

schema : [url](http://www.accellera.org/XMLSchema/SPIRIT/1685-2009/)
```

In [1]: import xmlschema
In [2]: my_schema = xmlschema.XMLSchema('1685-2009/schema/index.xsd')
In [3]: component = my_schema.find("//spirit:component")
In [4]: list(component.type.content_type.iter_components((xmlschema.validators.XsdElement,xml
   ...: schema.validators.XsdGroup)))
Out[4]: 
[XsdGroup(model='sequence', occurs=[1, 1]),
 XsdGroup(ref='spirit:versionedIdentifier', model='sequence', occurs=[1, 1]),
 XsdElement(ref='spirit:busInterfaces', occurs=[0, 1]),
 XsdElement(ref='spirit:channels', occurs=[0, 1]),
 XsdElement(ref='spirit:remapStates', occurs=[0, 1]),
 XsdElement(ref='spirit:addressSpaces', occurs=[0, 1]),
 XsdElement(ref='spirit:memoryMaps', occurs=[0, 1]),
 XsdElement(ref='spirit:model', occurs=[0, 1]),
 XsdElement(ref='spirit:componentGenerators', occurs=[0, 1]),
 XsdElement(ref='spirit:choices', occurs=[0, 1]),
 XsdElement(ref='spirit:fileSets', occurs=[0, 1]),
 XsdElement(name='spirit:whiteboxElements', occurs=[0, 1]),
 XsdGroup(model='sequence', occurs=[1, 1]),
 XsdElement(name='spirit:whiteboxElement', occurs=[1, None]),
 XsdElement(name='spirit:cpus', occurs=[0, 1]),
 XsdGroup(model='sequence', occurs=[1, 1]),
 XsdElement(name='spirit:cpu', occurs=[1, None]),
 XsdGroup(model='sequence', occurs=[1, 1]),
 XsdGroup(ref='spirit:nameGroup', model='sequence', occurs=[1, 1]),
 XsdElement(ref='spirit:addressSpaceRef', occurs=[1, None]),
 XsdElement(ref='spirit:parameters', occurs=[0, 1]),
 XsdElement(ref='spirit:vendorExtensions', occurs=[0, 1]),
 XsdElement(name='spirit:otherClockDrivers', occurs=[0, 1]),
 XsdElement(ref='spirit:description', occurs=[0, 1]),
 XsdElement(ref='spirit:parameters', occurs=[0, 1]),
 XsdElement(ref='spirit:vendorExtensions', occurs=[0, 1])]

In [5]: 
```

Is there a method I can use to return a generator with data corresponding to the picture produce by xmlspy ?
I try component.type.content_type.iter_model(), but xsdGroup are replaced by their definition.

**Comment by Thomasb81** [comment]
Should I use iter_model() then on each element iter_ancestor() method ?

**Comment by Thomasb81** [comment]
Ok goit it :
`list(component.type.content_type.elem)`

allows me to retrive the data I need.

**Comment by brunato** [comment]
Hi,
also `list(component.type.content.elem)`, the property `content_type` will be removed in a future release.

**Comment by Thomasb81** [comment]
Hello

Do you plan a replacement ? I mean a different way to access to the information ?

Thomas

**Comment by brunato** [comment]
Not at all, I've only replaced attribute `content_type` with `content` in `XsdComplexType` objects, that should be more clear (content is not necessarily a type, but it can be also a group).
