### ISSUE TITLE
Reorder sequence elements according to xml schema during encoding process

### ISSUE THREAD

**Issue by LinnaViljami** [sissaschool/xmlschema#257]
## Problem description
I have set-up, where I read documents from xml making use of xmlschema library and predefined xsd schema file. I modify decoded documents using python, and then store them to django JSONField (with postgres it uses jsonb field in background). Everything works well, but my database JSON field does not keep the order of elements, and that is why document may not fullfill the schema validation rules after saved and loaded back from database. Problem occurs when there is sequences in xsd schema file.

I have already tried to set unordered=True flag to encoder, which I thought could be possible solution, but still some of my sequence elements are not reordered in proper way. I am not sure if this is just a bug, or have I understood wrong how unordered=True works with encode() function

## Intended action
I would want to be able to reorder (sequence)elements according to my schema during the encoding process, and reconstruct valid xml, after database has reordered some of my elements and reordered elements not anymore fulfilling the sequence rules of xsd file.

**Comment by brunato** [comment]
Hi,

it should be a bug due to a specific schema content model. If you have the opportunity to give me a sample (the schema or a part of it and the JSON data that is not reordered during the encoding) i can try to analyze the case and eventually to fix it.

Thanks

**Comment by LinnaViljami** [comment]
Okay, thanks a lot! I will post an examples: xsd schema document, source xml which fullfills the schema, decoded data, and result that not fulfills the schema due to bad order of sequence elements

**Comment by LinnaViljami** [comment]
So there is xsd schema files, in `exports.py` file there is CDAFI instance which basically constructs schema using xmlschema library:
[xmlschemas.zip](https://github.com/sissaschool/xmlschema/files/7044104/xmlschemas.zip)

Here is my source xml document (uploaded as .txt file because github did not support .xml):
[prescription_example.txt](https://github.com/sissaschool/xmlschema/files/7044234/prescription_example.txt)

When I first decode the file `CDAFI.decode(filename)`, it looks like this:
[decoded.txt](https://github.com/sissaschool/xmlschema/files/7044205/decoded.txt)

**Comment by LinnaViljami** [comment]
Okay I just realized that maybe there is bug in my code, I will update information soon :)

**Comment by brunato** [comment]
Ok, it seems that something fails with reordering using this base content model group:

```xml
<xs:sequence>
<xs:element name="realmCode" type="CS" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="typeId" type="POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
<xs:element name="templateId" type="POCD_MT000040.InfrastructureRoot.templateId" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="id" type="II" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="code" type="CD"/>
<xs:element name="text" type="ED" minOccurs="0"/>
<xs:element name="statusCode" type="CS" minOccurs="0"/>
<xs:element name="effectiveTime" type="IVL_TS" minOccurs="0"/>
<xs:element name="priorityCode" type="CE" minOccurs="0"/>
<xs:element name="languageCode" type="CS" minOccurs="0"/>
<xs:element name="subject" type="POCD_MT000040.Subject" minOccurs="0"/>
<xs:element name="specimen" type="POCD_MT000040.Specimen" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="performer" type="POCD_MT000040.Performer2" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="author" type="POCD_MT000040.Author" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="informant" type="POCD_MT000040.Informant12" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="participant" type="POCD_MT000040.Participant2" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="entryRelationship" type="POCD_MT000040.EntryRelationship" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="reference" type="POCD_MT000040.Reference" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="precondition" type="POCD_MT000040.Precondition" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
```
I will check this starting from _invalid.xml_ data.

**Comment by LinnaViljami** [comment]
Would it be possible to release a new package with this release soon? What is the estimation of the new release date?

**Comment by brunato** [comment]
The new release with a fix for this is now available.
Bye
