### ISSUE TITLE
How to handle xs:choice ?

### ISSUE THREAD

**Issue by leryss** [sissaschool/xmlschema#270]
How can I tell if a bunch of elements are wrapped by an <xs:choice> tag ? When I use XsdElement.iterchildren() it just lists all the child elements, is there a way to figure out a xs:choice group of elements ? I'm trying to generate some random xml data and right now I'm generating all elements wrapped by xs:choice which is not valid.

Also I have an instance where iter_components(XsdAttribute) is returning me some duplicate attributes, right now I'm manually removing the duplicates but I'm wondering what might cause this

Thanks in advance

**Comment by brunato** [comment]
Hi,

each non global element have model group as parent, so you should check this looking if `element.parent.model == 'choice'`. Anyway model groups structure can be very complex and generating a valid content is not simple. 

For doing this try to build a generator function similar to `ModelVisitor.iter_unordered_content()`.

About attributes: attribute groups are not structural in XSD validation so in derivations the base attributes are simply copied, and so when you iterate XsdAttribute components you can find duplicates. Generating duplicates of these attributes have not an impact in validation and only slowing down and augment the memory occupied by the process.

**Comment by leryss** [comment]
Thanks, this answered my questions
