### ISSUE TITLE
Attributes on xs:any elements stripped before element_decode()

### ISSUE THREAD

**Issue by TreyBoudreau** [sissaschool/xmlschema#273]
I have a fragment of XSL that looks like this:

```xml
<xs:element name="someName">
	<xs:complexType>
		<xs:sequence>
			<xs:any processContents="lax" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="x" use="optional" type="xs:ID" />
		<xs:attribute name="y" use="required" type="xs:integer" />
		<xs:attribute name="z" use="optional" type="xs:NCName" />
	</xs:complexType>
</xs:element>
```

and this XML data:

```xml
<someName x="QA01_sequence" y="2500">
	<QA01>
		<qa01_elem01>13</qa01_elem01>
		<qa01_elem02>5139</qa01_elem02>
		<qa01_elem03>170</qa01_elem03>
		<qa01_elem04 these="attributes" get="dropped">0</qa01_elem04>
		<qa01_elem05>56</qa01_elem05>
		<qa01_elem06>11141178</qa01_elem06>
	</QA01>
</someName>
```
When processing the XML via `to_dict()`, none of the attributes covered by the `xs:any` show up.
I presumed that the default encoder just ignored them for some reason, so I hacked up a custom decoder to see what the `ElementData` looks like, and I get this:

```
ed: ElementData(tag='qa01_elem01', text='13', content=None, attributes=[])
ed: ElementData(tag='qa01_elem02', text='5139', content=None, attributes=[])
ed: ElementData(tag='qa01_elem03', text='170', content=None, attributes=[])
ed: ElementData(tag='qa01_elem04', text='0', content=None, attributes=[])
ed: ElementData(tag='qa01_elem05', text='56', content=None, attributes=[])
ed: ElementData(tag='qa01_elem06', text='11141178', content=None, attributes=[])
ed: ElementData(tag='QA01', text=None, content=[('qa01_elem01', '13', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None])), ('qa01_elem02', '5139', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None])), ('qa01_elem03', '170', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None])), ('qa01_elem04', '0', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None])), ('qa01_elem05', '56', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None])), ('qa01_elem06', '11141178', XsdAnyElement(namespace=('##any',), process_contents='lax', occurs=[0, None]))], attributes=[])
```

Specifying `keep_unknown=True` does not affect things, presumably because we've already stripped them before that comes into play.

I'd greatly appreciate any assistance you can provide.

**Comment by TreyBoudreau** [comment]
If I pass `validation='skip'` then I get the attributes!

This implies that `xmlschema` does not consider `<xs:any>` to include attributes associated with the tag-tree. I have yet to find a way to tell it to allow `<xs:anyAttribute processContext="lax"/>` with the `<xs:any>`.

**Comment by TreyBoudreau** [comment]
Using
```xml
<xs:any processContext="skip" .../>
```
causes `xmlschema` to remove the tag-tree entirely. This behavior seems counter-intuitive given `validation="skip"`'s behavior.

**Comment by brunato** [comment]
Hi,
with `processContents="lax"` the validator tries to retrieve and validate the elements but if schema is missing (like in your case) no error is raised. With `processContent="skip"` the content is simply ignored. That attribute is part of the XSD standard but is peculiar for wildcard processing not for the entire schema validation.

The _validation_ parameter applied to another context of the schema is not a part of the XSD standard, but it's defined in similar way to express similar concepts at various stages (schema parsing, validation or decoding). In other parts of the decoding process if you provide `validation='lax'`, invalid values are replaced by `None`, conversely if you provide `validation='skip'` the same invalid values are replaced with the string value. And the choice to not produce any content if the schema is missing and `validation='lax'` is in coherence with that behavior.

**Comment by TreyBoudreau** [comment]
https://www.w3.org/TR/xmlschema-1/#Wildcards describes "lax" as "If the item has a uniquely determined declaration available, it must be ·valid· with respect to that definition, that is, ·validate· if you can, don't worry if you can't."
The choice to throw away otherwise valid XML without generating a warning/exception makes `xmlschema` dangerous to use with `validation="lax"` as it silently destroys data.

A `keep_any` option, defaulting to `False` that kept the discarded tag trees would solve the problem. I want it badly enough that I'll prototype a pull request, if you can suggest where I might make such changes.

**Comment by brunato** [comment]
Hi,

the meaning of `keep_unknown` is explained in #204. If there is a wildcard the decoding is done also for missing elements (with non strict validation). Otherwise unknown data would be kept only if `keep_unknown=True`, as in your case.

But I found a bug in decode/encode methods of XSD wildcards. Some parts already perform decoding as you described, eg.:

```python
                elif validation == 'skip' or self.process_contents == 'lax':
                    yield from self.any_type.iter_decode(obj, validation, **kwargs)
                else:
                    reason = "element %r not found." % obj.tag
                    yield self.validation_error(validation, reason, obj, **kwargs)
```

other parts still not and currently don't produce any decoded data if XSD validator is missing, `validation='lax'` and `processContents='lax'`. I'm going try to fix these methods.

After the fix also the missing attributes (`these="attributes" get="dropped"`) should be decoded in your case (in the schema are covered by the anyAttribute wildcard of the xs:anyType decoder).

Thank you

**Comment by TreyBoudreau** [comment]
Thanks for digging into this. I look forward to testing the fixes.

I took a bit of a tour of the code base whilst digging into the issue, and I've never seen more thoroughly type-hinted code. I didn't even know Python *allowed* type-hints in places `xmlschema` uses them :-) Thanks for teaching me something new!

**Comment by brunato** [comment]
For _xmlschema_ the full inline type hints help to use the library components, put more control for changes and ... helped to find several little bugs :)

About **processContents**: with `processContents='lax'` I will fix adding the missing decoded/encoded parts, but with `processContents='skip'` the related content will remain ignored. Returning values would causes the failure of some W3C tests (cases with `xsi:nil='True'` attribute).

**Comment by brunato** [comment]
Hi,

with release v.1.9.0 the unmatched content, processed with a wildcard that has `processContents='lax'`, is decoded with default decoder (to string values). And this is a choice necessary for avoiding silent discard of unknown data.

Conversely content processed with a wildcard that has `processContents='skip'` is discarded. This behavior  is necessary for compatibility with schema validation in particular cases, but eventually the content could be kept by option (eg. if validation='skip' or with a custom option). 

Any suggestion for these choices?

Thanks

**Comment by TreyBoudreau** [comment]
Howdy,

I installed v.1.9.0 and now I get the attributes when parsing with `validation="strict"`, which solves my problem. I also see that you now support pathlib.Path objects for XMLSourceType: nice.

However, I must apologize, but I don't think I understand your question. Do you mean some kind of option, like `keep_any=True` that overrides the discarding behavior when `processContents='skip'`? If so, I'd think you'd want it to default to `False` for compatibility reasons. And I don't know that I necessarily like the `keep_any` name. Perhaps `keep_skipped_any` or just `keep_skipped`?

Thanks for the quick fix!

**Comment by brunato** [comment]
Yes, an option for `processContents='skip'`. Maybe `process_skipped`, with False as default value. If True the wildcard process the content in the same way that it does when has `processContents='lax'`.
