### ISSUE TITLE
How to find the full schema path of errors?

### ISSUE THREAD

**Issue by barry-gallagher** [sissaschool/xmlschema#275]
Hello, I was investigating your xmlschema module as a possible replacement for PyXB.  So far everything looks good but I am stuck on one last problem.

When I receive an error list back from encode or decode the message is pretty informative about what is wrong in the element but I don't see a way to find the parents of the element having the error all the way back to the root.  I'm attaching a sample I extracted and cut down from our application to illustrate this.  

Basically, in the xml data below (in the attachment) each <ENC> should have three child elements (name, scale and edition).  When I encode the data with 'lax' I get errors saying name and scale is missing from one ENC and scale is missing from another ENC but I don't see how to tell whether the error comes from descriptiveReportSummary/MissingTwo or descriptiveReportSummary/MissingOne.  

Is there a way to find the parents all the way back to the root?  I inspected the data and code and didn't see it although I did see .parent variables that could be traced back but they aren't stored in the Exception instances themselves and seem to be lost.

```xml
<ns1:descriptiveReportSummary >
  <ns1:MissingTwo>
    <ns1:charts>
      <ns1:ENC>
        <!-- How do you tell if which elements had this error: how to get parents from Exception back to the root -->
        <ns2:edition>1</ns2:edition>
      </ns1:ENC>
    </ns1:charts>
  </ns1:MissingTwo>
  <ns1:MissingOne>
    <ns1:charts>
      <ns1:ENC>
        <ns2:name>Hello</ns2:name>
        <ns2:edition>2</ns2:edition>
      </ns1:ENC>
    </ns1:charts>
  </ns1:MissingOne>
</ns1:descriptiveReportSummary>
```

```
failed validating <Element '{http://example.com/2021/02/DR_Summary}ENC' at 0x0000025613369C78> with XsdGroup(model='sequence', occurs=[1, 1]):
Reason: Unexpected child with tag '{http://example.com/2021/02/AllGlobalTypes}edition' at position 1. Tag 'name' expected.
Schema:
  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" name="ENCType">
      <xs:annotation>
          <xs:documentation>Preliminary ENCs have not been reviewed by the Marine Chart Division and should not be used for chart comparison.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
          <xs:element name="name" type="xs:string" />
          <xs:element name="scale" type="xs:positiveInteger" />
          <xs:element name="edition" nillable="true" type="xs:positiveInteger" />
      </xs:sequence>
  </xs:complexType>
Instance:
  <ns0:ENC xmlns="http://example.com/2021/02/AllGlobalTypes" xmlns:ns0="http://example.com/2021/02/DR_Summary">
  <edition>1</edition>
          </ns0:ENC>
```

[error_parents.zip](https://github.com/sissaschool/xmlschema/files/7653131/error_parents.zip)

**Comment by brunato** [comment]
Hi,
encoded data do not have a _source_ (XML resource) so is not possible to get a path. Furthermore a dummy element is used for make raised errors more readable.

For both reasons with 'lax' encoding a path cannot be calculated for the element associated an error. I will improve that adding a dummy XML resource at the end to the reported errors and replacing *elem* on yielded `XMLSchemaChildrenValidation` errors.

Thanks

**Comment by barry-gallagher** [comment]
Thanks for the quick response.  I look forward to trying your improvement.

**Comment by brunato** [comment]
Hi, 
you can try with the new release v1.9.1.

**Comment by barry-gallagher** [comment]
Hello, I see the path is fully qualified in the exception now, that works for me.  Thanks very much.
