### ISSUE TITLE
XMLSchemaParseError: multiple declaration of attribute 'resp' in XML Schema 1.1 file

### ISSUE THREAD

**Issue by yngwi** [sissaschool/xmlschema#276]
Hi,
I'm trying to validate documents against a complex [XML Schema v1.1 file](https://www.monasterium.net/mom/resource/?atomid=tag:www.monasterium.net,2011:/mom/resource/xsd/cei) but I'm getting an error when creating the `XMLSchema11` instance:

```
xmlschema.validators.exceptions.XMLSchemaParseError: multiple declaration of attribute 'resp':

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" mixed="true">
     <xs:attributeGroup ref="lang" />
     <xs:attributeGroup ref="standard" />
     <xs:attributeGroup ref="resp" />
  </xs:complexType>

Path: /xs:schema/xs:element[10]/xs:complexType
```

The file seems to be correct and works fine when using it to validate documents in Oxygen-XML. Any input to what might happen or help me resolve this problem is greatly appreciated.

Best,
Daniel

**Comment by brunato** [comment]
Hi,
this is a bug on parsing schema attributes. The attribute is the same object so in this case shouldn't be considered a duplicate.
I'll put the fix in next bugfix release. Until that you could parse the schema providing `validation='lax'`.

Thank you

**Comment by yngwi** [comment]
Thank you very much, works like a charm!

**Comment by brunato** [comment]
Hi,
with new release v1.9.1 it should work also with default validation mode.

**Comment by yngwi** [comment]
I just tried it, indeed, it works. Thank you for the quick fix.
