### ISSUE TITLE
Is XPath 3.1 in the roadmap?

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [sissaschool/xmlschema#280]
Hi,

I am looking for a python library supporting XPath 3.1. Is XPath 3.1 in the roadmap of this library?

Specifically, what I am trying to achieve is the following:

I have the XML data:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<root>
        <creator>
	        <name>Bob</name>
	        <surname>Marley</surname>
        </creator>
        <creator>
	        <name>Elvis</name>
	        <surname>Presley</surname>
        </creator>
        <id>1234</id>
</root>
```

And the XPath 3.1 expression: `/root/[id,creator/name]`

That should provide the following result: `["1234", ["Bob", "Elvis"]]`

Is it possible to do this with the current state of this library?

Best,
Julián

**Comment by brunato** [comment]
Hi,

the XPath processor is not part of this library but is implemented by the [elementpath](https://github.com/sissaschool/elementpath) package.

The support of XPath 3.1 is in the roadmap. Currently the development of XPath 3.0 is almost completed and I am fixing the code using W3C XP30+ tests (status: 18308 success, 956 failed). Particularly complex is the implementation of the format-* functions, that will also require a clean after tests completion.

After XPath 3.0 the next challenge will be 3.1.

Best wishes
Davide

**Comment by ArenasGuerreroJulian** [comment]
This answers my question :)

Thanks for your work Davide.

Best,
Julián
