### ISSUE TITLE
Attribute order in error message using tox

### ISSUE THREAD

**Issue by Naruto0** [sissaschool/xmlschema#281]
version: xmlschema==1.9.2
tox==3.24.5

Issue:
When running simply with pytest (no environment fiddling) the element is unchanged in error message:
```(Pdb) str(e.value)
'failed validating \'icmp\' with XsdEnumerationFacets([\'tcp\', \'udp\']):\n\nReason: attribute protoname=\'icmp\': value must be one of [\'tcp\', \'udp\']\n\nSchema:\n\n  <xs:enumeration xmlns:xs="http://www.w3.org/2001/XMLSchema" value="tcp" />\n\nInstance:\n\n  <layer4 protonum="1" protoname="icmp" />\n\nPath: /flow/meta[1]/layer4\n'
```
Sot he element ``<layer4 protonum="1" protoname="icmp"></layer4>`` seems in correct order

however with `tox` the error is following:
```
(Pdb) str(e.value)
'failed validating \'icmp\' with XsdEnumerationFacets([\'tcp\', \'udp\']):\n\nReason: attribute protoname=\'icmp\': value must be one of [\'tcp\', \'udp\']\n\nSchema:\n\n  <xs:enumeration xmlns:xs="http://www.w3.org/2001/XMLSchema" value="tcp" />\n\nInstance:\n\n  <layer4 protoname="icmp" protonum="1" />\n\nPath: /flow/meta[1]/layer4\n'
```
so it fails to assert on whole error string. It is not an issue for me, as I can test it solely on `reason` attribute of raised `XMLValidationError`.

I wonder if anyone have ran to similar issue as I did, or if it is just incompatibility of modules.

**Comment by brunato** [comment]
Hi,

the error messages seems to be identical to me. The error is related to an invalid value in attribute protoname, not with element order. To check this is better if you provide the schema (or the part related with the error) and a sample instance.

Thank you

**Comment by brunato** [comment]
If you refer to order of attribute names in error message it could depends on Python version or libraries used (if you use lxml for example), so try to check if there are differences.

**Comment by brunato** [comment]
Release v1.10.0 is out. 

Without further info on this I can't check where is the *issue* (if it is due to this library or to infrastructure).
I close the issue, you can reopen it with other details if you want.

Cheers

**Comment by Naruto0** [comment]
Sure, I don't mind, Sorry for late response.
