### ISSUE TITLE
Add sourceline during  parsing

### ISSUE THREAD

**Issue by hcw70** [sissaschool/xmlschema#283]
When parsing xml documents, lxml reports thw current xml line number via https://lxml.de/api/lxml.etree._Element-class.html in attribute "sourceLine".

I would like to have that attribute also be available as an attribute of the resulting document after

`xmlschema.XmlDocument()
`
so my parsed XML instance knows for each element in the document its type and the source location.

**Comment by brunato** [comment]
Hi,

an _XmlDocument_ object is an _XMLResource_ instance with an optional schema and other methods. If you provide an XML root parsed with lxml for building an XmlDocument, the elements inside are lxml's elements with sourceline attributes.

Is this what you intended?

**Comment by brunato** [comment]
Close for lacking of feedback, reopen if needed.
