### ISSUE TITLE
Security vulnerability on schema validation - read arbitrary local file.

### ISSUE THREAD

**Issue by jakub-m** [sissaschool/xmlschema#284]
Hi,

I might have found a security vulnerability, please confirm. The vulnerability allows reading an arbitrary local file. The content of the file is then included in an error message. If `xmlschema` is used in a web service, the error message, together with the content of the local file, could be potentially returned to an adversary remote caller.

The mechanism is as follows:

1. A web service uses `XMLSchema.validate` to validate arbitrary input XML.
2. The input XML is not an XML but a path to a local file.
3. [xmlschema/resources.py][ref_py1] reads the local file, fails to parse it as XML and returns the file content in `ParseError`.

[ref_py1]:https://github.com/sissaschool/xmlschema/blob/847ead0540c58390efb95b2024eda120eb535ef1/xmlschema/resources.py#L759

An example (pseudo code compiled from actual larger example):

```
schema: xmlschema.XMLSchema = ... # some XML schema that I validate the input with.
xml_body = "/etc/timezone" # offending remote input
schema.validate(xml_body)
```

The resulting stack trace. note `data` in `ParseError` holding content of the local file:

```
/usr/local/lib/python3.7/site-packages/xmlschema/validators/schemas.py:1677: in validate
    namespaces, max_depth, extra_validator):
/usr/local/lib/python3.7/site-packages/xmlschema/validators/schemas.py:1711: in iter_errors
    resource = XMLResource(source, defuse=self.defuse, timeout=self.timeout)
/usr/local/lib/python3.7/site-packages/xmlschema/resources.py:508: in __init__
    self.parse(source, lazy)
/usr/local/lib/python3.7/site-packages/xmlschema/resources.py:742: in parse
    with urlopen(url, timeout=self._timeout) as resource:
/usr/local/lib/python3.7/urllib/request.py:222: in urlopen
    return opener.open(url, data, timeout)
/usr/local/lib/python3.7/urllib/request.py:525: in open
    response = self._open(req, data)
/usr/local/lib/python3.7/urllib/request.py:543: in _open
    '_open', req)
/usr/local/lib/python3.7/urllib/request.py:503: in _call_chain
    result = func(*args)
/usr/local/lib/python3.7/urllib/request.py:1451: in file_open
    return self.open_local_file(req)

(...)

self = <xml.etree.ElementTree.XMLPullParser object at 0x7f1248878f60>
data = b'Etc/UTC\n'

    def feed(self, data):
        """Feed encoded data to parser."""
        if self._parser is None:
            raise ValueError("feed() called after end of stream")
        if data:
            try:
>               self._parser.feed(data)
E                 File "<string>", line None
E               xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 3

/usr/local/lib/python3.7/xml/etree/ElementTree.py:1269: ParseError
```

**Comment by brunato** [comment]
Hi,

within new release v1.10.0 there is a new option 'nonlocal' for the argument *defuse* and a new option 'none' for the argument *allow*  (XMLResource and also for schema classes and schema validation API).

For your case you can use `defuse='always'` and `allow='none'`.

Please confirm if these options resolve reported security vulnerability and if so then close this ticket.

Best regards

**Comment by jakub-m** [comment]
Thanks @brunato for the prompt response (and sorry for myself lagging)! I will check your suggestions and will come back if I have any other questions. For now, I close the issue.

Best,
J
