### ISSUE TITLE
Does the method from_json deserialize JSON to XML while ordering elements against schema?

### ISSUE THREAD

**Issue by mariocampacci** [sissaschool/xmlschema#294]
Cannot understand if the method xmlschema.from_json is supposed to keep the XML elements in the order dictated by the schema.

I am able to generate the XML only by skipping the validation but then it does not validate against the schema because the elements are not in the correct order.
If validation="lax" is passed it indicates some errors that can be interpreted as wrong XML elements order.
Does the method need the JSON or dictionary to be pre ordered?

Is the XSD passed used for validation purposes only?

Cheers,

Mario

**Comment by brunato** [comment]
Hi,

you can provide argument `converter=xmlschema.UnorderedConverter` to _from_json_. In alternative provide `unordered=True` that applies to the default converter. 

The two options should be equivalent, let me know if the behavior is different for your case.

thank you

**Comment by mariocampacci** [comment]
Thank you @brunato! 
Adding `unordered=True`  did the trick. 

Cheers,

Mario
