### ISSUE TITLE
use of auto generated binding classes 

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#300]
Hello
There is a get_binding method in the Xsd Element class which returns the self.binding attribute  if it exists or creates one if it does not exist.
This attribute does not seem to be initialized.
I created it after creating the schema and importing the module of auto generated bindings. However the get_binding_method of the class Xsd_element recreates a binding class if replace_existing is False.Is this on purpose?

**Comment by brunato** [comment]
Hi,
this should be a typo, the test need to be changed to:

```python
if self.binding is None or replace_existing:
```

thank you!

**Comment by brunato** [comment]
Fix available with release v1.11.2
