### ISSUE TITLE
questions about encoding of hierarchical data

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#301]
I have a hierarchical data structure described with a schema and I need to encode it in XML. I am trying to figure out how to use the schema. iter_encode and xsd_element.iter_encode methods to create a tree of dataelements objects.

I am trying to writer a custom converter.encode method but I cannot figure out what to put in the Data_element.Content so that the next round of the iterator can create the dataelements for the children?

**Comment by brunato** [comment]
Hi,
i think that you can create the XML with `encode/iter_encode` and then use `to_objects()` or `decode/iter_encode` with `DataBindingConverter/DataElementConverter` to create the tree of dataelements objects.

**Comment by piscvau** [comment]
Thank you for your answer. My problem is to use iter_encode or encode and to find the children in my data hierarchy to get the data values. Are you suggesting to use to_objects before filling the DataElement with its content?
I tried he DataElementConverter. But I need to fill in the content of dataelement at level n with the DataElement of the children.
I tried the default converter but this seems to be made for mutable mapping.
Should I write my own converter from the default converter with ElementData?  
Or should I use the package only for validating a ElementTree that I created without using the package?

**Comment by brunato** [comment]
You can create dataelements tree only starting from XML data. Essentially:

```python
  datatree = schema.to_objects(xml_data)
```

or using the decode call:

```python
  datatree = schema.decode(xml_data, converter=DataElementConverter)
```

Each data element has a decoded _value_ attribute (possibly `None`) 
The _xml_data_ can be a file path, a string containing the XML data, or an element tree instance (in this case with the limitation of namespace map if you use stdlib ElementTree library).

**Comment by piscvau** [comment]
If others are getting into this question : overriding the element_encode method of the default converter to return an ElementData whose content is a list of the children, each child being described by a tuple (one tuple for each child) each tuple including (name, and child object)
