### ISSUE TITLE
How i can validate soap XML? 

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#307]
Hi ,
when i am validating with soap xml with xsd , i am getting the below errors.
ERRORS: 
Reason: <Element '{http://schemas.xmlsoap.org/soap/envelope/}Body' at 0x7fb8009efe00> is not an element of the schema

How i can validate with the nampspace attributes ignoring the xlmns attributes ?

Need immediate help 

@jayvdb @bdauvergne @fabaff @jmuhlich @gaborbernat

**Comment by priyatamnano** [comment]
xsd = xmlschema.XMLSchema(SCHEMA_PATH)
if xsd.is_valid(XML_PATH, namespaces={"xmlns:soapenv": "http://schemas.xmlsoap.org/soap/envelope/"}):
    print("XML is valid")
else:
    print("XML is not valid")
print(xsd.validate(XML_PATH))

Am still getting the below errors, could you please help me

EERORS:

Traceback (most recent call last):
  File "xml_validation.py", line 36, in <module>
    print(xsd.validate(XML_PATH))
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 1694, in validate
    raise error
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{http://schemas.xmlsoap.org/soap/envelope/}Body' at 0x7f8ee09b0e00> with XMLSchema10(name='suncorp.xsd', namespace='urn:ais:schema:theme:lo:su:SubmitSLNApplication'):

Reason: <Element '{http://schemas.xmlsoap.org/soap/envelope/}Body' at 0x7f8ee09b0e00> is not an element of the schema

Instance:

  <soapenv:Body xmlns:ns1="urn:ais:schema:theme:lo:su:SubmitSLNApplication" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">

**Comment by priyatamnano** [comment]
Did not get you, let me share the xsd and xml file to you.
Could you please share your personal email. I really need your help.

Xml
<soapenv:Body xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:nik-com-au:wmb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<ns0:ApplicationBatch xmlns:ns0="urn:ais:schema:banking:loans:nik:SubmitSLNApplication" NumberOfApplications="1" ProductionData="No">
<ns0:Identifier UniqueID="1035853-SUN" Type="BrokerAssigned"/>


xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    targetNamespace="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="AccountNumber">
        <xs:complexType>


Many thanks
From: Davide Brunato ***@***.***>
Date: Thursday, 16 June 2022 at 10:11 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I see that the schema is in a specific namespace:

XMLSchema10(name='su.xsd', namespace='urn:ais:schema:banking:loans:loan:SubmitSLNApplication')

Having your loaded schema:

xsd = xmlschema.XMLSchema(SCHEMA_PATH)

the namespace "http://schemas.xmlsoap.org/soap/envelope/" has to be loaded by an import (check in the namespace URI is in xsd.maps.namespaces). If it's not you have to provide an import in one of the XSD source files that are loaded with your schema (read XSD standard for this) or imported manually with xsd.import_schema API.

**Comment by priyatamnano** [comment]
Please find the attachment for xsd and xml

From: Priyatam Nayak ***@***.***>
Date: Thursday, 16 June 2022 at 10:20 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Did not get you, let me share the xsd and xml file to you.
Could you please share your personal email. I really need your help.

Xml
<soapenv:Body xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:nik-com-au:wmb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<ns0:ApplicationBatch xmlns:ns0="urn:ais:schema:banking:loans:nik:SubmitSLNApplication" NumberOfApplications="1" ProductionData="No">
<ns0:Identifier UniqueID="1035853-SUN" Type="BrokerAssigned"/>


xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    targetNamespace="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="AccountNumber">
        <xs:complexType>


Many thanks
From: Davide Brunato ***@***.***>
Date: Thursday, 16 June 2022 at 10:11 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I see that the schema is in a specific namespace:

XMLSchema10(name='su.xsd', namespace='urn:ais:schema:banking:loans:loan:SubmitSLNApplication')

Having your loaded schema:

xsd = xmlschema.XMLSchema(SCHEMA_PATH)

the namespace "http://schemas.xmlsoap.org/soap/envelope/" has to be loaded by an import (check in the namespace URI is in xsd.maps.namespaces). If it's not you have to provide an import in one of the XSD source files that are loaded with your schema (read XSD standard for this) or imported manually with xsd.import_schema API.

**Comment by priyatamnano** [comment]
Are you able to solve the issue?

Many thanks
Priyatam

From: Priyatam Nayak ***@***.***>
Date: Thursday, 16 June 2022 at 11:11 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
Please find the attachment for xsd and xml

From: Priyatam Nayak ***@***.***>
Date: Thursday, 16 June 2022 at 10:20 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Did not get you, let me share the xsd and xml file to you.
Could you please share your personal email. I really need your help.

Xml
<soapenv:Body xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:nik-com-au:wmb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<ns0:ApplicationBatch xmlns:ns0="urn:ais:schema:banking:loans:nik:SubmitSLNApplication" NumberOfApplications="1" ProductionData="No">
<ns0:Identifier UniqueID="1035853-SUN" Type="BrokerAssigned"/>


xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    targetNamespace="urn:ais:schema:banking:loans:nik:SubmitSLNApplication"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="AccountNumber">
        <xs:complexType>


Many thanks
From: Davide Brunato ***@***.***>
Date: Thursday, 16 June 2022 at 10:11 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I see that the schema is in a specific namespace:

XMLSchema10(name='su.xsd', namespace='urn:ais:schema:banking:loans:loan:SubmitSLNApplication')

Having your loaded schema:

xsd = xmlschema.XMLSchema(SCHEMA_PATH)

the namespace "http://schemas.xmlsoap.org/soap/envelope/" has to be loaded by an import (check in the namespace URI is in xsd.maps.namespaces). If it's not you have to provide an import in one of the XSD source files that are loaded with your schema (read XSD standard for this) or imported manually with xsd.import_schema API.

**Comment by brunato** [comment]
Hi,
i don't think this can be an issue of the library, but a missing schema case.

> Please find the attachment for xsd and xml

Attach your XSDs and an XML sample (using a ZIP archive) if you want this case to be examined.

Best regards

**Comment by priyatamnano** [comment]
[data.zip](https://github.com/sissaschool/xmlschema/files/8925562/data.zip)
Please find the attachment for xsd and xml
Thanks

@brunato

**Comment by brunato** [comment]
I give you a recipe for building the complete schema and then validate it:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema("nik.xsd")
>>> schema.is_valid("nik.xml")
False
>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)      
XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')
>>> schema.is_valid("nik.xml")
True
```

another method is to provide explicit locations when you create the schema instance:

```pycon
>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}
>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)
>>> schema.is_valid("nik.xml")
True
```

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by priyatamnano** [comment]
Thank you so much for your solution,
But am getting the below error when am trying the first solution
From: Davide Brunato ***@***.***>
Date: Friday, 17 June 2022 at 9:52 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I give you a recipe for building the complete schema and then validate it:

>>> import xmlschema

>>> schema = xmlschema.XMLSchema("nik.xsd")

>>> schema.is_valid("nik.xml")

False

>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)

XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')

>>> schema.is_valid("nik.xml")

True

another method is to provide explicit locations when you create the schema instance:

>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}

>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)

>>> schema.is_valid("nik.xml")

True

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by priyatamnano** [comment]
File "xml_validation.py", line 40, in <module>
    schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 1365, in import_schema
    schema_url = fetch_resource(location, base_url)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/resources.py", line 348, in fetch_resource
    raise XMLResourceError(msg % {'url': url, 'reason': err.reason})
xmlschema.exceptions.XMLResourceError: cannot access to resource 'https://schemas.xmlsoap.org/soap/envelope/': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Thank you so much for your solution,
But am getting the below error when am trying the first solution
From: Davide Brunato ***@***.***>
Date: Friday, 17 June 2022 at 9:52 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I give you a recipe for building the complete schema and then validate it:

>>> import xmlschema

>>> schema = xmlschema.XMLSchema("nik.xsd")

>>> schema.is_valid("nik.xml")

False

>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)

XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')

>>> schema.is_valid("nik.xml")

True

another method is to provide explicit locations when you create the schema instance:

>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}

>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)

>>> schema.is_valid("nik.xml")

True

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by brunato** [comment]
It is an SSL error, dowload the soapenv schema usig a browser and then provide a local filepath.

**Comment by priyatamnano** [comment]
How to solve for to_json api ?

xmlschema.to_json(xml_document=default_storage.open(xml_path).read(),schema=default_storage.open(f'{BASE_LIXI_PATH}/{partner_name}/schema/{partner_name.lower()}.xsd'),process_namespaces="http://schemas.xmlsoap.org/soap/envelope/")
*** xmlschema.exceptions.XMLSchemaKeyError: "the namespace 'http://schemas.xmlsoap.org/soap/envelope/' is not loaded"

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
  File "xml_validation.py", line 40, in <module>
    schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 1365, in import_schema
    schema_url = fetch_resource(location, base_url)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/resources.py", line 348, in fetch_resource
    raise XMLResourceError(msg % {'url': url, 'reason': err.reason})
xmlschema.exceptions.XMLResourceError: cannot access to resource 'https://schemas.xmlsoap.org/soap/envelope/': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Thank you so much for your solution,
But am getting the below error when am trying the first solution
From: Davide Brunato ***@***.***>
Date: Friday, 17 June 2022 at 9:52 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I give you a recipe for building the complete schema and then validate it:

>>> import xmlschema

>>> schema = xmlschema.XMLSchema("nik.xsd")

>>> schema.is_valid("nik.xml")

False

>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)

XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')

>>> schema.is_valid("nik.xml")

True

another method is to provide explicit locations when you create the schema instance:

>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}

>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)

>>> schema.is_valid("nik.xml")

True

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by priyatamnano** [comment]
Issue solved. But for the from_json , it is not working properly.

json_object = xmlschema.to_json(xml_document=default_storage.open(xml_path).read(),schema=default_storage.open(f'{BASE_LIXI_PATH}/{partner_name}/schema/{partner_name.lower()}.xsd'),locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"})
# To convert to xml

#print(xmlschema.from_json(json_object, schema=schema))

what will be the value for schema option?
From: Priyatam Nayak ***@***.***>
Date: Sunday, 19 June 2022 at 4:09 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
How to solve for to_json api ?

xmlschema.to_json(xml_document=default_storage.open(xml_path).read(),schema=default_storage.open(f'{BASE_LIXI_PATH}/{partner_name}/schema/{partner_name.lower()}.xsd'),process_namespaces="http://schemas.xmlsoap.org/soap/envelope/")
*** xmlschema.exceptions.XMLSchemaKeyError: "the namespace 'http://schemas.xmlsoap.org/soap/envelope/' is not loaded"

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
  File "xml_validation.py", line 40, in <module>
    schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 1365, in import_schema
    schema_url = fetch_resource(location, base_url)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/resources.py", line 348, in fetch_resource
    raise XMLResourceError(msg % {'url': url, 'reason': err.reason})
xmlschema.exceptions.XMLResourceError: cannot access to resource 'https://schemas.xmlsoap.org/soap/envelope/': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Thank you so much for your solution,
But am getting the below error when am trying the first solution
From: Davide Brunato ***@***.***>
Date: Friday, 17 June 2022 at 9:52 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I give you a recipe for building the complete schema and then validate it:

>>> import xmlschema

>>> schema = xmlschema.XMLSchema("nik.xsd")

>>> schema.is_valid("nik.xml")

False

>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)

XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')

>>> schema.is_valid("nik.xml")

True

another method is to provide explicit locations when you create the schema instance:

>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}

>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)

>>> schema.is_valid("nik.xml")

True

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by priyatamnano** [comment]
Sorry,
  What should be the path value ?

Reason: unable to select an element for decoding data, provide a valid 'path' argument.
(Pdb) xmlschema.from_json(source=json_object, schema=schema)

From: Priyatam Nayak ***@***.***>
Date: Sunday, 19 June 2022 at 4:34 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
Issue solved. But for the from_json , it is not working properly.

json_object = xmlschema.to_json(xml_document=default_storage.open(xml_path).read(),schema=default_storage.open(f'{BASE_LIXI_PATH}/{partner_name}/schema/{partner_name.lower()}.xsd'),locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"})
# To convert to xml

#print(xmlschema.from_json(json_object, schema=schema))

what will be the value for schema option?
From: Priyatam Nayak ***@***.***>
Date: Sunday, 19 June 2022 at 4:09 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
How to solve for to_json api ?

xmlschema.to_json(xml_document=default_storage.open(xml_path).read(),schema=default_storage.open(f'{BASE_LIXI_PATH}/{partner_name}/schema/{partner_name.lower()}.xsd'),process_namespaces="http://schemas.xmlsoap.org/soap/envelope/")
*** xmlschema.exceptions.XMLSchemaKeyError: "the namespace 'http://schemas.xmlsoap.org/soap/envelope/' is not loaded"

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)
  File "xml_validation.py", line 40, in <module>
    schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 1365, in import_schema
    schema_url = fetch_resource(location, base_url)
  File "/Users/priyatamnayak/Repository/soap_python_test/venv/lib/python3.8/site-packages/xmlschema/resources.py", line 348, in fetch_resource
    raise XMLResourceError(msg % {'url': url, 'reason': err.reason})
xmlschema.exceptions.XMLResourceError: cannot access to resource 'https://schemas.xmlsoap.org/soap/envelope/': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

From: Priyatam Nayak ***@***.***>
Date: Friday, 17 June 2022 at 10:16 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

Thank you so much for your solution,
But am getting the below error when am trying the first solution
From: Davide Brunato ***@***.***>
Date: Friday, 17 June 2022 at 9:52 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] How i can validate soap XML? (Issue #307)

I give you a recipe for building the complete schema and then validate it:

>>> import xmlschema

>>> schema = xmlschema.XMLSchema("nik.xsd")

>>> schema.is_valid("nik.xml")

False

>>> schema.import_schema(namespace="http://schemas.xmlsoap.org/soap/envelope/", location="https://schemas.xmlsoap.org/soap/envelope/", build=True)

XMLSchema10(name='', namespace='http://schemas.xmlsoap.org/soap/envelope/')

>>> schema.is_valid("nik.xml")

True

another method is to provide explicit locations when you create the schema instance:

>>> locations = {"http://schemas.xmlsoap.org/soap/envelope/": "https://schemas.xmlsoap.org/soap/envelope/"}

>>> schema = xmlschema.XMLSchema("nik.xsd", locations=locations)

>>> schema.is_valid("nik.xml")

True

P.S.: in both cases is better if you download the soapenv schema and then provide a local filepath.

Best regards

**Comment by brunato** [comment]
There is a documentation for [from_json API](https://xmlschema.readthedocs.io/en/latest/api.html?highlight=from_json#xmlschema.from_json) that should be sufficient to explain this.

P.S.: I'm the maintainer of this package, not a consultant for XSD and XML.

Best regards

**Comment by priyatamnano** [comment]
cannot access to resource 'http://schemas.xmlsoap.org/soap/envelope/': Forbidden

How can i give local path for http://schemas.xmlsoap.org/soap/envelope/" ?

@brunato

**Comment by bdauvergne** [comment]
Please stop harassing @brunato, you questions are not related to the xmlschema package.
