### ISSUE TITLE
 assertion not evaluating to False

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#308]
in the following xsd model the assertion with id = "test-nexts" does not create an error when validating the instance with invalid part number 25. Does this come from the assertion or is this a bug?
Here is the instance  :
`<ns0:kPartModel xmlns:ns0="http://www.ludd21.com/kPartModel" >
    <ns0:kPartsPiece pieceName="pieceknit_layer1">
        <ns0:kPartsList>
            <ns0:castOnPartSeg nextsnum="1 25" partNumber="0" heightd="11.82912">
                <ns0:baseSeg start="9.73143 0.00000" end="17.73188 0.00000" />
            </ns0:castOnPartSeg>
            <ns0:joinPart nextsnum="3" previousnum="0 2" partNumber="1" heightd="8.08932">
                <ns0:baseSeg start="9.88173 -11.82912" end="25.27907 -11.82912" />
            </ns0:joinPart>
            <ns0:castOffPartPoint previousnum="1" partNumber="2" heightd="0">
                <ns0:basePoint start="21.83789 -8.02031" />
            </ns0:castOffPartPoint>
        </ns0:kPartsList>
    </ns0:kPartsPiece>
</ns0:kPartModel>

here is the xsd:

`<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace = "http://www.ludd21.com/kPartModel"
xmlns = "http://www.ludd21.com/kPartModel"
elementFormDefault="qualified"
xpathDefaultNamespace= "http://www.ludd21.com/kPartModel"
>
  
    <xs:element name="kPartModel">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="kPartsPiece"  minOccurs="1" maxOccurs = "unbounded"/>
        </xs:sequence>
      </xs:complexType>
       
      <xs:unique name= "kPartModel">
            <xs:selector xpath="*"/>
            <xs:field xpath= "@pieceName"/>
          </xs:unique>
    </xs:element>
    
    <xs:element name="kPartsPiece">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref= "kPartsList"/>
          </xs:sequence>         
          <xs:attribute name="pieceName" type="xs:NCName"/>
         
         <xs:assert id = "test-nexts" test = "every $x in data(kPartsList/*/@nextsnums) satisfies some $part in kPartsList/* satisfies $part/@partNumber = $x"/>        </xs:complexType>
        
        <xs:unique name= "kPartsList">
          <xs:selector xpath="*/*"/>
          <xs:field xpath= "@partNumber"/>
        </xs:unique>
    </xs:element>
  
    <xs:element name = "kPartsList" >
      <xs:complexType>
        <xs:sequence>
          <xs:choice >
            <xs:element ref = "castOnPartSeg"/>
            <xs:element ref = "castOnPartPoint"/>
          </xs:choice>
          <xs:choice  minOccurs= "0" maxOccurs = "unbounded">
            <xs:element ref = "castOnPartSeg" />
            <xs:element ref = "castOnPartPoint" />
            <xs:element ref = "castOffPartSeg" />
            <xs:element ref = "castOffPartPoint"/>
            <xs:element ref = "joinPart"/>
            <xs:element ref = "splitPart" />
            <xs:element ref = "segSplitPart"/>  
          </xs:choice>
        </xs:sequence>
        
      </xs:complexType>      
      </xs:element>
    
    <xs:element name="castOnPartPoint">
      <xs:complexType>
        <xs:sequence>
           <xs:element ref ="basePoint"/>
         </xs:sequence>
         <xs:attribute name ="nextsnum" type = "kpRefsList" use = "required"/>
         <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
         <xs:attribute name = "heightd" type = "decimal5digits" use = "required"/>
      </xs:complexType>
    </xs:element>
      
    <xs:element name="castOnPartSeg">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref ="baseSeg"/>          
        </xs:sequence>
        <xs:attribute name = "nextsnum"  type = "kpRefsList" use = "required"/>
        <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
        <xs:attribute name = "heightd" type = "decimal5digits" use = "required"/>
      </xs:complexType>
    </xs:element>

    
    <xs:element name="castOffPartPoint">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref ="basePoint"/>
        </xs:sequence>
         <xs:attribute name ="previousnum" type = "kpRefsList" use = "required"/> 
        <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
        <xs:attribute name = "heightd" type = "decimal5digits" fixed = "0" use = "required"/>
      </xs:complexType>
    </xs:element>
    
    
    <xs:element name="castOffPartSeg">
     <xs:complexType>
        <xs:sequence>
          <xs:element ref ="baseSeg"/>          
        </xs:sequence>
        <xs:attribute name ="previousnum" type = "kpRefsList" use = "required"/> 
        <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
        <xs:attribute name = "heightd" type = "decimal5digits" fixed="0" use = "required"/>
      </xs:complexType> 
    </xs:element>

    
    <xs:element name="splitPart">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref ="baseSeg"/>          
        </xs:sequence>
        <xs:attribute name ="previousnum" type = "kpRefsList" use = "required"/> 
        <xs:attribute name ="nextsnum" type = "kpRefsList" use = "required"/>
        <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
        <xs:attribute name = "heightd" type = "decimal5digits" use = "required"/>
      </xs:complexType>
    </xs:element>
    
    <xs:element name="segSplitPart">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref ="baseSeg"/>
        </xs:sequence>
        <xs:attribute name ="previousnum"  type = "kpRefsList" use = "required"/>        
        <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
        <xs:attribute name = "heightd" type = "decimal5digits" fixed= "0" use = "required"/>       
      </xs:complexType>
    </xs:element>
    
    <xs:element name="joinPart">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref ="baseSeg"/>
        </xs:sequence>
      <xs:attribute name ="nextsnum"  type = "kpRefsList" use = "required"/>   
      <xs:attribute name ="previousnum" type = "kpRefsListmin2" use = "required"/>
       <xs:attribute name = "partNumber" type = "xs:nonNegativeInteger" use = "required"/>
       <xs:attribute name = "heightd" type = "decimal5digits" use = "required"/>      
      </xs:complexType>
    </xs:element>

    <xs:simpleType name = "kpRefsList">
        <xs:list itemType= "xs:nonNegativeInteger"/>
    </xs:simpleType>
    
    <xs:simpleType name="kpRefsListmin2"> 
        <xs:restriction base = "kpRefsList"> 
        <xs:minLength value = "2"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:element name = "basePoint">
      <xs:complexType>
        <xs:attribute name= "start" type = "point" use = "required"/>
      </xs:complexType>
    </xs:element>
    
    
    <xs:element name = "baseSeg">
      <xs:complexType>
        <xs:attribute name= "start" type = "point" use = "required"/>
        <xs:attribute name= "end" type = "point" use = "required"/>
        
        
      </xs:complexType>
    </xs:element>
    
    
    <xs:simpleType name= "point">
        <xs:restriction>
          <xs:simpleType>
            <xs:list itemType = "decimal5digits"/>
          </xs:simpleType>
          <xs:length value = "2"/>
        </xs:restriction>
    </xs:simpleType>
   
    <xs:simpleType name ="decimal5digits">
        <xs:restriction base = "xs:decimal">
            <xs:fractionDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>
`
`

**Comment by piscvau** [comment]
A typo error in the XPath expression which refers to a non existing attribute. No error nor warning is given by element_path and the assertion is considered True.

**Comment by brunato** [comment]
Hi,
the XML instance and schema you posted above are valid with XSD 1.1 ...

**Comment by piscvau** [comment]
In the assertion test-nexts the @nextnums refers to an attribute which does not exist .The name of the attribute is nextnum.
I would have liked to have a warning, because it took me a very long time to see it.!.......
In issue 310 I included a test which reproduces this behavior.

**Comment by brunato** [comment]
This is the behavior expected by the XPath standard.
