### ISSUE TITLE
Xml with schema validation is failing due to "&" present in xml attribute value

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#309]
Xml with schema validation is failing due to "&" present in xml attribute value

File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1274, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 460, column 38

@gaborbernat

**Comment by brunato** [comment]
Hi, 
this is a wrong XML data, as the traceback shown clearly. Check your XML data with `xml.etree.ElementTree` before create an issue and please don't continue to tag other people for problems that not involve them.

Thank you

**Comment by priyatamnano** [comment]
NO ,the attribute contains & value (like a & b company )
How it is wrong ?
Value can be any characters?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by priyatamnano** [comment]
NO ,the attribute contains & value (like a & b company )
How it is wrong ?
Value can be any characters?

<ns0:CompanyName BusinessName="HAINS & CO PTY LTD"/>





[@brunato](https://github.com/brunato)

**Comment by brunato** [comment]
Maybe you missing to use the appropriate XML declaration into your XML data. 

See https://www.w3resource.com/xml/declarations.php.

Check the XML data with `xml.etree.ElementTree` or `lxml.etree`.

__But in any case this is not an issue of this library__.
