### ISSUE TITLE
wrong attributes in the exception raised by validation errors for unique and XPath assertions 

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#310]
Because I am a beginner in xPath and xml  I have been writing systematic tests of error cases for my application. 
The XML schema package raises validation errors with wrong information in the arguments of the XMLSchemaValidationError.
Here is set of files including unittest Cases and xml files  that can reproduce some of the problems I encountered.
Also as indicated in issue number 308 nor error is detected in xPath Expression which refer to non existing attribute which does not help beginners like me.
Below is a .tar.gz file renamed with .zip including the 2 tests toreproduce the issue;
[issue.tar.gz.zip](https://github.com/sissaschool/xmlschema/files/8967600/issue.tar.gz.zip)

**Comment by brunato** [comment]
Hi,
testing with another software that can validate XSD 1.1 (xerces) the results are the same given by xmlschema:

  * duplicate_partNumber_issue.xml: INVALID
  * invalid_attribute.xml: VALID
  * invalid_nexts_issue.xml: INVALID

These are the error messages produced by xerces (you already know about the errors given by xmlschema):

_duplicate_partNumber_issue.xml_:
  
```
[Error] duplicate_partNumber_issue.xml:10:62:cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.ludd21.com/kPartModel":castOnPartPoint}'. One of '{"http://www.ludd21.com/kPartModel":castOnPartSeg, "http://www.ludd21.com/kPartModel":joinPart}' is expected.
[Error] duplicate_partNumber_issue.xml:11:80:cvc-complex-type.3.2.2: Attribute 'end' is not allowed to appear in element 'ns0:basePoint'.
[Error] duplicate_partNumber_issue.xml:20:23:cvc-assertion: Assertion evaluation ('every $x in data(kPartsList/*/@nextsnum) satisfies some $part in kPartsList/* satisfies $part/@partNumber = $x') for element 'ns0:kPartsPiece' on schema type '#AnonType_kPartsPiece' did not succeed.
```

_invalid_nexts_issue.xml_:
```
[Error] invalid_nexts_issue.xml:10:62:cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.ludd21.com/kPartModel":castOnPartPoint}'. One of '{"http://www.ludd21.com/kPartModel":castOnPartSeg, "http://www.ludd21.com/kPartModel":joinPart}' is expected.
[Error] invalid_nexts_issue.xml:17:23:cvc-assertion: Assertion evaluation ('every $x in data(kPartsList/*/@nextsnum) satisfies some $part in kPartsList/* satisfies $part/@partNumber = $x') for element 'ns0:kPartsPiece' on schema type '#AnonType_kPartsPiece' did not succeed.
```

The XPath expressions are valid, otherwise an error is raised during the schema building. Simply the result of the expressions is false (checking _duplicate_partNumber_issue.xml_ i see that in fact the result has to be false because there is no partNumber="6" ...).

Best regards

**Comment by piscvau** [comment]
Thanks for replying. Yes In cutting off the complex model and the data to produce the tests for the issue,  I made more errors than intended!....
and all the errors raised by the other software are easy to localize. Because XMLSchema raises only one error, it was not the error I expected but the one I did not intend!... 
Here is another archive where all unintended errors are corrected.  The only may be problem remaining is that 
duplicate PartNumber does not return id of the unique item but a None code. But the reason is OK so it might be perfectly OK.
[files issue_error_code.tar.gz.zip](https://github.com/sissaschool/xmlschema/files/8984255/files.issue_error_code.tar.gz.zip)

Thanks for your taking the time to investigate. I let you close the issue if you so decide.

**Comment by brunato** [comment]
For getting all validation errors take a look at `iter_errors()` or at decode() with `validation='lax'`.

Best regards

**Comment by piscvau** [comment]
Thanks .Is there anyway to get the ancestors of the element which produced the error. The error.object argument is an elementTree.Element which has no parent.

**Comment by brunato** [comment]
With ElementTree for getting the parent you have to iterate the root, eg.:

```python
# elem is the element you want to find the parent
for e in root.iter():
    if elem in e:
        parent = e
        break
else:
        parent = None  # elem is the root or is not an element of the tree
```
