### ISSUE TITLE
Getting error when am trying create xml from json and xsd

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#313]

**Comment by priyatamnano** [comment]
want to create xml from xsd and populate all the values from json

**Comment by brunato** [comment]
With a fix in *path* argument, providing `path='note'`:

```python
import xmlschema
import json
from xml.etree import ElementTree

my_xsd = '<?xml version="1.0"?><schema targetNamespace = "urn:oasis:names:tc:emergency:cap:1.2" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema"> <element name="note" type="xs:string"/><element name="age" type="xs:integer"/> </schema>'

schema = xmlschema.XMLSchema(my_xsd)
data = json.dumps({'note': 'this is a Note text','age':'5'})
print(data)
print(schema)
xml = xmlschema.from_json(data, schema = schema, preserve_root=True, namespaces={'': 'urn:oasis:names:tc:emergency:cap:1.2'},path='note')
ElementTree.dump(xml)
```
the result of running your script is:

```
{"note": "this is a Note text", "age": "5"}
XMLSchema10(namespace='urn:oasis:names:tc:emergency:cap:1.2')
<ns0:note xmlns:ns0="urn:oasis:names:tc:emergency:cap:1.2">this is a Note text</ns0:note>
```

**Comment by priyatamnano** [comment]
Want to generate the xml template from xsd and populate with Jason ,it may contains many path ,how can I do it ? Do you have any documentation with examples ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brunato** [comment]
It's a custom method on building an XML from a generic JSON, I don't have documentation for that, sorry.

**Comment by priyatamnano** [comment]
No am asking anything we have xmlschema from Json like build a xml using xsd and Json ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brunato** [comment]
It's not a feature of the package. With xmlschema you can convert JSON to XML using the schema only if the JSON is structured in a compatible shape (see converters). 
Building XML from a template, populating it with values taken from JSON is not supported (maybe you can do it on your own building your method).

**Comment by priyatamnano** [comment]
With xmlschema you can convert JSON to XML using the schema only if the JSON is structured in a compatible shape (see converters)?
Have checked all conveters.

Yes we can pass any converters type, but the generated xml should validate with xsd

Is it possible? Could you please help me ,am struggling.
Our main aim is create xml which should validate with xsd ,we can give any format json.
Can you share some working code .

From: Davide Brunato ***@***.***>
Date: Tuesday, 28 June 2022 at 9:24 pm
To: sissaschool/xmlschema ***@***.***>
Cc: Priyatam Nayak ***@***.***>, Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] Getting error when am trying create xml from json and xsd (Issue #313)

It's not a feature of the package. With xmlschema you can convert JSON to XML using the schema only if the JSON is structured in a compatible shape (see converters).
Building XML from a template, populating it with values taken from JSON is not supported (maybe you can do it on your own building your method).

**Comment by priyatamnano** [comment]
import xmlschema
location = "http://schemas.xmlsoap.org/soap/envelope/"
xml_schema = './nikola.xsd'
xml_document = './valid_nikola.xml'
xs = xmlschema.XMLSchema(xml_schema, converter=xmlschema.BadgerFishConverter)
xs.import_schema(namespace=location,
                     location=location, build=True)
json_data = json.dumps(xs.to_dict(xml_document, decimal_type=str))
xml_data = xmlschema.from_json(json_data, xs, converter=xmlschema.BadgerFishConverter)
xs.validate(xml_data)

[Archive.zip](https://github.com/sissaschool/xmlschema/files/9009549/Archive.zip)

@brunato   want to do like this ,it is giving errors, could you please help me . have attached the xml and xsd file .

**Comment by priyatamnano** [comment]
import xmlschema
location = "http://schemas.xmlsoap.org/soap/envelope/"
xml_schema = './nikola.xsd'
xml_document = './valid_nikola.xml'
xs = xmlschema.XMLSchema(xml_schema,converter=xmlschema.AbderaConverter)
xs.import_schema(namespace=location,
                     location=location, build=True)
import pdb;pdb.set_trace()
#json_data = json.dumps(xs.to_dict(xml_document, decimal_type=str)['soapenv:Envelope'][0]['soapenv:Body'])
#json_data = json.dumps(xs.to_dict(xml_document, decimal_type=str)['soapenv:Body']['soapenv:Envelope'][0]['soapenv:Body'])
json_data = json.dumps( xs.to_dict(xml_document, decimal_type=str)['soapenv:Envelope']['soapenv:Body'])
print(xs.annotations)
xml_data = xmlschema.from_json(json_data, xs,converter=xmlschema.AbderaConverter ,preserve_root=True, namespaces={'ns0':'urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication'} )
#xs.validate(xml_data)

error:
Reason: The content of element '{urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication}ApplicationBatch' is not complete. Tag 'Identifier' expected.
note: Tried with different converters  it is giving different errors ,Could you please help me.
@brunato

**Comment by priyatamnano** [comment]
@brunato  Sir any help ?

**Comment by priyatamnano** [comment]
am able to solve this , have created PR also ,can you review and release a new version?

**Comment by priyatamnano** [comment]
import xmlschema
location = "http://schemas.xmlsoap.org/soap/envelope/"
xml_schema = './nikola.xsd'
xml_document = './valid_nikola.xml'
xs = xmlschema.XMLSchema(xml_schema,converter=xmlschema.BadgerFishConverter)
xs.import_schema(namespace=location,
                     location=location, build=True)


json_data = json.dumps( xs.to_dict(xml_document, decimal_type=str)['soapenv:Body']['soapenv:Envelope'][0]['soapenv:Body'])

print(xs.annotations)
xml_data = xmlschema.from_json(json_data, xs,converter =xmlschema.BadgerFishConverter,preserve_root=True, namespaces={'ns0':'urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication'} )
print(xs.is_valid(xml_data))
print(xmlschema.etree_tostring(xml_data))

**Comment by priyatamnano** [comment]
am not able to push the code
could you please add the below line in bagerfish.py file (line number 128)

        if type(element_data)==list:
            element_data=element_data[0]
        for name, value in element_data.items():

**Comment by priyatamnano** [comment]
i found some data is getting missed .

**Comment by priyatamnano** [comment]
Could you please look into the issue ?

**Comment by priyatamnano** [comment]
@brunato

**Comment by priyatamnano** [comment]
my requirement is  convert the xml to dict and  convert same dict to xml and it should  validate with xsd

**Comment by priyatamnano** [comment]
@brunato  Any idea ? All validator is failing ..
