### ISSUE TITLE
Namespace prefix of attributes

### ISSUE THREAD

**Issue by tysonite** [sissaschool/xmlschema#314]
Probably, I am doing something wrong or don't understand namespaces usage, but still want to see if any suggestions or fixes can be popped up.

I have XML schema and XML document that I want to validate and parse. XML schema has `attributeFormDefault="unqualified"` + `elementFormDefault="qualified"`, some of the attributes of elements belong to different namespaces. 

Part of XML:
```
<a:element b:attr1="a:some_value" attr2="..."/>
```

I parse this XML document with `XMLSchema.to_objects(xml_document, with_bindings=True)` method and want to get values of element's attributes. I use `.get()` method which requires either `b:attr1` or `attr2` as input, but namespace prefix `b` can be different depending on XML document source.

What is the right way to unify handling of such case? The same question applies to `a:some_value`, where `a` is actually a namespace prefix and `some_value` is a type. Do I need to maintain a mapping between namespace URI and namespace prefixes of XSD and XML (in my case prefixes differ between XSD and XML document, but URIs are the same), and concatenate namespace prefix and attribute name before calling `.get(...)`?

**Comment by brunato** [comment]
Hi,
methods `get()` and `set()` of `DataElement` objects have an extended name resolution in v2.0.0. Provided key arguments that are in prefixed format are mapped to extended format before lookup in `attrib`.

Best regards

**Comment by tysonite** [comment]
Hi @brunato, thank you for your efforts, but the fix does not work for some reason.

I've upgraded to 2.0.0 and while I debugging I see following:

1. Input argument value to `get()` is `b:type`, `b` is defined as `xmlns:b="http://www.w3.org/2001/XMLSchema-instance"` in a top-level element of my XML.
2. After calling `key = self._map_attribute_prefixed_name(key)` in `get()`, `key` gets evaluated to `{http://www.w3.org/2001/XMLSchema-instance}type`, but `self.attrib` contains `b:type` and `self.attrib.get(...)` fails.

Not sure if this is valid case, though, but this is some kind of regression. I can't anymore get a value of my attribute by any means. If input argument is `type` or `{http://www.w3.org/2001/XMLSchema-instance}type`, the value of attribute can't be obtained as well.

**Comment by brunato** [comment]
So, attribute names in `DataElement` can be local names, prefixed names (eg. `b:type`) or extended names (eg. `{http://www.w3.org/2001/XMLSchema-instance}type`). I'll try to handle this on `get()` and `set()` (but not in `attrib`).

Have you an example with `xsi:type`, in order to create a test case?

Thank you

**Comment by tysonite** [comment]
Sure. I hope I did a correct minimal example of XML schema and and example of XML to showcase issue. See below please.

XSD:
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="my_namespace"
           targetNamespace="my_namespace"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:complexType name="ContainterItemInfo">
  </xs:complexType>

  <xs:complexType name="ConcreteContainterItemInfo">
    <xs:complexContent>
      <xs:extension base="ContainterItemInfo">
        <xs:attribute name="attr_2" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ContainerInfo">
    <xs:complexContent>
      <xs:extension base="ContainterItemInfo">
        <xs:sequence>
          <xs:element name="item" type="ContainterItemInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="RootElementInfo">
    <xs:sequence>
      <xs:element name="container" type="ContainerInfo"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="root-element" type="RootElementInfo">
  </xs:element>

</xs:schema>
```

XML:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:root-element xmlns:p="my_namespace" xmlns:b="http://www.w3.org/2001/XMLSchema-instance">
  <p:container>
    <p:item b:type="p:ConcreteContainterItemInfo" attr_2="value_2"/>
  </p:container>
</p:root-element>
```

The `attrib` list looks like that if:
```
>>> xs = xmlschema.XMLSchema("xmlschema_bug_1.xsd")
>>> xml_object = xs.to_objects("xmlschema_bug_1.xml", with_bindings=True)
>>> print(list(list(xml_object.iterchildren('{my_namespace}container'))[0].iterchildren('{my_namespace}item'))[0].attrib)
{'b:type': 'p:ConcreteContainterItemInfo', 'attr_2': 'value_2'}
```

The `b:type` references one of types in XSD.

**Comment by brunato** [comment]
This error with `process_namespace=False` is related with the lookup required by `xsi:type`, and affects the decode process in general.

**Comment by tysonite** [comment]
Sounds good to me. What will be allowed input argument format of key and algorithm of fallback?

E.g. if key is not in attrib dict, than fallback to either prefixed or extended format, but 2 different namespaces has the same key name?

attrib dict like that:
```
{'b:type': 'p:ConcreteContainterItemInfo', 'a:type': 'another_value', 'attr_2': 'value_2'}
```

Or is it not allowed by specs?

**Comment by brunato** [comment]
This is the new version:

```python
    def get(self, key: str, default: Any = None) -> Any:
        """Gets a data element attribute."""
        try:
            return self.attrib[key]
        except KeyError:
            if not self.nsmap:
                return default

            # Try a match with mapped/unmapped name
            if key.startswith('{'):
                key = get_prefixed_qname(key, self.nsmap)
                return self.attrib.get(key, default)
            elif ':' in key:
                try:
                    _prefix, _local_name = key.split(':')
                    key = '{%s}%s' % (self.nsmap[_prefix], _local_name)
                except (ValueError, KeyError):
                    pass
                else:
                    return self.attrib.get(key, default)
            return default
```

`set()` has been restored to the initial version:

```python
    def set(self, key: str, value: Any) -> None:
        """Sets a data element attribute."""
        self.attrib[key] = value
```

Anyway if you need an alternative behavior you can subclass DataElement an provide `data_element_class` to `to_objects()`.

**Comment by brunato** [comment]
Also: attribute mapping (`{uri}name` -> `pref:name`) could be regulated by an optional argument for `DataElementConverter/DataBindingConverter` (eg. `map_attributes`, `True` for default).

**Comment by tysonite** [comment]
Yeah. It works with modified version of `get()`! Thank you for pointing to `map_attributes` too.

**Comment by brunato** [comment]
Ok, the new argument for `DataElementConverter` will be `map_attribute_names` to avoid overlap/confusion with method `map_attributes` in base class.

**Comment by brunato** [comment]
A new release is available with the fix for `process_namespace` and the new argument `map_attribute_names`.

Thank you

**Comment by tysonite** [comment]
Thanks! Upgraded to 2.0.1 and it works as expected.
