### ISSUE TITLE
XMLSchemaConverter not  able to convert the text data to xml

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#316]
this converter is able to convert the below xml data to dict data

```xml
<ns0:LoanTerm Units="Months" Type="TotalTerm" PaymentType="PrincipleAndInterest">360</ns0:LoanTerm>
```
```
'ns0:LoanTerm': [{'@Units': 'Months', '@Type': 'TotalTerm', '@PaymentType': 'PrincipleAndInterest', '$': '360'}]
```

But not able to convert back to xml when am using from_json

```
error:
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication}ApplicationBatch' at 0x10faaabd0> with XsdGroup(model='sequence', occurs=[1, 1]):

Reason: The content of element '{urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication}ApplicationBatch' is not complete. Tag 'Identifier' expected.
```

**Comment by priyatamnano** [comment]
any update ?  am getting other issues when am sending soap xml  to json ,it is giving errors

 elif isinstance(obj, (converter.dict, dict)) and len(obj) == 1:
                for key in obj:
                    match = re.search(r'[{\w]', key)
this one come  len(obj) == 1:   as 2 instead of one as it contains 2 keys,  is there any fix for this ?

<soapenv:Body xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:suncorp-com-au:wmb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<soapenv:Envelope>
<soapenv:Header>
<wmb:ServiceName>x</wmb:ServiceName>
<wmb:Action>x</wmb:Action>
</soapenv:Header>
<soapenv:Body>
<ns0:ApplicationBatch xmlns:ns0="ux"  ProductionData="No">
@brunato

**Comment by brunato** [comment]
I'm going to complete a set of tests with a fix for #315. About the default converter (XMLSchemaConverter, but also with UnorderedConverter, that is a variation of the default converter), you have to provide a `cdata_prefix` (usulally '#'). 

In any case with mixed content the order of children cannot be preserved normally (cdata and child elements with the same name). For a warranty on preserving structure and order the only choice is to use the JsonML convention.

**Comment by priyatamnano** [comment]
See the below,the object is coming 3
-> elif isinstance(obj, (converter.dict, dict)) and len(obj)==1:
(Pdb) n
> /Users/priyatamnayak/.local/share/virtualenvs/nano-lixi-IJd-8ihv/lib/python3.8/site-packages/xmlschema/validators/schemas.py(2112)iter_encode()
-> if not isinstance(xsd_element, XsdElement):
(Pdb) len(obj)
3
(Pdb) converter
<xmlschema.converters.jsonml.JsonMLConverter object at 0x10c1d4ac0>
(Pdb)
From: Priyatam Nayak ***@***.***>
Date: Wednesday, 6 July 2022 at 10:47 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] XMLSchemaConverter not able to convert the text data to xml (Issue #316)
Have also tested with JsonML ,it is giving issues for soap xml ,any idea ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by priyatamnano** [comment]
Am getting the below error when am using jsonMLconverter and also the len(obj) is coming  3


File "/Users/priyatamnayak/Repository/nano-lixi/src/lixi/base.py", line 140, in to_xml
    return parser.to_xml()
  File "/Users/priyatamnayak/Repository/nano-lixi/src/lixi/partners/nikola_v14/__init__.py", line 187, in to_xml
    xml_data = xmlschema.from_json(
  File "/Users/priyatamnayak/.local/share/virtualenvs/nano-lixi-IJd-8ihv/lib/python3.8/site-packages/xmlschema/documents.py", line 413, in from_json
    return schema.encode(obj, path=path, converter=converter, **kwargs)
  File "/Users/priyatamnayak/.local/share/virtualenvs/nano-lixi-IJd-8ihv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 2136, in encode
    for result in self.iter_encode(obj, path, validation, *args, **kwargs):
  File "/Users/priyatamnayak/.local/share/virtualenvs/nano-lixi-IJd-8ihv/lib/python3.8/site-packages/xmlschema/validators/schemas.py", line 2114, in iter_encode
    if path is not None:
xmlschema.validators.exceptions.XMLSchemaEncodeError: failed validating ['soapenv:Body', {'xmlns:soapenc': 'http://schemas.xmlsoap.org/soap/encoding/', 'xmlns:soapenv': 'http://schemas.xmlsoap.org/soap/envelope/', 'xmlns:wmb': 'urn:suncorp-com-au:wmb', 'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance', 'xmlns:wsse': 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd', 'xmlns:

From: Priyatam Nayak ***@***.***>
Date: Wednesday, 6 July 2022 at 10:51 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] XMLSchemaConverter not able to convert the text data to xml (Issue #316)
See the below,the object is coming 3
-> elif isinstance(obj, (converter.dict, dict)) and len(obj)==1:
(Pdb) n
> /Users/priyatamnayak/.local/share/virtualenvs/nano-lixi-IJd-8ihv/lib/python3.8/site-packages/xmlschema/validators/schemas.py(2112)iter_encode()
-> if not isinstance(xsd_element, XsdElement):
(Pdb) len(obj)
3
(Pdb) converter
<xmlschema.converters.jsonml.JsonMLConverter object at 0x10c1d4ac0>
(Pdb)
From: Priyatam Nayak ***@***.***>
Date: Wednesday, 6 July 2022 at 10:47 pm
To: sissaschool/xmlschema ***@***.***>, sissaschool/xmlschema ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [sissaschool/xmlschema] XMLSchemaConverter not able to convert the text data to xml (Issue #316)
Have also tested with JsonML ,it is giving issues for soap xml ,any idea ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by priyatamnano** [comment]
am attaching the xsd and xml file , my requirement is convert the XML to dict and  convert the  same dict to xml (using any converter)

[Archive.zip](https://github.com/sissaschool/xmlschema/files/9055124/Archive.zip)

**Comment by brunato** [comment]
Tried your lines of code, retrieving soapenv schema from https://schemas.xmlsoap.org/soap/envelope/.

You miss to provide the path argument, eg.:

```python
xml_data = xmlschema.from_json(json_data, xs, path='soapenv:Body', unordered=True, converter=xmlschema.JsonMLConverter(dict_type=dict), preserve_root=True, namespaces={ 'soapenv': 'http://schemas.xmlsoap.org/soap/envelope/'})
```
xml_data is identical to xml source data (_nikola_valid.xml_). The file _nikola_valid.xml_ contains an invalid character `&`, that has to be replaced by `&amp;` entity.

I check if it is possible to retrieve the right encoding element with a full search into defined global elements.

**Comment by priyatamnano** [comment]
yes, have changed the encoding.
but after that also am getting this error 
    raise XMLSchemaTypeError(msg.format(type(obj)))
xmlschema.exceptions.XMLSchemaTypeError: The first argument must be a sequence, <class 'str'> provided

 79             if not isinstance(obj, MutableSequence):
 80                 import pdb;pdb.set_trace()
 81  ->             msg = "The first argument must be a sequence, {} provided"
 82                 raise XMLSchemaTypeError(msg.format(type(obj)))
 83             elif not obj:
 84                 raise XMLSchemaValueError("The first argument is an empty sequence")
 85     
 86             data_len = len(obj)
(Pdb) obj
'wmb:ServiceName'
(Pdb) isinstance(obj, MutableSequence)
False
(Pdb) MutableSequence
<class 'collections.abc.MutableSequence'>
(Pdb)

**Comment by priyatamnano** [comment]
Aslo want to keep namespace tag as <soapenv> and <ns0>

but the xml_from_json converting  it like below . How to keep it is as original format ?
 </ns2:ApplicationBatch>
            </ns0:Body>
        </ns0:Envelope>
    </ns0:Body>
</ns0:Body>

**Comment by brunato** [comment]
Provide a full namespace map (not only 'soapenv' ...) when you call _decode/to_dict_.

Best regards

**Comment by priyatamnano** [comment]
Have given that, but it is becoming ns2 instead of ns0

<soapenv:Body xmlns:ns2="urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:suncorp-com-au:wmb">
    <soapenv:Envelope>
        <soapenv:Header>
            <wmb:ServiceName>LOAN</wmb:ServiceName>
            <wmb:Action>SUBMITAPPLICATION</wmb:Action>
        </soapenv:Header>
        <soapenv:Body>
            <ns2:ApplicationBatch NumberOfApplications="1" ProductionData="No">
                <ns2:Identifier UniqueID="1036921-SUN" Type="BrokerAssigned" />
                <ns2:RevisionNumber LIXIVersion="1.4" LenderVersion="1.0" />
                <ns2:Submission>

**Comment by priyatamnano** [comment]
json_data = json.dumps(self.data)
            xml_data = xmlschema.from_json(
                json_data,
                xs,
                unordered=True,
                converter=NikolaBadgerFishConverter(dict_type=OrderedDict),
                preserve_root=True,
                validator="strict",
                path='soapenv:Body',

                namespaces={
                    'soapenv': 'http://schemas.xmlsoap.org/soap/envelope/',
                    'soapenc': "http://schemas.xmlsoap.org/soap/encoding/",
                    'wmb': "urn:suncorp-com-au:wmb",
                    'xsi': "http://www.w3.org/2001/XMLSchema-instance",
                    'wsse': "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",
                    'ns0': "urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication"

                },
            )
        except urllib.error.URLError:
            message = f"No such file or directory {self.xsd_file}"
            raise FileNotFoundError(message)
        except Exception as error:
            logger.error(error)
            raise XmlToDictConversionError(
                f"Not able to convert dict data to xml string : {error}"
            )

        return xmlschema.etree_tostring(xml_data, {
                    'soapenv': 'http://schemas.xmlsoap.org/soap/envelope/',
                    'soapenc': "http://schemas.xmlsoap.org/soap/encoding/",
                    'wmb': "urn:suncorp-com-au:wmb",
                    'xsi': "http://www.w3.org/2001/XMLSchema-instance",
                    'wsse': "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",
                    'ns0': "urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication"
                }, xml_declaration=True)

**Comment by brunato** [comment]
You cannot use 'ns0', 'ns1' ... prefixes in the map because they are reserved (by ElementTree)

**Comment by priyatamnano** [comment]
i think this is the issue why  xmlns  keeping ns0': 'urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication'}, instead of it should present in 'ns0:ApplicationBatch '  dict ?

lx.to_dict()['@xmlns']
{'soapenc': 'http://schemas.xmlsoap.org/soap/encoding/', 'soapenv': 'http://schemas.xmlsoap.org/soap/envelope/', 'wmb': 'urn:suncorp-com-au:wmb', 'xsi': 'http://www.w3.org/2001/XMLSchema-instance', 'wsse': 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd', 'ns0': 'urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication'}

@brunato

**Comment by priyatamnano** [comment]
after removing from that it is giving correct result, do you know how can put that inside applicationbatch at the time dict creation  ?

@brunato

**Comment by priyatamnano** [comment]
any idea @brunato

**Comment by priyatamnano** [comment]
{'@xmlns': {'soapenc': 'http://schemas.xmlsoap.org/soap/encoding/', 'soapenv': 'http://schemas.xmlsoap.org/soap/envelope/', 'wmb': 'urn:suncorp-com-au:wmb', 'xsi': 'http://www.w3.org/2001/XMLSchema-instance', 'wsse': 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd', 'ns0': 'urn:ais:schema:banking:loans:sunloan:SubmitSLNApplication'}, 'soapenv:Body': {'soapenv:Envelope': [{'soapenv:Header': {'wmb:ServiceName': [{'$': 'LOAN'}], 'wmb:Action': [{'$': 'SUBMITAPPLICATION'}]}, 'soapenv:Body': {'ns0:ApplicationBatch': [{'@NumberOfApplications': '1', '@ProductionData': 'No', 'ns0:Identifier': [{'@UniqueID': '1036921-SUN', '@Type': 'BrokerAssigned'}],

**Comment by priyatamnano** [comment]
Have also tested with JsonML ,it is giving issues for soap xml ,any idea ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
