### ISSUE TITLE
to_dict putting the data elements in namespace if it has xmlns tag

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#318]
In the below case ,to_dict method putting the  ns0="urn:ais:SubmitApplication" in xmlns key, instaed of  ns0:ApplicationBatch key ,which causing issue when creating the xml again from the same dict.

<soapenv:Body xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wmb="urn:xxx-com-au:wmb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<ns0:ApplicationBatch xmlns:ns0="urn:ais:SubmitApplication" NumberOfApplications="x" ProductionData="No">

**Comment by brunato** [comment]
This is not an issue of this library. Please stop opening issues for cases that clearly not depend by this library. 

Best Regards
