### ISSUE TITLE
getting some wiered errors

### ISSUE THREAD

**Issue by priyatamnano** [sissaschool/xmlschema#320]
Getting some c++ errors when xsd validation
value doesn't match any pattern of ['\\c+']"

**Comment by brunato** [comment]
Maybe something wrong in your C++ with character encoding. 
But this is a Python-only package, so nothing related with xmlschema I suppose ...

**Comment by priyatamnano** [comment]
Haha

This errors am getting when am doing xsd validation

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brunato** [comment]
I don't know wherever you have added the _xmlschema_ library for validation, but a pure Python library cannot cause an error in your C++ application/environment if you don't already have a problem in this. So please don't open issues in these cases.

Cheers
