### ISSUE TITLE
`py.typed` not included in 2.0.1

### ISSUE THREAD

**Issue by Syndace** [sissaschool/xmlschema#321]
Hi, I found that the `py.typed` file is not included in the pip package version 2.0.1, but it is included in 2.0.0. I believe it is likely [this commit](https://github.com/sissaschool/xmlschema/commit/be2749e7d44b41cda8c1ddfa7f343b90872972be) that broke the `py.typed` file being included in the package data.

**Comment by brunato** [comment]
`py.typed` has been included again in the new version v2.0.2.

Thank you
