### ISSUE TITLE
Question: Iterate trough XMLDocument

### ISSUE THREAD

**Issue by Veganizer** [sissaschool/xmlschema#328]
Is there a way to iterate trough a XMLDocument without converting it to an object or dict? 

Unfortunally the attribute getChildren doesn't exist in XMLDocument's root.

I tried XsdElement.iter()

I tried iter() itself, it iters but I can't find a relation to children or parent.

Maybe someone can help me...

**Comment by Veganizer** [comment]
Okay I find it out randomly.
It is just easy... :-D

just loop trough the element itself.

**Comment by brunato** [comment]
It's similar to ElementTree API whenever possible ...

Cheers
