### ISSUE TITLE
using databinding classes for global complex types

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#329]
Hello
I have existing python classes and I want to create instances of these classes with the DataBinding converter.
My schema contain several global complex types and global simple types and I need to be able to create instances of corresponding existing corresponding classes.
For example I have in my xsd 
   <xs:complexType name = "line">      
        <xs:attribute name= "start" type = "point" use = "required"/>
        <xs:attribute name= "end" type = "point" use = "required"/>
    </xs:complexType>
and an existing class Line whose init is : __init__(start, end)

I do not see how to create such a BindingClass as the metaclass __init__ checks that the xsd_element is an instance of validators.xsd_element.
I probably missed something there or may be there is a simpler way to create such a binding class.

Any help would be most welcomed

**Comment by piscvau** [comment]
thanks for the answer. How about creating a binding class which inherits only from dataelement and does not inherit from dataBindingMeta?
I understand that this class cannot be dynamically generated but if it somehow exists  before decoding, is not this a possible solution? or Am I going to get into problems?

**Comment by brunato** [comment]
DataBindingMeta is a metaclass, not a simple class. Metaclasses are used to customize types creation (e.g. setting an the appropriate name for the dynamic created class).

**Comment by piscvau** [comment]
Thanks for your answer. I did create a bindingclass which inherits only from dataelement and does not inherit from dataBindingMeta. Of course, this bindingclass is not dynamically created.
