### ISSUE TITLE
accessing the type of an attribute

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#331]

**Comment by piscvau** [comment]
How can I access the type of an attribute.
for example I have  :  
 <xs:complexType name = "line">      
        <xs:attribute name= "start" type = "point" use = "required"/>
        <xs:attribute name= "rotation" type = "xs:decimal" use = "required"/>
    </xs:complexType>
and
<xs:simpleType name = "point">
        <xs:restriction>
          <xs:simpleType>
            <xs:list itemType = "decimal5digits"/>
          </xs:simpleType>
          <xs:length value = "2"/>
        </xs:restriction>
    </xs:simpleType>
How can I associate know what is the type of the attribute in the dataelement object?

**Comment by brunato** [comment]
If you have a dataelement object (e.g. _obj_) you can use `obj.attrib[key]` to get the _XsdAttribute_ and then the type:

```python
xsd_attribute = obj.attrib['foo']
xsd_type = xsd_attribute.type
```

**Comment by piscvau** [comment]
Well here is what I get for a dataelement instance : 
isinstance(dataelement, xs.DataElement)
True
xsd_attribute = dataelement.attrib['start']
xsd_attribute.type
Traceback (most recent call last):
  Debug Console, prompt 50, line 1
builtins.AttributeError: 'list' object has no attribute 'type'

It seems as the object is of type list and not of type point. Is this because I described the type as a restriction of a list?

**Comment by brunato** [comment]
Sorry I made a mistake, confusing XML data attributes and XSD attributes. For accessing the latters you have to do:

```python
xsd_attribute = obj.xsd_element.attributes['foo']
xsd_type = xsd_attribute.type
```

**Comment by piscvau** [comment]
Hello I am sorry but I still get the same problem.
<xs:complexType name = "line"> 
        <xs:attribute name= "start" type = "point" use = "required"/>
        <xs:attribute name= "end" type = "point" use = "required"/>
    </xs:complexType >

 <xs:simpleType name = "point">
        <xs:restriction>
          <xs:simpleType>
            <xs:list itemType = "decimal5digits"/>
          </xs:simpleType>
          <xs:length value = "2"/>
        </xs:restriction>
    </xs:simpleType>

The attribute start of complextype line has a type Point defined as a restriction of a list. When I look for the xsd_attribute.type I get 'list' and not 'point'. Is this normal behavior?

**Comment by piscvau** [comment]
Sorry. I made the same confusion. The the type of the xsd_type.attributes is correct.
