### ISSUE TITLE
child missing after encoding an object into xml

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#333]
Hello
My  program encoding an object into xml using schema.encode produces an etree. I then use etree.to_string to produce an xml string.
This code has been thoroughly tested. But I ran it with a more complex object and I get into a problem. One of the child is just not present into the xml string.
I have spent several days doing step by step to try to find a bug in my encoder but I do see the child being encoded while it is missing in the xml string.
I have tried to dump the etree and the element seems also to be missing in the dump.
I am not an expert into digging into xml.etree and therefore cannot go any further.

I do have set up an environment and a test file that reproduces the bug. However it is big and therefore should be transmitted via a transfer like web site. I have set up 2 tests, one that encodes into xml where the part is missing and one that creates only the etree so it is possible to dig into it.
I thank you in advance for your help.
piscvau

**Comment by brunato** [comment]
Hi,
the element that is missing in the XML string serialization is included in the tree encoded using `schema.encode`?

Have you tried using `xml.etree.ElementTree.tostring()`?

**Comment by piscvau** [comment]
Yes the element is included into the etreeElement resulting from schema.encode. If I do
etree.findall(".//*[@partNumber='12']")
I do get a part. 
but if I start from the root and go down to the parent of the missing part, and list the children of this parent, the part is missing. In other words, the part is in the tree but it is not a child of its parent!...

Yes I have tried using xml.etree.ElementTree.tostring and the part is also missing.

**Comment by brunato** [comment]
Have you check if that child is a comment or PI (Processing Instruction) node?

Which command do you use to list the children?

**Comment by piscvau** [comment]
Hello Thank you for your hints.
After looking in more details the child is not missing but its attributes are wrong.
I use a databinding converter with a specific element_decode method calling an xml_topython method declared in a databinding classes. At the end of this method, I store each created object in a dataelement.obj attribute and return dataelement. When creating the parent I use list(dataelement) or dataelement.obj in list(dataelement) to get the objects corresponding to the children.
When I do a print of each object of the type 'part' at the end of the xml_topython method, the attributes are correct. When I do a print at the entrance of the parent bindingclass method the attributes have changed.
Could that be related to the fact that I store each object in a dataelement.obj?

**Comment by brunato** [comment]
Hi,
i don't know how you customization of `DataElement` works, so I can't argue nothing on this. This space is for, possibly specific, issues that are found on _xmlschema_ package.

thank you
