### ISSUE TITLE
Support elementpath v4

### ISSUE THREAD

**Issue by dotlambda** [sissaschool/xmlschema#335]

**Comment by brunato** [comment]
xmlschema v2.2.0 is avaliable. The new dependency from XPath processor is `elementpath>=4.0.0, <5.0.0 `.

The previous version of *xmlschema* had problems with unprefixed sequence types, that are not accepted anymore in *elementpath* v4, so I've increased the major version of *elementpath* to avoid updates that then cause faults in certain cases (some XSD 1.1 assertions).
