### ISSUE TITLE
Validation of single element of schema

### ISSUE THREAD

**Issue by mander76** [sissaschool/xmlschema#338]
Hi

I have built a package (https://github.com/pyoscx/scenariogeneration) that can generate xml files for simulation inputs (OpenSCENARIO and OpenDRIVE), and want to validate the xmls generated. 
There are alot of different possibilities to create these xmls, so I test each class (which is responsible for one element each) individually. What I would like to do is to validate just one element of the schema. 

An example:
the part of the schema
```
	<xsd:complexType name="DynamicConstraints">
		<xsd:attribute name="maxAcceleration" type="Double"/>
		<xsd:attribute name="maxAccelerationRate" type="Double"/>
		<xsd:attribute name="maxDeceleration" type="Double"/>
		<xsd:attribute name="maxDecelerationRate" type="Double"/>
		<xsd:attribute name="maxSpeed" type="Double"/>
	</xsd:complexType>

```
The generated xml
`<DynamicConstraints maxSpeed="1.0" maxDeceleration="1.0" maxAcceleration="1.0"/>`

Is this possible somehow?

**Comment by brunato** [comment]
Hi,

this should be possible but XML elements have to be validated using an _XsdElement_ objects, not a complex type.

This element can be created using the schema (or another schema containing the element, that is then included), otherwise it could be also created on the fly from an element, associating the proper type. 

I already do this in the code for wildcards (see ), but without specifying a type. It should work also providing a type attribute with the name.

**Comment by mander76** [comment]
I don't fully understand to be honest. Not sure if I do it correctly, but following the same example as before

```
import xmlschema

from scenariogeneration import xosc

schema = xmlschema.XMLSchema("OpenSCENARIO_1_0.xsd")
xsd_element = schema.create_element("DynamicConstraints")

dc = xosc.DynamicsConstraints(10,20,30)
print(xsd_element.validate(dc.get_element()))
```
(Note dc.get_element() returns a xml.etree.ElementTree.Element)

This however yields a None, no matter what element I send in

**Comment by brunato** [comment]
You can try providing `type='DynamicConstraints'` to *create_element()* ...

But if `OpenSCENARIO_1_0.xsd` already contains proper elements (that have the name 'DynamicConstraints' and type 'DynamicConstraints') you don't need to create a new element in a custom way. Fetch the non global element using `find(path)` on schema or use `schema.validate()` providing a `schema_path` argument.

**Comment by mander76** [comment]
Cool, this worked! 

Thanks for the quick and effective support :)
