### ISSUE TITLE
Registro Nazionale degli Aiuti di Stato

### ISSUE THREAD

**Issue by paolovolterra** [sissaschool/xmlschema#339]
ciao
non riesco però ad utilizzarlo con gli aiuti del [RNA](https://www.rna.gov.it/RegistroNazionaleTrasparenza/faces/pages/OpenDataAiuti.jspx)...

**Comment by brunato** [comment]
ciao,

ho dato un'occhiata al registro.

Lo schema dei dati non è pubblicamente accessibile ([qui](https://www.rna.gov.it/sites/PortaleRNA/it_IT/comunicazioni) parlano di area riservata). Tu ne hai accesso?

Inoltre i file XML sono molto grossi, potrebbe essere un problema con la memoria o la lentezza di elaborazione. Ci sono file XML di esempio con cui si possa fare qualche test?

Se non puoi pubblicare lo schema qui evenualmente inviamelo via email (trovi il mio indirizzo nei riferimenti all'autore del codice).
 
Grazie

**Comment by paolovolterra** [comment]
No, infatti
Ma opendata senza schema?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brunato** [comment]
Sono d'accordo, non ha senso pubblicare dataset così corposi senza gli schemi base per elaborarli. Peraltro i file sembrano un lungo elenco di sezioni simili di secondo livello, lo schema non dovrebbe neppure essere tanto complicato.

Volendo si può usare uno schema generico basato su wildcard per convertirli in JSON, ma risulterebbe molto lento per via della generazione dinamica di elementi generici. 

L'elaborazione di file molto grossi è un problema. In xmlschema c'è una decodifica _lazy_ per risparmiare memoria, ma ancora c'è da lavorarci.

**Comment by paolovolterra** [comment]
se ne può parlare in un newsgroup?

**Comment by brunato** [comment]
Non frequento newsgroup o forum su opendata, ma se hai qualche suggerimento indicamelo pure scrivendomi una email.
Qui intanto chiudo la issue visto che non riguarda un problema dovuto a xmlschema.
