### ISSUE TITLE
Question: does xmlschema-validate.exe have an option or way to show validation errors?

### ISSUE THREAD

**Issue by martin-honnen** [sissaschool/xmlschema#343]
I am using xmlschema-2.2.3 with Python 3 and are exploring the CLI tool `xmlschema-validate.exe`. 

So far all I get it to output is whether an instance XML document is valid or not; I don't find a way in case of invalidity to get a single error message or a list of what exactly caused the validation to fail. 

Do I need to write my on Python code to achieve that, using e.g. `iter_errors`, or is there a way to have the CLI tool output some details?

**Comment by brunato** [comment]
Hi,
I think the CLI interfaces can be extended to get more output on validation errors. Maybe using logging, defining a logger instance, setup it and using `logger.error` calls.
