### ISSUE TITLE
Can't load WSDL document

### ISSUE THREAD

**Issue by Jacob-Flasheye** [sissaschool/xmlschema#347]
Hi.

I'm trying to read a bunch of wsdl files that I do not control (you can find them [here](https://github.com/onvif/specs/tree/development/wsdl)) and I run into a bunch of issues.
If I try importing with a random file
```python
wsdl_document = xmlschema.extras.Wsdl11Document(file)
```
I get the following error:
```
xmlschema.validators.exceptions.XMLSchemaModelError: Unique Particle Attribution violation ...
```
I get the same error when I set `validation` to `"lax"` or `"skip"`.

I then thought that I maybe need to specify `cls=xmlschema.XMLSchema11`:
```python
wsdl_document = xmlschema.extras.Wsdl11Document(
    file,
    cls=xmlschema.XMLSchema11,
    validation="lax"
```
and this runs successfully for most of the files, but fails for [this one](https://github.com/onvif/specs/blob/development/wsdl/ver20/analytics/wsdl/analytics.wsdl) with the following error:
```
xmlschema.validators.exceptions.XMLSchemaParseError: unknown type 'tt:Frame':

Schema:

  <xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="SampleFrame" type="tt:Frame">
      <xs:annotation><xs:documentation>Sample frame content starting with the tt:Frame node.</xs:documentation></xs:annotation>
  </xs:element>

Path: /xs:schema/xs:complexType[3]/xs:sequence/xs:element
```

I have two ideas of what I might be. The first is that the `validation` argument is not forwarded properly to the schema, or that I need to provide a `global_maps` argument. But it could very well be something else.

Does anyone know what I need to do to read the failing documents?

**Comment by brunato** [comment]
Hi,
infact, almost all the wsdl/xsd files of that repository contains XSD 1.1 schemas (error with XSD 1.0 is correct, there is an UPA violation between an element and a wildcard). 
It should work also without 'lax' validation mode.

With _analytics.wsdl_ the error is the type lookup, that is done before the building of the imported XSD file ( `wsdl/ver10/schema/metadatastream.xsd`). I'm confident this can be fixed for the next release.

**Comment by brunato** [comment]
This is not a bug. The embedded schema in _analytics.wsdl_ contains two imports of the same namespace:

```xsd
<xs:import namespace="http://www.onvif.org/ver10/schema" schemaLocation="../../../ver10/schema/onvif.xsd"/>
<xs:import namespace="http://www.onvif.org/ver10/schema" schemaLocation="../../../ver10/schema/metadatastream.xsd"/>
```

By XSD design the second import is skipped (to avoid circular imports). The best remediation for this is to fix source WSDL/XSD documents.

Anyway I examine possible changes in `Wsdl11Document` initialization to handle a non-standard workaround for cases like this.

**Comment by Jacob-Flasheye** [comment]
Thanks for taking your time looking at the schemas! I'm a novice at XML and XSD so your explanation of double imports is appreciated :pray:  I had a hunch the likely culprit was that double imports are invalid (a bit bummed they didn't follow the standard but whatever), but I hoped there was a solution that worked right now. I'll try to change the schemas and move on.

**Comment by brunato** [comment]
In v2.3.0 of _xmlschema_ I added a *schema* option to `Wsdl11Document` in order to provide missing or alternative XSD components. Note that this is a non-standard feature.

Best regards
