### ISSUE TITLE
Missing User-Agent causes remote URL retrieval to fail

### ISSUE THREAD

**Issue by therealprof** [sissaschool/xmlschema#351]
👋🏻 

I just noticed that `urllib` doesn't seem to set a `User-Agent` header anymore by default which causes some servers to reject delivering a schema file and instead report with a "403 Forbidden" error.

This can be easily reproduced by e.g. referring to: https://www.broadband-forum.org/cwmp/cwmp-datamodel-1-10.xsd which will cause the server to respond with a:
```
403 Forbidden

Date: Wed, 21 Jun 2023 13:59:36 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 16
Connection: close
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0acLh9OYhpkqRDSpYjIDNnGfLg81VUFWElCRqxaNeNt068mtCW50ndrRI60LXpDCb4f5hOlzfcqVJsTWA0LMlLIDUODOMFcqk8S%2FdFfe7JVBX9zCJhsl7ZFlodV8aN9g%2FUZj1KE53IjFqQ%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 7dacc5e55a18194d-FRA
alt-svc: h3=":443"; ma=86400
```

This can be fixed by changing calls to `urlopen()` using a url directly by creating a `Request` object first, adding the `User-Agent` header via `add_header()` and then passing that to `urlopen()` instead.

**Comment by brunato** [comment]
Hi,
I tried the referred site, but it seems to authorize only specific user agents, e.g.:

```pycon
>>> from urllib.request import urlopen, Request
>>> req = Request('https://www.broadband-forum.org/cwmp/cwmp-datamodel-1-10.xsd')
>>> 
>>> req.add_header('User-Agent', "Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11")
>>> urlopen(req)
<http.client.HTTPResponse object at 0x7f73c51d1f60>
>>> 
>>> req.add_header('User-Agent', "Python-urllib/3.11")
>>> urlopen(req)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
>>>
```

Also, looking at `urllib.request` source code the *OpenerDirector* class that is used for building the requests always add a User-Agent header:

```python
class OpenerDirector:
    def __init__(self):
        client_version = "Python-urllib/%s" % __version__
        self.addheaders = [('User-agent', client_version)]
        # self.handlers is retained only for backward compatibility
        self.handlers = []
        # manage the individual handlers
        self.handle_open = {}
        self.handle_error = {}
        self.process_response = {}
        self.process_request = {}
```

that is exactly "Python-urllib/3.11" in this case. In Python 2 it was different ("urllib/vvv" where vvv is the version of the old urllib library).

Infact if i try:

```python
>>> req = Request('https://www.broadband-forum.org/cwmp/cwmp-datamodel-1-10.xsd')
>>> req.add_header('User-Agent', "urllib/123")
>>> urlopen(req)
<http.client.HTTPResponse object at 0x7f48d67ba6b0>
```

Adding arguments for `XMLResource` (and then for schema classes and validation methods) requires a detailed analysis, in order to avoid adding too much complexity to the code for resolving single specific situations that can be solved also with a download of XSD source before building the schema.

Furthermore the nature of import/include of XSD sources may requires the handling of different parameters for different specific sources, so it could be better to think about more flexible solutions instead of adding arguments.

**Comment by therealprof** [comment]
Thanks for this interesting analysis. I didn't see the particular User-Agent header added in my tests and I indeed confirmed that eliminating the User-Agent header altogether causes the problem but I didn't think that the server actually discriminates certain user agents. :(

**Comment by brunato** [comment]
Probably it was done for some reason (security??) and maybe the user agent validator it's not updated anymore  ...
