### ISSUE TITLE
The namespaces in root element of (meta)schema are not decoded

### ISSUE THREAD

**Issue by kostunin** [sissaschool/xmlschema#354]
How to reproduce:

```python
import xmlschema
xmlschema.XMLSchema.meta_schema.decode('<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:test="test"> </schema>', process_namespaces=True)
Out[29]: 
{'@xmlns': 'http://www.w3.org/2001/XMLSchema',
 '@finalDefault': [],
 '@blockDefault': [],
 '@attributeFormDefault': 'unqualified',
 '@elementFormDefault': 'unqualified'}
```

expected behavior:
```python
import xmlschema
xmlschema.XMLSchema.meta_schema.decode('<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:test="test"> </schema>', process_namespaces=True)
Out[29]: 
{'@xmlns': 'http://www.w3.org/2001/XMLSchema',
 '@xmlns:test': 'test',
 '@finalDefault': [],
 '@blockDefault': [],
 '@attributeFormDefault': 'unqualified',
 '@elementFormDefault': 'unqualified'}
```

Problematic code:

https://github.com/sissaschool/xmlschema/blob/a6c98d05c8d3f2a7005c70f1054a5ce52edf7f80/xmlschema/converters/default.py#L280

The workaround I found is to replace this line with the following:
```python
if v in schema_namespaces or v == XSI_NAMESPACE or xsd_element.local_name=='schema'
```

**Comment by brunato** [comment]
Hi,

> this is an intended behavior to exclude unused namespaces from conversion

your original example includes `xmlns:test="test"` namespace that is not declared in the meta-schema, so it's discared. Validating (decoding) an XSD source with the meta-schema instance is not building a new schema using the XSD source, but it's similar to validating (decoding) an XML instance against a schema instance.


>>    About your workaround for encoding consider to use only parameters of the default converter instead creating instances for checking entries.

> If I understand correctly, I should just simply inherit XMLSchemaConverter (or subclass) and re-implement encoder/decoder methods? I have learned about this option after you mentioned it.

Yes, this is the option for a specific decode/encode cases. Converters are the objects that can shape decoded/encoded data at element level, that are the pivotal points of XML data structures.

Converter classes will be extended in the future for better handling namespace mapping, but I'll try keep compatibility of the old customizations adding optional arguments to converter API.

**Comment by kostunin** [comment]
Thanks @brunato! I think this issue can be closed.
