### ISSUE TITLE
Missing version tag

### ISSUE THREAD

**Issue by KonstantyFlint** [sissaschool/xmlschema#355]
The commit with polish translations is missing a version tag.
https://github.com/sissaschool/xmlschema/commit/a6c98d05c8d3f2a7005c70f1054a5ce52edf7f80

I suspect that it is my fault, because I have not bumped the version in configuration files.

**Comment by brunato** [comment]
Hi,
i squashed your commits into a single, but if there was a new version it should have been kept.

Anyway, which version tag exactly do you refer? (I you intend a git tag, it cannot be included in a PR)

**Comment by KonstantyFlint** [comment]
Yes. My understanding is that the tagging occurs automatically in CI based on version specified in the files. And I think I should have done something analogous to https://github.com/sissaschool/xmlschema/commit/839e28e253b950c6353dafd8e493280e83d48557.

**Comment by brunato** [comment]
No, tagging a commit is done explicitly using `git tag -a <tag>`, and also the tag must be pushed to the repo (e.g. `git push origin <tag>`).

Anyway your contribute will be included into the next release.

**Comment by KonstantyFlint** [comment]
Ok, thanks, sorry for the misunderstanding.
