### ISSUE TITLE
Question: `pprint` for an `XMLSchema`

### ISSUE THREAD

**Issue by jamesbraza** [sissaschool/xmlschema#358]
Is there a `pprint` option for printing an `XMLSchema` itself?  Currently, when I go to print a schema:

```python
In [3]: xs = xmlschema.XMLSchema("file.xsd")

In [4]: print(xs)
XMLSchema10(name='file.xsd', namespace='')

In [5]: pprint(xs)
XMLSchema10(name='file.xsd', namespace='')
```

It would be cool to somehow print the schema itself, to enable quick insights to a schema file

**Comment by brunato** [comment]
Hi,

a schema instance is not a data structure but a composite object containing/connecting often more schema objects, so pretty printing of a schema has a little sense (maybe someone can think about a graph representation instead, but this is not and will be not a feature of this package).

For having a string representation of XSD source you can use the call:

```python
xs.source.tostring()
```

or:

```python
xs.source.get_text()
```

to retrieve the original text content of the XSD source (if it's is a file, a remote resource or a string).
