### ISSUE TITLE
Creating a local copy of a remote XSD schema is broken

### ISSUE THREAD

**Issue by schmitzu** [sissaschool/xmlschema#362]
The documentation shows an example of how to convert a remote schema to a local one.
I tried it with a rather complex one:
```python
import xmlschema
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
schema = xmlschema.XMLSchema("https://repository.gdi-de.org/schemas/adv/nas/7.1/NAS-Operationen.xsd")
schema.export(target='NAS7.1.2', save_remote=True)
```
After that there are some problems using the _localized_ schema.

First, in the main schema file NAS-Operationen.xsd other schemas are imported like:
```xml
<import namespace="http://www.opengis.net/gml/3.2" schemaLocation="NAS7.1.2/schemas.opengis.net/gml/3.2.1/gml.xsd"/>
```
With this `schemaLocation` the imported file will not be found if you use NAS-Operationen.xsd from somewhere else than the parent folder of NAS7.1.2. IMHO much better:
```xml
<import namespace="http://www.opengis.net/gml/3.2" schemaLocation="./schemas.opengis.net/gml/3.2.1/gml.xsd"/>
```
Using a path relative to the importing schema file.

Second, in the schema AAA-Fachschema.xsd not all imported schemas are localized, e.g.:
```xml
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
```
The schema is still accessed remotely. So the statement from the documentation:
> With these commands, a folder my_schemas is created and contains the XSD files that can be used without access to the internet.

is not true!

**Comment by brunato** [comment]
Hi,

> With this `schemaLocation` the imported file will not be found if you use NAS-Operationen.xsd from somewhere else than the parent folder of NAS7.1.2. IMHO much better:
> 
> ```
> <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="./schemas.opengis.net/gml/3.2.1/gml.xsd"/>
> ```
> 
> Using a path relative to the importing schema file.

sure, a relative path can be better, I'll try creating the target directory and then replacing the target path with a dot.

> Second, in the schema AAA-Fachschema.xsd not all imported schemas are localized, e.g.:
> 
> ```
>   <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
> ```

the XSD import mechanism avoids the re-import of already loaded namespaces and so only the effective imported schema sources can be saved. In practice rebuilding the schema using the same initial source would load the sources in the same order, avoiding remote imports.

I will try this using a debug and the `allow='local'` option.

Replace also the schemaLocation of unused imports can be tried, but I'm not sure of the result (failed imports are not an error). In this case not loaded sources could be replaced with no location at all (removing the schemaLocation attribute in `xs:import`).

**Comment by brunato** [comment]
Hi,
v2.5.0 has a refactored schema export feature:

- Exported _schemaLocation_ attributes contain only local paths
- For default the residual imports are cleaned (_schemaLocation_ attribute is removed)

I detached the export method body as a function in a new module, intending to extend tests on this if there are specific cases.

**Comment by schmitzu** [comment]
I've tested the new version and could completely localize the aforementioned schema. 
One problem is  with http://www.w3.org/XML/1998/namespace. It is translated to:
```
<xsd:import namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation=""/>
```
The XML progs I use (e.g. xmllint from libxml2 https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html) have problems reading that. IMHO it is best to leave the URL here, because the namespace is predefined and no external schema is read.

Thank you very much for your efforts. Now I have a very valuable tool for localizing any complex schemas!

**Comment by brunato** [comment]
> I've tested the new version and could completely localize the aforementioned schema. One problem is with http://www.w3.org/XML/1998/namespace. It is translated to:
> 
> ```
> <xsd:import namespace="http://www.w3.org/XML/1998/namespace"
>       schemaLocation=""/>
> ```

I will check this case.
Maybe an idea could be introducing another argument (eg. _exclude_locations_) for managing these cases.

As the best option for exports is to operate directly on XSD sources, so substitution rules cannot be too specific.

**Comment by brunato** [comment]
Hi,
new version v3.0 includes an extra parameter for `XMLSchema.export()` that can exclude specific locations from export rewrites.

Also a new option *uri_mapper* can be provided to schema for changing the loading location without changing the original schemas (related with issue #377)..
