### ISSUE TITLE
Empty string elements are deserialized as None

### ISSUE THREAD

**Issue by da1910** [sissaschool/xmlschema#367]
Suppose you have an element defined as

`<xsd:element name="StringElement" type="xsd:string" />`

According to the XSD spec it is perfectly valid to provide the string `""` - [XSD Spec](https://www.w3.org/TR/xmlschema11-2/#string)

> The [·value space·](https://www.w3.org/TR/xmlschema11-2/#dt-value-space) of [string](https://www.w3.org/TR/xmlschema11-2/#string) is the set of finite-length sequences of zero or more [character](http://www.w3.org/TR/xml11/#dt-character)s (as defined in [[XML]](https://www.w3.org/TR/xmlschema11-2/#XML)) that [·match·](https://www.w3.org/TR/xmlschema11-2/#dt-match) the [Char](http://www.w3.org/TR/xml11/#NT-Char) production from [[XML]](https://www.w3.org/TR/xmlschema11-2/#XML).

If you provide the value `<StringElement></StringElement>` I would therefore expect, for a required string field, to receive the value `""` from the `Schema.decode()` method, instead I receive "None". Is there a reason for this difference?

**Comment by brunato** [comment]
Hi, 
the analisys for that matter is in the issue #322. For having "" instead of None you have to provide the option `keep_empty=True`.

**Comment by da1910** [comment]
Hi @brunato, thanks for the speedy reply, that solved my issue! I didn't see all the options there on the base class.
