### ISSUE TITLE
documentation or implementation of ParticleMixin.is_emptiable() seems incorrect

### ISSUE THREAD

**Issue by barsnick** [sissaschool/xmlschema#369]
The docstring mentions testing for `max_occurs == 0`, while the implementation tests `self.min_occurs == 0`. This seems weird.

https://github.com/sissaschool/xmlschema/blob/a3c1e2b49d9eb1c84c504ad44253f0e9c527ea3e/xmlschema/validators/particles.py#L62-L67

**Comment by brunato** [comment]
I will fix in v3.0, thank you

**Comment by brunato** [comment]
fixed within v3.0.0
