### ISSUE TITLE
How to use xmlschema for convert xsd to xml

### ISSUE THREAD

**Issue by catalunha** [sissaschool/xmlschema#373]
Congratulations on the brilliant computing work.
Sorry for my limited knowledge.
There are xsd files that I need to generate their xml. Can I use xmlschema for this purpose?
I don't find this in the documentation.

**Comment by brunato** [comment]
Hi, thank you for the appreciations.

XSD files are already XML files ... if you intend the generation of a valid XML for the schema expressed by the XSD files, it's not a feature supported by this library (nor it will, a feature like that it's better if it's implemented by another specific package).
