### ISSUE TITLE
Unexpected $ variable reference - XSD with a test function

### ISSUE THREAD

**Issue by sgtraptor** [sissaschool/xmlschema#375]
We are trying to validate a XML against XSD 1.1 schema, but every <xs:assert test=""/> that has a $ sign in it causes an error to be thrown. Example assert test. This works fine in Altova.

```xml
<xs:assert test="let
				$xml_file_path := string(base-uri()),
				$last_slash_pos := index-of(string-to-codepoints(upper-case(string(base-uri()))), string-to-codepoints('/'))[last()],
				$xml_file_name := substring($xml_file_path, $last_slash_pos + 1),
			
				$schema_file_location := @xsi:noNamespaceSchemaLocation,
				$schema_last_slash_pos := index-of(string-to-codepoints($schema_file_location), string-to-codepoints('/'))[last()],
				$schema_name := substring($schema_file_location, $schema_last_slash_pos + 1),
				$schema_type := substring-before(substring-after(substring-after($schema_name, '.'), '.'), '.'),
				$schema_type_upper := upper-case($schema_type),
							
				$regex_pattern := concat('^', $schema_type_upper, '_.*')
														   
				return matches($xml_file_name, $regex_pattern)">
```

**Comment by brunato** [comment]
Hi, 
the reason of the error is that the 'let' expression is an XPath 3.0+ construct.
For resolving that in release v3.0 i will add an option for using XPath 3 parser instead of the default parser XPath 2.0.

thanks

**Comment by brunato** [comment]
Hi,
with major release v3.0.0 the new option *use_path3* is available for initializing schema objects. Providing `use_path3=True` the XPath 3 processor is loaded and activated on XSD 1.1 assertions and the expression above is parsed.

Best regards
