### ISSUE TITLE
Extreme slowness

### ISSUE THREAD

**Issue by derreter** [sissaschool/xmlschema#378]
Hi,
It never hurts to congratulate you on the work done on this piece of software.

This version definitely has some problems. I was using version 2.1.1 and an xml file (saf-t PT) with +- 6Mb, it took +- 2 minutes to validate. With the current version, it takes +- 1 hour.

**Comment by brunato** [comment]
Hi,
i still testing with some saf-t PT resources:

```
# SAFTPT - StandardAuditFile for Tax Purposes
SAFTPT/SAFTPT1.04_01.xsd --version=1.1
SAFTPT/SAFT_IDEMO599999999.xml --version=1.1
SAFTPT/fxsd.xsd --version=1.1
```

but my XML sample is smaller of your and XSD schemas maybe obsolete. Maybe if you give me a link to more recent resources i will try to find where the slowness is generated.

You used v2.1.1, but the slowness already appears with v2.2.0 or only with the latest release?

thank you

**Comment by derreter** [comment]
I'll test 2.2.0 and leave feedback here.

**Comment by derreter** [comment]
I tested it right now and verified that in version 2.2.0, everything is fine, it was even faster than 2.1.1.

**Comment by brunato** [comment]
so the slowness is with v2.5.0? 
Any recent schema and sample instance for reproducing this?

**Comment by derreter** [comment]
[sample.zip](https://github.com/sissaschool/xmlschema/files/13706380/sample.zip)

**Comment by brunato** [comment]
Found the origin of the slowness: is the fix for identity keys added in v2.5.0 (fix identity keys tracking with additional full XPath checks on XML data). 

I'll check if it's possible to mitigate the loss of performances or using full XPath checks only for ambiguous cases.

**Comment by brunato** [comment]
An optimization can be applied for restoring at least the performance of previous releases. I will publish a bugfix release.

**Comment by brunato** [comment]
Release v2.5.1 is available with a fix for slow processing of key selectors.

Thank you for reporting the problem.

**Comment by derreter** [comment]
Thank you very much,
I just tested and confirmed, performance was restored.
