### ISSUE TITLE
Group definition with order "choice" is parsed falsly as complexType "sequence"  

### ISSUE THREAD

**Issue by ps-luxoft** [sissaschool/xmlschema#384]
Hi Guys,

Thank you for maintaining such a good library. While using it extensively for xsd parsing, I found a bug. 

I'm working with ASAM OpenSCENARIO (see [ASAM](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4092&token=d3b6a55e911b22179e3c0895fe2caae8f5492467)) schema v1.2 which is publicly available ([OpenSCENARIO_1.2.zip](https://github.com/sissaschool/xmlschema/files/14009084/OpenSCENARIO_1.2.zip))

Consider the following `complexType`, found in the xsd:

```xml
<xsd:complexType name="ParameterValueDistribution">
    <xsd:sequence>
	  <xsd:element name="ScenarioFile" type="File"/>
	  <xsd:group ref="DistributionDefinition"/>
    </xsd:sequence>
</xsd:complexType>
```

and the group definition:

```xml
<xsd:group name="DistributionDefinition">
    <xsd:choice>
	<xsd:element name="Deterministic" type="Deterministic"/>
	<xsd:element name="Stochastic" type="Stochastic"/>
    </xsd:choice>
</xsd:group>
```

If I parse the xsd with `xmlschema.XMLSchema(schema_path)` the group is converted falsely to `complexType` with order indicator `sequence`:

![SchemaElementNode](https://github.com/sissaschool/xmlschema/assets/154356311/cd7f6774-f416-4347-9050-4148edc952a1)

![xsd_type](https://github.com/sissaschool/xmlschema/assets/154356311/05c4bb95-f2b6-439d-9bbb-88094486e3a6)
 
This is obviously false, because only one child element is allowed! Either `Deterministic` or `Stochastic` but not both!

**Comment by ps-luxoft** [comment]
Hi @brunato,

Thank you for checking it and guiding me in the right direction. Indeed I had to switch to the `content` of the `XsdElement` because this is the only object where the proper order indicator is stored. So it's definitely not a bug.

I have to iterate over the whole schema recursively and select only one or all the children depending on the order indicator (`sequence, choice, all`). After spending 3 days, I was able to implement it using the `content`. However, there are two issues I would like to clarify.

**Comment by ps-luxoft** [comment]
**Issue2**
Consider the XsdElement with the following path: `/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup/Maneuver`

```python
schema = xmlschema.XMLSchema("resources/schema/open-scenario/OpenSCENARIO_1.2.xsd")
rs = schema.findall("//Storyboard/Story/Act/ManeuverGroup")
man_group = rs[0]
print(f"xpath: {man_group.xpath_node.path}")
maneuver = man_group[-1]
print(f"xpath: {maneuver.xpath_node.path}")
for child in maneuver:
    print(f"xpath: {child.xpath_node.path}")
```

Output
```text
xpath: /{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup
xpath: /{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup/Maneuver
xpath: /{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Maneuver/ParameterDeclarations
xpath: /{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Maneuver/Event
```

Why the children of `maneuver` have a different xpath? I would have expected
`/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup/Maneuver/ParameterDeclarations`
`/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup/Maneuver/Event`

**Comment by ps-luxoft** [comment]
Hi @brunato,

Any news or explanation, why the two issues exist?

**Comment by brunato** [comment]
About the **issue 1**: each distinct element that is found by the path expression a child in a content of a global `xs:complexType` definition (except in one case), so has no ancestors:

```pycon
>>> for e in set(schema.findall(path="//ParameterDeclarations")):
...    print(e.findall('ancestor-or-self::*'))
... 
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
[Xsd11Element(name='ParameterDeclarations', occurs=[0, 1])]
```

examining the XSD ancestors:

```pycon
>>> for e in set(schema.findall(path="//ParameterDeclarations")):
...    print(e.parent, e.parent.parent)
... 
Xsd11Group(model='all', occurs=[1, 1]) Xsd11ComplexType(name='Environment')
Xsd11Group(model='sequence', occurs=[1, 1]) Xsd11ComplexType(name='Maneuver')
Xsd11Group(model='all', occurs=[1, 1]) Xsd11ComplexType(name='Vehicle')
Xsd11Group(model='all', occurs=[1, 1]) Xsd11ComplexType(name='MiscObject')
Xsd11Group(model='all', occurs=[1, 1]) Xsd11ComplexType(name='Controller')
Xsd11Group(model='sequence', occurs=[1, 1]) Xsd11ComplexType(name='Story')
Xsd11Group(name='ScenarioDefinition', model='sequence', occurs=[1, 1]) None
Xsd11Group(model='all', occurs=[1, 1]) Xsd11ComplexType(name='Pedestrian')
Xsd11Group(model='sequence', occurs=[1, 1]) Xsd11ComplexType(name='Route')
Xsd11Group(model='sequence', occurs=[1, 1]) Xsd11ComplexType(name='Trajectory')
```

These ten are the only elements in the schema that have name='ParameterDeclarations'.

The paths that you report are the paths of the XPath node tree:

```pycon
>>> for e in set(schema.findall(path="//ParameterDeclarations")):
...    print(e.xpath_node.path)
... 
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Environment/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Maneuver/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Vehicle/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/MiscObject/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Controller/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Storyboard/Story/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenScenario/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Pedestrian/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Route/ParameterDeclarations
/{http://www.w3.org/2001/XMLSchema}schema/OpenSCENARIO/Catalog/Trajectory/ParameterDeclarations
```

But the paths of the node tree are not necessarily the same of the XSD elements in the schema, the node tree is substantially an extension of the schema structure (particularly in this case where the elements are all declared in global complex types or groups).

A schema is a complex graph with references and an expansion with root descendant operator '//' might not follow the same path that you expected in the XML document. Also the '//' operator cannot returns the same node twice, repetitions are discarded.

**Comment by ps-luxoft** [comment]
Hi @brunato,

Thank you for the explanation. I understand that the XSD tree in the schema is different from the Xpath node tree.  I ended up implementing my own function that finds all possible xpaths, where a given XSDElement name shows up.

For example, for `Condition` it returns
```
/OpenSCENARIO/Storyboard/Story/Act/StartTrigger/ConditionGroup/Condition
/OpenSCENARIO/Storyboard/Story/Act/ManeuverGroup/Maneuver/Event/StartTrigger/ConditionGroup/Condition
/OpenSCENARIO/Storyboard/Story/Act/StopTrigger/ConditionGroup/Condition
/OpenSCENARIO/Storyboard/StopTrigger/ConditionGroup/Condition
```
