### ISSUE TITLE
Request: Recommendation for where to get support

### ISSUE THREAD

**Issue by velle** [sissaschool/xmlschema#389]
There is a _Support_ section in your docs ([link](https://xmlschema.readthedocs.io/en/latest/intro.html#support)), but it only points to the issue tracker. Normally support questions are not welcome in the github issue tracker. 

Is there any recommended / official place where I can ask a question? A mailing list? StackOverflow.com?

Have you considered enabling GitHub Disussions? I think that works quite well for other projects. 

Best regards.

**Comment by brunato** [comment]
> Is there any recommended / official place where I can ask a question?

Hi, not yet. 

I'll examine GitHub Discussions as you suggested. Have you a pair of links to projects that use them?

Best regards

**Comment by velle** [comment]
Cool :) Right now I can only remember these two:
- https://github.com/ruby/rake/discussions
- https://github.com/jekyll/jekyll/discussions

**Comment by brunato** [comment]
Support section has been updated, referencing to Discussions section.
Thank you
