### ISSUE TITLE
issue with handling xml structure

### ISSUE THREAD

**Issue by hyperfra** [sissaschool/xmlschema#394]
I have an issue parsing  xml files  because the `xmlschema` library is using the namespace prefix ("schemaLocation") used in the `xmlns` declaration ("xmlns:schemaLocation") to build keys for the dictionary. 
This is a peculiar behavior as "schemaLocation" is not actually a namespace I have defined for any elements—it's part of the namespace definitions syntax. In one file, "schemaLocation" is explicitly defined as a non-standard attribute of AuditFile, and the library does not treat it as a namespace. However, in another file, "schemaLocation" is defined in the `xmlns` attribute (i.e., it's defined as an XML namespace), and the library treats it as such.

**Comment by brunato** [comment]
Hi,
it's pretty unusual to use `schemaLocation` as a prefix, anyway this have to be checked. I need a reference of where to find that schema case, or a similar one.

Thank you

**Comment by hyperfra** [comment]
agreed. But unfortunately this what they did (generated by commercial software)

<AuditFile  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:schemaLocation="urn:OECD:StandardAuditFile-Tax:PT_1.04_01" xmlns="urn:OECD:StandardAuditFile-Tax:PT_1.04_01">

**Comment by hyperfra** [comment]
'AuditFile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:OECD:StandardAuditFile-Tax:PT_1.04_01 ../schemas/SAF-T.xsd" xmlns="urn:OECD:StandardAuditFile-Tax:PT_1.04_01"

**Comment by brunato** [comment]
Sorry but I still don't understand where is the problem. I need a concrete case or a more detailed description for analyzing it.
The version of SAF-T schema that I use for extended tests does not contain any weird usage of *schemaLocation* attribute.

**Comment by hyperfra** [comment]
I can send you via zip two xml files and 3
lines of code if that is ok?

Sent from my iPhone

On 13 Mar 2024, at 07:49, Davide Brunato ***@***.***> wrote:

﻿

Sorry but I still don't understand where is the problem. I need a concrete case or a more detailed description for analyzing it.
The version of SAF-T schema that I use for extended tests does not contain any weird usage of schemaLocation attribute.

**Comment by brunato** [comment]
okay, you can send me this archive

**Comment by hyperfra** [comment]
[test.zip](https://github.com/sissaschool/xmlschema/files/14587425/test.zip)

Here the zip with two xml files (and the xsd). test with both and see differeneces in keys:

`schema_file_path = join(application_path, 'saftpt1.04_01.xsd')
my_schema = xmlschema.XMLSchema11(schema_file_path)
data = my_schema.to_dict(args, decimal_type=str)
data.keys()`
