### ISSUE TITLE
write/edit xml using xsd with xmlschema

### ISSUE THREAD

**Issue by chenkianwee** [sissaschool/xmlschema#395]
Hi as the title suggest I am trying to write/edit xml using xsd with xmlschema.  I am not very familiar with xml and xsd, I am using this xsd (https://github.com/NREL/bcl-gem/blob/develop/schemas/v3/measure_v3.xsd) and this xml file [measure.zip](https://github.com/sissaschool/xmlschema/files/14641820/measure.zip)

```
schema = xmlschema.XMLSchema(xsd_path)
print(schema.is_valid(xml_path))
d = xmlschema.to_json(xml_path, schema=schema)
d = schema.to_dict(xml_path)
print(d)
json_data = json.dumps(d)
xml = xmlschema.from_json(json_data, schema=schema, preserve_root=True)
```
However I keep getting this error 
```
  File "/home/lib/python3.12/site-packages/xmlschema/validators/schemas.py", line 2245, in encode
    for result in self.iter_encode(obj, path, validation, *args, **kwargs):
  File "/home/lib/python3.12/site-packages/xmlschema/validators/schemas.py", line 2229, in iter_encode
    raise XMLSchemaEncodeError(self, obj, self.elements, reason, namespaces=namespaces)
xmlschema.validators.exceptions.XMLSchemaEncodeError: failed validating <class 'dict'> instance with XMLSchema10(name='measure_v3.xsd', namespace=''):

Reason: unable to select an element for decoding data, provide a valid 'path' argument.
```

The issue is very similar to #241. In the issue you suggested.

> it's a matter of namespaces, despite there is no prefix the data are still bound to namespace of the schema:

you get the namespace from the xsd by using the command. However, the xsd provided to me does not have a target_namespace. 

```
>>> CAPSchema.target_namespace
'urn:oasis:names:tc:emergency:cap:1.2'
```
I cannot figure out how to translate the solution you have given in the previous issue for my case. I am not very familiar with xml and xsd, hope I am not missing something that is very obvious here. Thanks

**Comment by brunato** [comment]
Hi,
the *preserve_root* argument, applicable to the default converter, has to be provided both in decode and in encode.
So your case can be rewritten as:

```pycon
>>> import xmlschema
>>> import json
>>> schema = xmlschema.XMLSchema("measure_v3.xsd")
>>> xml_path = 'measure.xml'
>>> 
>>> d = schema.to_dict(xml_path, preserve_root=True)
>>> json_data = json.dumps(d)
>>> xmlschema.to_json(xml_path, schema=schema, preserve_root=True) == json_data
True
>>> xmlschema.from_json(json_data, schema=schema, preserve_root=True)
<Element 'measure' at 0x7fb90035c040>
```

without a `preserve_root=True` the decode cuts the top level element (measure). The schema _measure_v3.xsd_ is full of
potential root elements, so without the effective root the automatic match does not happen (it's still not so smart ...), so you have to provide a path:

```pycon
>>> d = schema.to_dict(xml_path)
>>> json_data = json.dumps(d)
>>> xmlschema.to_json(xml_path, schema=schema) == json_data
True
>>> xmlschema.from_json(json_data, schema=schema, path='measure')
<Element 'measure' at 0x7fb90034ac50>
```

No namespace map is needed in your case. Furthermore version 3 of the package is able to retrieve namespace declarations from decoded data if they are processed and included by the used convention (converter type in xmlschema ...).

> Reason: unable to select an element for decoding data, provide a valid 'path' argument.

N.B. found a typo in the above error message ... maybe it's *encoding data*
