### ISSUE TITLE
defaultOpenContent and minOccurs produces validation errors

### ISSUE THREAD

**Issue by bradh** [sissaschool/xmlschema#397]
I'm trying to perform validation using a schema that combines `defaultOpenContent` interleave and `minOccurs` of 0. That doesn't seem to work well.

This is a minimised example:

```
import xmlschema

print(xmlschema.__version__)

soddxa = xmlschema.XMLSchema11('''
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified"
    vc:minVersion="1.1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns="urn:us:mil:nga:ntb:soddxa"
    targetNamespace="urn:us:mil:nga:ntb:soddxa">
    <xs:defaultOpenContent mode="interleave">
        <xs:any />
    </xs:defaultOpenContent>
    <xs:complexType name="SecurityDataType">
        <xs:sequence>
            <xs:element name="smRestrictedCollection" type="xs:boolean" minOccurs="0" />
            <xs:element name="accmClassification" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="spaceObjectDescriptionData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="securityData" type="SecurityDataType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
''')

print()
print("with optional element")
soddxa.validate('''
<spaceObjectDescriptionData xmlns="urn:us:mil:nga:ntb:soddxa">
    <securityData>
        <smRestrictedCollection>false</smRestrictedCollection>
        <accmClassification>text</accmClassification>
    </securityData>
</spaceObjectDescriptionData>
''')

print()
print("without optional element")
soddxa.validate('''
<spaceObjectDescriptionData xmlns="urn:us:mil:nga:ntb:soddxa">
    <securityData>
        <accmClassification>text</accmClassification>
    </securityData>
</spaceObjectDescriptionData>
''')
```

When I run that, I get:

```
3.2.0

with optional element

without optional element
Traceback (most recent call last):
  File "/home/bradh/coding/py-nitf-hack/./xmlschema_test.py", line 44, in <module>
    soddxa.validate('''
  File "/home/bradh/.cache/pypoetry/virtualenvs/py-nitf-hack-liZRLP3j-py3.11/lib/python3.11/site-packages/xmlschema/validators/schemas.py", line 1702, in validate
    raise error
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{urn:us:mil:nga:ntb:soddxa}accmClassification' at 0x70f0a3687600> with Xsd11AnyElement(namespace=('##any',), process_contents='strict', occurs=[0, None]):

Reason: element '{urn:us:mil:nga:ntb:soddxa}accmClassification' not found

Schema component:

  <xs:any xmlns:xs="http://www.w3.org/2001/XMLSchema" />

Instance type: <class 'xml.etree.ElementTree.Element'>

Instance:

  <accmClassification xmlns="urn:us:mil:nga:ntb:soddxa">text</accmClassification>

Path: /spaceObjectDescriptionData/securityData/accmClassification
```

Given the `minOccurs="0"` part on `smRestrictedCollection`, I think they should both be fine.

The validation error  does not occur without the
```
    <xs:defaultOpenContent mode="interleave">
        <xs:any />
    </xs:defaultOpenContent>
```
setting.

**Comment by brunato** [comment]
It's that part of the code that requires a fix:

https://github.com/sissaschool/xmlschema/blob/3608106f7661182afdcb21b193f4d326b570bf01/xmlschema/validators/groups.py#L971-L985

Refining the check may not fix the validation in all cases. After examining the formal rules in "[3.4.4.3 Element Sequence Locally Valid (Complex Content)](https://www.w3.org/TR/xmlschema11-1/#sec-cvc-complex-content)" the solution should be the validation with a dummy model group that contains the complexType model and the openContent particle (a _xs:sequence_ group if the mode is **suffix** or _xs:all_ if mode is **interleave**).

**Comment by brunato** [comment]
The release v3.2.1 includes a fix for this. The _openContent_ 'interleave' mode is now included in the model of the group ( using a dummy `xs:all` group as the root group of the model).

It seems to work well also with child groups that have different model (sequence or choice). I would rewrite also the 'suffix' mode in the same way, but some cases with `xs:sequence` root and `xs:all` children still don't works .

Anyway the suffix mode is simpler, and shouldn't require a fix.

**Comment by bradh** [comment]
> The release v3.2.1 includes a fix for this. The _openContent_ 'interleave' mode is now included in the model of the group ( using a dummy `xs:all` group as the root group of the model).

Thanks - appreciated.

**Comment by brunato** [comment]
In v3.3.0 the processing of _openContent_ has been improved with the usage of new _InterleavedModelVisitor_ and _SuffixedModelVisitor_ classes. Probably the is something that have to be fixed but it could be the right way to handle the validation of open content.

**Comment by brunato** [comment]
I close the issue, considering that resolved through the usage of _InterleavedModelVisitor_ and _SuffixedModelVisitor_. Reopen if you still have problems on this.
