### ISSUE TITLE
GitHub shows 3.3.1 as latest version, not 3.3.2

### ISSUE THREAD

**Issue by gruenich** [sissaschool/xmlschema#415]
There is a misconfiguration in your releases at GitHub. It shows still 3.3.1 as being the latest version:

![image](https://github.com/user-attachments/assets/c4020cde-b213-4b07-937b-04ef52654863)

And at your front page:
![image](https://github.com/user-attachments/assets/60bc5e6d-05ad-442d-b78a-efb1386cb237)

**Comment by brunato** [comment]
Set the latest to v3.3.2. Thanks
