### ISSUE TITLE
py313 tox env does not depend on lxml, but py314 (implicit) does?

### ISSUE THREAD

**Issue by hroncok** [sissaschool/xmlschema#423]
Hello,

when we attempted to build+test xmlschema with Python 3.14.0a1 in Fedora, I realized a strange thing.

lxml is required for all test envs (including implicit ones, as py314), except py313.

What is the idea behind that?

Perhaps this was a temporary workaround that can be dropped now for Python 3.13?

**Comment by brunato** [comment]
Hi, 
yes this was a workaround added when Python 3.13 was still in beta, because lxml's pre-build binaries were not available, with next release I will align py313 to the base config that includes lxml as well.

**Comment by brunato** [comment]
Changed with v3.4.3: now py313 installs also lxml. Added tests for Python 3.14-alpha in GH Workflow. For tox added py314 aswell but obviously lxml requires devel packages for libxml2, libxslt and Python for building the binaries.
