### ISSUE TITLE
Unable to detect invalid year values with less than four digits

### ISSUE THREAD

**Issue by Lishang123** [sissaschool/xmlschema#426]
I found out that xmlschema is unable to detect values of xs:gYear that are less than four digits. For example, the value "500" is considered valid for xs:gYear by xmlschema, although according to the [xsd standard](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#nt-yrFrag), gYear must have at least four digits, such that "0500" is valid, but "500" is invalid.

The four-digit-year rule is implemented in Xerces, Saxon and xmllint. 

The same problem applies to all xsd built-in types that contain a year value, such as xs:gYearMonth, xs:date, etc.

The issue happens with both `xmlschema.XMLschema10` and `xmlschema.XMLschema11`.

Tested with `xmlschema 3.4.3`

**Comment by brunato** [comment]
Hi,
I've tried  to reproduce the issue but both the XSD datatype and the builtin XSD type in elementpath and both report "500" ad invalid:

```pycon
>>> import xmlschema
>>> xmlschema.XMLSchema.meta_schema.build()
>>> gyear = xmlschema.XMLSchema.meta_schema.types['gYear']
>>> gyear.is_valid('0500')
True
>>> gyear.is_valid('500')
False
>>> from elementpath.datatypes import GregorianYear10, GregorianYear
>>> GregorianYear.is_valid('0500')
True
>>> GregorianYear.is_valid('500')
False
>>> GregorianYear10.is_valid('500')
False
```

could you give me the *elementpath* version installed and more details about the wrong behavior.

thank you

**Comment by Lishang123** [comment]
Sorry, I think I forgot to call check the is_valid() function. I will close this issue.

**Comment by Lishang123** [comment]
Issue is non-existing.
