### ISSUE TITLE
Enhancement Request: Apache Arrow

### ISSUE THREAD

**Issue by davlee1972** [sissaschool/xmlschema#49]
Here's an idea I think that will make this package a lot more flexible..

Could we serialize the python objects to Apache Arrow objects?
https://arrow.apache.org/docs/python/index.html
https://arrow.apache.org/docs/python/data.html

Apache Arrow is a cross-language development platform for in-memory data. It specifies a standardized language-independent columnar memory format for flat and hierarchical data, organized for efficient analytic operations on modern hardware. It also provides computational libraries and zero-copy streaming messaging and interprocess communication. Languages currently supported include C, C++, Java, JavaScript, Python, and Ruby.

Once data is in Arrow format you can use Arrow's built in libraries to convert memory to a variety of other formats including JSON, Parquet and Pandas.

**Comment by davlee1972** [comment]
Well I was able to serialize a python dictionary to an Apache Arrow memory buffer, save it to a file, read it back, etc..  However it looks like arrow functionality to convert memory to JSON / Parquet haven't made it from C++ to Python yet.. I had to convert OrderedDict to Dict and Decimals to Floats first which aren't supported by Arrow.

```
from collections import OrderedDict
import decimal
import pyarrow as pa
import pyarrow.parquet as pq

def ordereddict_to_dict(value):
    for k, v in value.items():
        if isinstance(v, decimal.Decimal):
            value[k] = float(v)
        elif isinstance(v, dict):
            value[k] = ordereddict_to_dict(v)
        elif isinstance(v, list):
            value[k] = array_convert(v)
    return dict(value)

def array_convert(value):
    for i, v in enumerate(value):
        if isinstance(v, decimal.Decimal):
            value[i] = float(v)
        elif isinstance(v, dict):
            value[i] = ordereddict_to_dict(v)
        elif isinstance(v, list):
            value[i] = array_convert(v)
    return value

def _serialize_MyData(val):
    if isinstance(val, decimal.Decimal):
        return float(val)
    if isinstance(val, OrderedDict):
        ordereddict_to_dict(val)
    if isinstance(val, list):
        array_convert(val)
    return(val)

with open('test.dat', 'wb') as f:
    f.write(arrow_memory)

mmap = pa.memory_map('test.dat')
arrow_buffer = mmap.read_buffer()

pa.deserialize(arrow_buffer)
```

**Comment by davlee1972** [comment]
The more I think about this I think we should try to create a my_schema.to_arrow() function.
Python Dictionaries are essentially unstructured. If you have a bunch of python None values they aren't exactly typed as ints and strings, etc..

Arrow memory objects follow a schema and the cool thing about it is that you get other features like memory pooling across servers, memory access via an address which can be shared with other Arrow compatible applications written in Java, C and R, etc.. Low level APIs to write Arrow memory to files in different formats are also available.

https://arrow.apache.org/docs/python/data.html

I took the default collections.xml and collections.xsd example and converted it manually to an arrow object.

>>> import xmlschema
>>> from pprint import pprint
>>> xs = xmlschema.XMLSchema('xmlschema/tests/cases/examples/collection/collection.xsd')
>>> xs_dict = xs.to_dict('xmlschema/tests/cases/examples/collection/collection.xml')
>>>
>>> import pyarrow as pa
>>> from datetime import datetime
>>>
>>> personType = pa.struct([pa.field('@id',pa.string()), pa.field('name',pa.string()), pa.field('born',pa.date64()), pa.field('dead',pa.date64()), pa.field('qualification',pa.string())])
>>>
>>> objType = pa.struct([pa.field('@Id',pa.string()), pa.field('@available',pa.bool_()), pa.field('position',pa.int32()), pa.field('title',pa.string()), pa.field('year',pa.string()), pa.field('author',personType), pa.field('estimation', pa.float32()), pa.field('characters', pa.list_(personType))])
>>>
>>> xs_dict['object'][0]['author']['born'] = datetime.strptime(xs_dict['object'][0]['author']['born'],"%Y-%m-%d")
>>> xs_dict['object'][1]['author']['born'] = datetime.strptime(xs_dict['object'][1]['author']['born'],"%Y-%m-%d")
>>> xs_dict['object'][0]['author']['dead'] = datetime.strptime(xs_dict['object'][0]['author']['dead'],"%Y-%m-%d")
>>> xs_dict['object'][1]['author']['dead'] = datetime.strptime(xs_dict['object'][1]['author']['dead'],"%Y-%m-%d")
>>>
>>> object = pa.array(xs_dict['object'], type=objType)
>>> object
<pyarrow.lib.StructArray object at 0x7f9dc5237bd8>
[
  {'@Id': None, '@available': True, 'position': 1, 'title': 'The Umbrellas', 'year': '1886', 'author': {'@id': 'PAR', 'name': 'Pierre-Auguste Renoir', 'born': datetime.date(1841, 2, 25), 'dead': datetime.date(1919, 12, 3), 'qualification': 'painter'}, 'estimation': 10000.0, 'characters': None},
  {'@Id': None, '@available': True, 'position': 2, 'title': None, 'year': '1925', 'author': {'@id': 'JM', 'name': 'Joan Mir▒', 'born': datetime.date(1893, 4, 20), 'dead': datetime.date(1983, 12, 25), 'qualification': 'painter, sculptor and ceramicist'}, 'estimation': None, 'characters': None}
]

As you can see the arrow object includes characters which is None in both objects
Going back to Python also includes the additional elements not in the XML file.

>>> object.to_pylist()
[{'@Id': None, '@available': True, 'position': 1, 'title': 'The Umbrellas', 'year': '1886', 'author': {'@id': 'PAR', 'name': 'Pierre-Auguste Renoir', 'born': datetime.date(1841, 2, 25), 'dead': datetime.date(1919, 12, 3), 'qualification': 'painter'}, 'estimation': 10000.0, 'characters': None}, {'@Id': None, '@available': True, 'position': 2, 'title': None, 'year': '1925', 'author': {'@id': 'JM', 'name': 'Joan Mir▒', 'born': datetime.date(1893, 4, 20), 'dead': datetime.date(1983, 12, 25), 'qualification': 'painter, sculptor and ceramicist'}, 'estimation': None, 'characters': None}]

Still trying to figure out how to get Arrow to write Arrow memory buffers to JSON, Parquet and other formats.

Looks like there is a project to read in JSON as Arrow and output Parquet if you have an Arrow Schema object to inject..
https://github.com/andrewgross/json2parquet

**Comment by brunato** [comment]
I think that some thing could be tried with a custom `dict_class` that internally manage a pyarrow struct and a custom `list_class` based on a pyarrow array. 

Not a fully Arrow Schema maybe needed for this, only a map from XSD builtins types to Arrows datatypes. The _**json2parquet**_ package needs an Arrow Schema object to convert data because It hasn't an XSD as support and XML Schema as the base.

About the `None` values I'm confident that they can also be managed by the converter class (or maybe it's a bug of this library ...).
 
I will return on this after the 22th of April trying some tests also with your ParquetConverter. I've some urgent things to complete until that date.

**Comment by davlee1972** [comment]
I put the parqconverter with other features in:

https://github.com/davlee1972/xml_to_json

Eventually I would like to generate an Apache Parquet file out of this..

JSON works, but Parquet is way better for Spark and other packages.
https://databricks.com/blog/2015/02/02/an-introduction-to-json-support-in-spark-sql.html

**Comment by davlee1972** [comment]
I started working with pyarrow extensively this past week and it turns out it does support multi level nesting. Going to try to reproduce a test example.

https://arrow.apache.org/docs/python/generated/pyarrow.lib.DictionaryArray.html#pyarrow.lib.DictionaryArray.from_arrays

https://arrow.apache.org/docs/python/api.html

A. Generate a arrow schema using collections.xsd.
B. Read collections.xml into numpy objects based on xsd
C. Convert numpy objects into pyarrow arrays, columns and a final pyarrow table.

From there you can use pyarrow functions to create a dict, panda or save it to a parquet file. Parquet is basically json saved with a schema definition in a columnar layout with dictionary encoding and columnar compression. Arrow is already memory efficient, but you can also periodically dump results to parquet to free up memory as well.

In my current situation I’m using pyarrow to read multiple json files generated by xmlschema, reformatting some data into a 6 column by 10 million row arrow table, temporarily saving results to a 25 meg parquet file and finally merging all the parquet files into a single 250 meg parquet file which has 100 million+ records.

**Comment by davlee1972** [comment]
Ok.. More testing results..

`import xmlschema
from pprint import pprint
xs = xmlschema.XMLSchema('xmlschema/tests/cases/examples/collection/collection.xsd')
xs_dict = xs.to_dict('xmlschema/tests/cases/examples/collection/collection.xml')

xs_dict['object'][0]['author']['born'] = datetime.strptime(xs_dict['object'][0]['author']['born'],"%Y-%m-%d")
xs_dict['object'][1]['author']['born'] = datetime.strptime(xs_dict['object'][1]['author']['born'],"%Y-%m-%d")
xs_dict['object'][0]['author']['dead'] = datetime.strptime(xs_dict['object'][0]['author']['dead'],"%Y-%m-%d")
xs_dict['object'][1]['author']['dead'] = datetime.strptime(xs_dict['object'][1]['author']['dead'],"%Y-%m-%d")

import pyarrow as pa
from datetime import datetime

personType = pa.struct([pa.field('@id',pa.string()), pa.field('name',pa.string()), pa.field('born',pa.date32()), pa.field('dead',pa.date32()), pa.field('qualification',pa.string())])

objType = pa.struct([pa.field('@Id',pa.string()), pa.field('@available',pa.bool_()), pa.field('position',pa.int32()), pa.field('title',pa.string()), pa.field('year',pa.string()), pa.field('author',personType), pa.field('estimation', pa.float32()), pa.field('characters', pa.list_(personType))])

object = pa.array(xs_dict['object'], type=objType)

table = pa.Table.from_arrays([object], ["object"])

xs_dict_new = table.to_pydict()

>>> table.num_rows
2

>>> table.column(0)
<pyarrow.lib.Column object at 0x7f64ab243cf0>
chunk 0: <pyarrow.lib.StructArray object at 0x7f65032e2138>
[
  {'@Id': None, '@available': True, 'position': 1, 'title': 'The Umbrellas', 'year': '1886', 'author': {'@id': 'PAR', 'name': 'Pierre-Auguste Renoir', 'born': datetime.date(1841, 2, 25), 'dead': datetime.date(1919, 12, 3), 'qualification': 'painter'}, 'estimation': 10000.0, 'characters': None},
  {'@Id': None, '@available': True, 'position': 2, 'title': None, 'year': '1925', 'author': {'@id': 'JM', 'name': 'Joan Mir▒', 'born': datetime.date(1893, 4, 20), 'dead': datetime.date(1983, 12, 25), 'qualification': 'painter, sculptor and ceramicist'}, 'estimation': None, 'characters': None}
]

>>> table.schema
object: struct<@Id: string, @available: bool, position: int32, title: string, year: string, author: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>, estimation: float, characters: list<item: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>>>
  child 0, @Id: string
  child 1, @available: bool
  child 2, position: int32
  child 3, title: string
  child 4, year: string
  child 5, author: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>
      child 0, @id: string
      child 1, name: string
      child 2, born: date32[day]
      child 3, dead: date32[day]
      child 4, qualification: string
  child 6, estimation: float
  child 7, characters: list<item: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>>
      child 0, item: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>
          child 0, @id: string
          child 1, name: string
          child 2, born: date32[day]
          child 3, dead: date32[day]
          child 4, qualification: string

>>> xs_dict['object']
[{'@id': 'b0836217462', '@available': True, 'position': 1, 'title': 'The Umbrellas', 'year': '1886', 'author': {'@id': 'PAR', 'name': 'Pierre-Auguste Renoir', 'born': datetime.datetime(1841, 2, 25, 0, 0), 'dead': datetime.datetime(1919, 12, 3, 0, 0), 'qualification': 'painter'}, 'estimation': Decimal('10000.00')}, {'@id': 'b0836217463', '@available': True, 'position': 2, 'title': None, 'year': '1925', 'author': {'@id': 'JM', 'name': 'Joan Mir▒', 'born': datetime.datetime(1893, 4, 20, 0, 0), 'dead': datetime.datetime(1983, 12, 25, 0, 0), 'qualification': 'painter, sculptor and ceramicist'}}]
>>> xs_dict_new
OrderedDict([('object', [{'@Id': None, '@available': True, 'position': 1, 'title': 'The Umbrellas', 'year': '1886', 'author': {'@id': 'PAR', 'name': 'Pierre-Auguste Renoir', 'born': datetime.date(1841, 2, 25), 'dead': datetime.date(1919, 12, 3), 'qualification': 'painter'}, 'estimation': 10000.0, 'characters': None}, {'@Id': None, '@available': True, 'position': 2, 'title': None, 'year': '1925', 'author': {'@id': 'JM', 'name': 'Joan Mir▒', 'born': datetime.date(1893, 4, 20), 'dead': datetime.date(1983, 12, 25), 'qualification': 'painter, sculptor and ceramicist'}, 'estimation': None, 'characters': None}])])
`
As you can see xs_dict_new includes None values for the schema elements which are missing, but more importantly the arrow table includes a schema definition which says characters: None is supposed to be a list "child 7, characters: list<item: struct<@id: string, name: string, born: date32[day], dead: date32[day], qualification: string>>"

I tried to write this to a parquet file (schema + data together), but it errored out:
`import pyarrow.parquet as pq

pq.write_table(table, 'test.parquet', compression='snappy', use_dictionary=True)

pyarrow.lib.ArrowInvalid: Nested column branch had multiple children
`
Writing out nested data is being worked on so hopefully this is available soon.
https://jira.apache.org/jira/browse/ARROW-2587
https://github.com/apache/parquet-cpp/pull/462

**Comment by davlee1972** [comment]
Here's some new developments. XML to Arrow should be the target for this library especially when Python underyling data structures (list, dict, pandas, etc.) are moving to Arrow under the hood.

https://ursalabs.org/tech/

With Arrow as our runtime memory format for analytics and interchange, we must be able to convert between various popular storage and raw data input formats, and back.

For file formats, these include, but are not limited to:
•CSV / Delimited Files
•JSON
•Apache Parquet: Popular columnar file format
•Apache ORC: Another Parquet-esque columnar data support, with good support i
•Apache Avro: Dynamic serialization format designed for RPC in the Hadoop ecosystem
•HDF5: Popular scientific data format for storing large array data

**Comment by brunato** [comment]
I'm confident to try for this soon, but I want to close the opened questions about encoding before.

Recent releases have some small modifications on converters, that are now in a full version for decoding and encoding. Put your attention on converter characteristic in comparison with XML, that I've syntetized with two class properties *lossless* and *losslessly* (eg. the `BadgerFishConverter` can be lossless, the `ParkerConverter` is not lossless and the `JsonMLConverter` is losslessly).

**Comment by brunato** [comment]
Enhancements are related to #159, so close this because it's connected to an old version.
