### ISSUE TITLE
Support xsd 1.1 validation

### ISSUE THREAD

**Issue by mzfr** [sissaschool/xmlschema#75]
I am using this module to validate addon manifests for an open-source project(as part of my GSoC). Most of my logic used [here](https://github.com/xbmc/addon-check/pull/35) can easily be removed if we can validate schema with XSD 1.1

So, I am willing to know that how far does this module supports XSD 1.1 schema validation ?  And is there any time-line for addition of complete support of XSD 1.1 ?

**Comment by brunato** [comment]
I need to complete the encoding part first, indicatively before the end of august. Then the XSD 1.1 devel could restart. I've already added extra classes for this and implemented the most difficult part (XPath 2.0, necessary for assertions). I'm confident to complete a first version a XSD 1.1 validator (XMLSchema11 class) before the end of the year.

**Comment by andreafonso** [comment]
@brunato are you still planning to bring XSD 1.1 to xmlschema? This would be very important, as it will be the first Python package to support XSD version 1.1.

**Comment by brunato** [comment]
Yes, XSD 1.1 is the next development target. The XMLSchema_11 development class is already added in tests and XSD 1.1 builtin types and facets are already implemented. Now I'm working for implementing assertions for complex types.

**Comment by egberts** [comment]
Do I post a new issue with regard to various functions being obsoleted in Python 3.8 or in this issue?

**Comment by brunato** [comment]
Some delay in XSD 1.1 validation completion. In the last two months I've worked mainly on date/time XSD builtin atomic types conversion, that are necessary for XSD 1.1 assertions. XSD datatypes included in elementpath-1.1, published some days ago, but some modifications are still needed for integrating these in the xmlschema package.

So the first XSD 1.1 support on xmlschema is postponed to the end of february.

**Comment by brunato** [comment]
A brief current development status of XSD 1.1 features:
  * All model extended for content groups
  * Assertions for simple types
  * Default attributes for complex types
  * Alternative type for elements
  * Inheritable attributes
  * TODO targetNamespace for restricted element and attributes
  * TODO: Assert for complex types
  * TODO: OpenContent for complex types
  * TODO: schema overrides

Some links to XSD 1.1 schemas that I can use to test those features would be an help.
Thanks

**Comment by andreafonso** [comment]
@brunato you can look at these tax reporting system which uses XSD 1.1:

http://info.portaldasfinancas.gov.pt/apps/saft-pt04/SAFTPT1.04_01.xsd

And corresponding XML demo file:

http://info.portaldasfinancas.gov.pt/apps/saft-pt01/local/SAFT_IDEMO599999999.xml

Hope it helps!

**Comment by jonathanrobie** [comment]
Do you know about the XML Schema Test Suite?

https://github.com/w3c/xsdtests

**Comment by brunato** [comment]
> Do you know about the XML Schema Test Suite?
> 
> https://github.com/w3c/xsdtests

I knew about that recently. I will write a script to use for testing xmlschema. 

There is also a W3C test repo for XPath (https://github.com/w3c/qt3tests), that is interesting for testing the package that parses XPath for xmlschema. XPath 2.0 is one of the most difficult parts to complete. Currently I'm working for making *static typing feature* on XPath (elementpath package) that is necessary for completing complexType's assertions (assert definitions).

**Comment by jonathanrobie** [comment]
> XPath 2.0 is one of the most difficult parts to complete.

I sure wish there were a good XPath 3.1 processor for Python ...

**Comment by brunato** [comment]
> I sure wish there were a good XPath 3.1 processor for Python ...

XPath 1.0 and XPath 2.0 are almost done (excepting bugs), XPath 3.0/3.1 maybe an extension in the future ...
 
Working on _elementpath_ is really a pleasure, because the method on which the package is based is pretty good (Pratt's parser with Python metaclasses), but better to end and consolidate _xmlschema_ first.

**Comment by jonathanrobie** [comment]
Cool!  I didn't know about _elementpath_.  I can use that ...

**Comment by brunato** [comment]
Still delays for XSD 1.1. Currently I'm fixing the code using the W3C XSD test suite. There may be a new release whitin some days. 

All the XSD 1.1 features are written except (partially) the open-content model and the wildcards. Also VC namespace has to be added, probably also to XSD 1.0 class. Then, after tested the XMLSchema11 class with W3C suite, the XSD 1.1 support will be added to package API.

**Comment by brunato** [comment]
XSD 1.1 support is finally done! It's available with the release v1.0.14.

Full XSD 1.1 support.It's tested also with [W3C XML Schema 1.1 test suite](https://github.com/w3c/xsdtests) (~100% of schema tests and ~97% of instance tests passed).
